### ISSUE TITLE
reduce font size of filters/facets

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1001]
In hyrax, the font sizes for the filters/facets and their subfacets is too large. reduce the font size by adding an override to `app/assets/css/heliotrope.scss`

- [x] font size for facet is back to normal
- [x] font size for sub facets are normal

**Comment by sethaj** [comment]
![hyrax-whitespace](https://user-images.githubusercontent.com/3924142/26943620-3b320d74-4c54-11e7-8dd9-c2223a219466.png)

Fulcrum w/ Hyrax has extra whitespace....

![cc-no-whitespace](https://user-images.githubusercontent.com/3924142/26943632-4504580c-4c54-11e7-9a3f-95de8d43e386.png)

That Fulcrum w/ CurationConcerns did not have.
