### ISSUE TITLE
Samvera Community Update - June 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1011]
Due June 23rd

This was May's update, which never went out since Nabeela has changed schedule to every other month:

May's update:

In addition to continuing to develop the epub reader application, Cozy Sun Bear, the Fulcrum team has started to investigate and prepare for the migration to Hyrax from Curation Concerns. As we have been ramping up our work on building a Platform Administrator dashboard, we're particularly interested in seeing how much of this development comes standard in Hyrax and what level of customization will be necessary to accommodate our publishing workflow.

We are also focused on preparing the remaining publishing projects from our Andrew W. Mellon Foundation-funded grant for release to Fulcrum, with the expectation that these will be live before the end of May.

**Comment by mbakeryo** [comment]
@jgmorse Hope it's ok that I assigned this to you. I'm not going to get a chance to work on this before I leave. I put a 6/23 due date on this, as Nabeela has told me she'll send out the update at the end of the month.

**Comment by jgmorse** [comment]
Update submitted to Nabeela June 27th:

Fulcrum: In addition to continuing to develop the epub reader application, Cozy Sun Bear, the Fulcrum team has completed a migration to Hyrax from Curation Concerns; this will be reflected in the 2.0 release of Heliotrope, scheduled for July 10.  As we have been ramping up our work on building a Platform Administrator dashboard, we're particularly interested in seeing how much of this development comes standard in Hyrax and what level of customization will be necessary to accommodate our publishing workflow.
