### ISSUE TITLE
cache EPUBs

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1012]
In heliotrope, load time for the initial page and subsequent sections is extremely slow. To improve load times, cache EPUBs to see if that improves page load performance.

**Comment by sethaj** [comment]
I'm not sure what the best way to do this is, but if we end up using the Rails cache, one trick that we're currently doing with cached IIIF images slices is to use the FileSet's timestamp in making the cache key. That way if the FileSet (epub in this case) changes, a new chached version is created relflecting the changes. 

https://github.com/mlibrary/heliotrope/blob/master/config/initializers/riiif_initializer.rb#L23

We end up cleaning out the old expired cached images through a cron job. https://github.com/mlibrary/heliotrope/blob/master/lib/tasks/clean_cache.rake#L11

Maybe we'd want to do something similar with epubs.

**Comment by gkostin1966** [comment]
I kick off a job to unzip the epub into the application ./tmp/epubs directory when it is first viewed which resulted in a noticeable performance increase.  After unzipping the epub the  job removes all epubs that have not been viewed in the last 24 hours.  Perhaps this will be sufficient.  If not, well, we'll cross that bridge further down the road.

**Comment by jmcglone** [comment]
@gkostin1966  this sounds great to me!
