### ISSUE TITLE
Can't create new monographs

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1013]
In hyrax, when creating a new work (monograph) you must upload a file. Right now on the monograph new page, file uploads aren't working in staging (nectar). They **do** work in development.

![new-monograph-not-found](https://user-images.githubusercontent.com/3924142/26985684-a054b710-4d12-11e7-9abb-64edcfd1bd73.png)

The error on staging is this:

```
I, [2017-06-09T12:50:35.357557 #29856]  INFO -- : Started POST "/uploads/index.html" for 141.211.43.239 at 2017-06-09 12:50:35 -0400
F, [2017-06-09T12:50:35.359886 #29856] FATAL -- :   
F, [2017-06-09T12:50:35.359956 #29856] FATAL -- : ActionController::RoutingError (No route matches [POST] "/uploads/index.html"):
F, [2017-06-09T12:50:35.360003 #29856] FATAL -- :   
F, [2017-06-09T12:50:35.360055 #29856] FATAL -- : actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Note that the route "/uploads/index.html" is being called (via javascript) and does not exist.

In development instead of the error the correct route of "/uploads/" is called and the correct controller is found:

```
Started POST "/uploads/" for 127.0.0.1 at 2017-06-09 10:22:03 -0400
Processing by Hyrax::UploadsController#create as JSON
...
```
I think the javascript in question is here: https://github.com/samvera-labs/hyrax/blob/master/app/assets/javascripts/hyrax/uploader.js#L30

- [ ] Find out why "index.html" is being appending to the "/uploads/" route on staging (an apache config?) and fix it.

**Comment by sethaj** [comment]
The `nectar:/hydra-dev/heliotrope-deploy/config/deploy.rb` cap script creates a shared "~/public/uploads" directory that was causing Rails to think "/uploads/index.html" existed on staging/preview/production but not development.

We're not using "~/public/uploads" and I believe we never have. I think it's an artifact from the deployer-template project. I've removed it from the heliotrope deploy script and everything seems to be working fine now, file uploads work fine.

**Comment by conorom** [comment]
Unfortunately `public/uploads` is where CarrierWave defaults to as well. I'll change it to `public/upload` for now so as not to cause a regression here.
