### ISSUE TITLE
Hyrax Questions????

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1019]
- [x] Move this to a Google Doc, share with team; keep in mind when to move it (if ever) to wiki.

Running questions about Hyrax ...

![hyrax primary creator](https://user-images.githubusercontent.com/10866980/27047410-06abb04e-4f76-11e7-9a42-bc162bae9d6e.png)

1. What is a 'primary creator role'?  Is there a conflict between heliotrope and hyrax use of the primary creator field? Ok for now.

2. File Set versioning; how is it done? Is there a use case?  If there is no use case, we could turn off for now. 

3. Share with option;  Should we use Hyrax 'user' and 'group' file sharing access levels?  Is there a use case?  Should we use Hyrax 'roles'?  Investigate as part of the workflow discussion.

4. Works can have child works.  Would this be useful? Leave defaults for now.

5. Collections can have works.  Would this be useful? Leave defaults for now.

6. Works have administrative sets.  Could we use administrative sets for publishers? 

7. Hyrax (Sufia has this too) has it's own GA/stats features that look like this: https://deepblue.lib.umich.edu/data/works/9z902z875/stats. Is that something we want to enable?

**Comment by jgmorse** [comment]
1. Role would have values like 'author' or 'editor', most commonly.  We store this same kind of metadata in our title mgmt system and include it in our CrossRef and ONIX feeds.  We should make use of this.

7. If it's easy, then sure!

**Comment by mbakeryo** [comment]
The doc is here: https://docs.google.com/a/umich.edu/document/d/1k_lAPhI7XyaIl6WudNFfD7PpsDvPbA0Xyi7Gm-Q_8W4/edit?usp=sharing
