### ISSUE TITLE
Adding File to Imported Monograph Fails

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1031]
Adding a new file to a monograph created by the importer fails with a `undefined method `user_key' for nil:NilClass` in the resque job.

This references this line, which makes me think the problem lies in the way a dummy user is used for the import:
https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L24

- [ ] adding a file to an imported monograph works using the UI

**Comment by sethaj** [comment]
It appears that Hyrax really needs an actual user in Monograph.depositor which up until now we've been able to avoid when adding monographs with our importer (using a dummy "system" user that is not persisted).

We tried overriding the various jobs that need a User but there appear to be quite a few of them and I'm not sure that taking all of that code from hyrax (and then maintaining forever) is the best idea. We considered creating a persisted "importer" user, but we'd need to maintain that on dev/staging/preview and production and we'd need a shared password... not great.

Given that in the future it's likely that the importer (or something like it) will be kicked off by users in the UI for batch imports, it seems like we'll want the actual user to be associated with the import. So we'll add that functionality into the importer (see #1038) now. 

For already with imported monographs if you need to add another FileSet via the UI just set the monograph.depositor to an actual user (it doesn't actually seem to matter who).

```
> m = Monograph.find 'NOID'
> m.depositor = "a_real_user_email@address.com"
> m.save!
```

Then you can add FileSets through the UI. Note that you can still add new FileSets to an exisiting monograph at any time with the importer without having to set the depositor to an actual user.
