### ISSUE TITLE
Add importer user flag

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1038]
In Hyrax Monographs seem to need an actual depositor. Up until now we've been able to avoid this using our importer and a fake "system" user, but we're running into problems with that approach.

As discussed in #1031, we should add user support to the importer.

- [x] Add a required flag for the importer command line that takes an email address as an argument `script/import -u "my_fulcrum_email@address.com"`
- [x] If the user doesn't exist in the system, the importer should fail with an error message saying to use a valid email address.
- [ ] Make sure the newly created monograph has a `Monograph.depositor` of the provided email address.
- [ ] Decide if current Monographs in the system should have their `Monograph.depositor` set to an actual user and maybe do it (maybe with a rake task, in staging/preview/production) or write a new Story for that.

With hyrax this means that the user with the email address used to import will probably have the entire importer process (new monograph, all the new file_sets) in their "Activity Log". Which seems ok. In the future, if/when we tie the importer into the UI, this seems to especially make sense.

**This is blocked until we can discuss and agree on this together as a group (lots of people are out right now)**

**Comment by conorom** [comment]
RE: checkbox #3, I'm not adding a specific warning in the importer as this not getting set would be the same as any other metadata not being set and we don't have any warnings for any of the rest of them either. It's tested in the spec.

RE: checkbox #4, I think we deal with this in a new ticket if and when assets ever get added to these pre-existing monographs by a non-technical person in the UI. Don't see the point of a ticket now. It would take a few minutes to set the monograph depositor in the console for all production monographs if we needed to.
