### ISSUE TITLE
Identify metadata field required for a monograph to be published

### ISSUE THREAD

**Issue by jcoyne** [mlibrary/heliotrope#105]
Then update the publishing process:

https://github.com/curationexperts/heliotrope/blob/master/app/jobs/publish_job.rb#L5-L8

**Comment by sethaj** [comment]
We need to decide what the relationship between "published" and CC's "visibility"

**Comment by mbakeryo** [comment]
We need to have further discussion about what this means: one publish button for all (monograph + assets) or individual publish button for each (monograph, assets).
