### ISSUE TITLE
Deploy PSUP Vol 1 to Production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1052]
- [x] deploy latest release tag branch to production
- [x] import Penn State
- [x] Generate handles for Penn State

**Comment by mbakeryo** [comment]
7/6/17: Awaiting Patrick's feedback (asked him to review Preview).

**Comment by mbakeryo** [comment]
7/11/17: Heard back from Jennifer:  I’ve taken a look at the links and everything is looking great. We don’t need any changes and prefer to have Volume 1 at the top as shown.

**Comment by sethaj** [comment]
The default_admin_set has been loaded onto production (as well as the default workflow) so importing on production should be good to go.

**Comment by conorom** [comment]
Importing worked fine.
