### ISSUE TITLE
Deploy NYU Press to Production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1053]
- [x] set `production: true` for nyupress in `db/publishers.yml`(did manually also on `bulleit-1`) to import content on 20170907)
- [x] tag release (not relevant with manual editing of `db/publishers.yml`)
- [x] deploy latest release tag branch to production (not relevant with manual editing of `db/publishers.yml`)
- [x] alter `/l/local/fits/xml/fits.xml` in the manner described in #1096
- [x] run seeds.db to create NYU Press (create in UI if this fails) NOTE: logo had to be uploaded manually afterwards
- [x] import assets, overwrite derivatives ~(as PRIVATE!!)~ NOTE: we decided against the PRIVATE thing, it won't allow folks to iterate on embed stuff etc.
- [x] contact A&E to setup redirects - all NYU Press URLs redirect to fulcrum.org/nyupress
nyupress.fulcrumscholar.org -> fulcrum.org/nyupress
nyupress.fulcrumservices.org - > fulcrum.org/nyupress
nyupress.fulcrum.org - > fulcrum.org/nyupress
- [x] Generate handles for NYU Press
- [x] Add NYUP's google analytics id (UA-77847516-11) to press database table for NYU Press (should be done as it's part of `db/publishers.yml`
- [x] Get embed codes
- [x] Change monograph to Open (see above this is no longer necessary as private mode not used)
- [x] Add link to OA to book description: http://openaccessbooks.nyupress.org/details/9780814731956/.

**Comment by mbakeryo** [comment]
Blocked by NYU Press - need their ok.

**Comment by mbakeryo** [comment]
Sent these embed codes to NYUP on 9/11/17: https://docs.google.com/document/d/1iXCKoOdb_kwTP8K05LCn8-yy9u-24Ad0CPSjNPxzURo/edit

**Comment by jgmorse** [comment]
Handles created.   For the record, I recorded my process in #847 .

**Comment by mbakeryo** [comment]
10/3/17: emailed NYUP about linking to OA title (which pubbed on Sept 29).

**Comment by mbakeryo** [comment]
10/5/17: emailed A&E to request redirects.
