### ISSUE TITLE
Create widgets for Google Analytics - Publisher level

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1055]
Publisher level analytics should be viewable via the dashboard. 

Refer to this usage report as an example of the  metrics to display: https://datastudio.google.com/org//reporting/0B-CNui8jTxj4MHByUVlwRnJfQWc/page/1M

First pass, thinking life to date (for Date Range)is acceptable; add more nuance as we get feedback.

Metrics of interest:
- [x] Users 
- [x] Sessions
- [x] Page views
- [x] Bounce rate
- [x] Top Pages
- [x] Top Landing Pages
- [x] Channels
- [x] Referrals

**Comment by moseshll** [comment]
Am getting data into Rails cache and just displaying raw data for now. Considering next steps for turning some of these into graphs.
<img width="1187" alt="2017-07-25 04 14 14 pm" src="https://user-images.githubusercontent.com/26604206/28591606-55455520-7154-11e7-92e8-002911eeba11.png">
