### ISSUE TITLE
Troubleshoot NYUP assets in epub

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1067]
NYU Press has provided us with their epub.

They indicated 3 issues they are having with the assets in Readium after using the sample embed codes provided:

- [x] Too much gray space around the assets. This has been resolved via ticket 884

- [x] "Your browser doesn't support iframes" message is unnecessary. I believe this should be resolved simply by deleting that message from the embed code (by the publisher).

- [x] The videos are too wide in Readium. "The challenge is that because Readium is flowable, the column width can change as readers re-size their screen." Note that they did not enter any width or height to the embed code.

For this ticket, upload their epub to Readium and use the embed codes from Fulcrum to see what they are seeing and adjust as necessary.

The epub (named 9780814731949_EPUB3.epub) is available here: https://drive.google.com/drive/folders/0B-CNui8jTxj4UXNubmVTcEtnRjg?usp=sharing

**Comment by jmcglone** [comment]
Created tickets #1082 and #1083 to address the last item (videos are too wide).

**Comment by mbakeryo** [comment]
@jmcglone and @conorom 

From NYUP:   
Re: Embedded captions: We agree that the embedded caption can be removed.
Re: Video stills:  for the Onion video example you included, we don't think it's important to select a specific spot in the embedded video for display purposes--the default still looks OK. However, we're wondering if the other videos all look the same at the beginning. When I clicked the links for the Simpsons videos in the draft embed codes below, it looked like they all begin with a white screen. If that's the case, for those videos we would want the ability to select a meaningful image farther into the video.
