### ISSUE TITLE
Samvera Community Update - August 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1070]
- [x] Write up Samvera community update (remember to include a high-level mention of something we had to do to make Hyrax work for us)- CLARIFICATION: PER DEVS AT 8/15 SPRINT DEMO PREP, THIS WAS ONLY MEANT FOR SOMETHING WE HAD DONE DURING THAT MONTH - THUS, NO MENTION THIS MONTH
- [x] Allow for devs to review/modify
- [x] Send to Nabeela - due August 18

Looks like we're skipping July; Nabeela sent June update in early July.

This was June's update:

Fulcrum: In addition to continuing to develop the epub reader application, Cozy Sun Bear, the Fulcrum team has completed a migration to Hyrax from Curation Concerns; this will be reflected in the 2.0 release of Heliotrope, scheduled for July 10. As we have been ramping up our work on building a Platform Administrator dashboard, we're particularly interested in seeing how much of this development comes standard in Hyrax and what level of customization will be necessary to accommodate our publishing workflow.

**Comment by jgmorse** [comment]
Here's my update for August.  All taken from Sprint Demo Prep docs, so hopefully it's accurate:


* Embedding Fulcrum-hosted media into Epubs, allowing video and hi-res images to be experienced in context of a responsive, valid Epub-formatted ebook with the same viewing capability as on our Samvera platform.

* Work has begun on adding a second index for full text search within specific Samvera object bitstreams (in our case, Epubs).

* Implemented a Draft mode for certain Works.

* Prevent the display of empty search facets.  (If there is no metadata in a facetable category, that category will not display in the facets.)

**Comment by mbakeryo** [comment]
In the future, make sure to use this document: https://docs.google.com/document/d/13qfwnYbAHjEzECKbCJBszUae4VLxNbVyqWxrgi4l2dA/edit
