### ISSUE TITLE
Customize Asset UI for PDFs

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1076]
Ensure we have optimal display of PDFs in the asset view.

Questions: Do we display a PDF in Leaflet?

- [x] If no Leaflet, increase the size of the thumbnail to fill the width of column.
- [x] Remove white space between thumbnail and caption.

Make sure if the item is downloadable that the only method to download is via the Download button.

**Comment by conorom** [comment]
In the case of the two pdfs-that-should-be-images we discussed earlier the whitespace is because they are unedited scanned photos with a large chunk of the scanner lid included.

**Comment by jmcglone** [comment]
@conorom @mbakeryo fairly certain this can be closed now, especially in looking at:

https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/f4752g770
