### ISSUE TITLE
Add a second index for Full Text in a single epub

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1078]
As a reader, I have selected a book and I would like to search inside it.

- [ ] A search from inside CSB returns hits from a second index that indexes the full text of the Epub.

**Comment by sethaj** [comment]
I'm going to break this up into three tickets:

- [ ] Complete EPub indexes, #1130
- [ ] Complete heliotrope search API, #1131
- [ ] Integrate heliotrope EPub search into Cozy Sun Bear
