### ISSUE TITLE
Add responsive height and width to video embed code

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1083]
To allow the videos to dynamically resize when embedded in an epub, add height and width attributes with values that allow the video to be responsive when a browser window is resized, or a different display setting is applied to an EPUB and reflows the text.

**Comment by conorom** [comment]
#1094 touches on this by using percentages for width/height. Now that width/height are being set in the technical metadata for videos, we can work out the aspect ratio for use here. Though we might have to "magic number" extra space for the Able Player controls.
