### ISSUE TITLE
audio/video back button styling

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1084]
I'm guessing this is to do with Able Player's styling.

Steps to reproduce:
- open an audio or video asset
- click one or more tabs (i.e. info, permissions, stats, tech info)
- use the back button till you get back to the anchorless FileSet URL

Able Player will be gone and/or messed up in various ways.

**Comment by mbakeryo** [comment]
Suspect: Turbo Links

**Comment by conorom** [comment]
There seem to be several parts to this one:
- Able Player is not Turbolinks compatible
- Jquery Turbolinks is not Rails 5/Turbolinks 5 compatible and so is not "fixing" Able Player to work with Turbolinks
- With the first two problems overcome (either by hacking `ableplayer.js` without Jquery Turbolinks or by including Jquery Turbolinks with a Turbolinks 5 monkey patch), Able Player will be loaded with the Turbolinks restore/"restoration"/back button event, but then you hit caching problems that give you two or more copies of the Able Player controls. The solution here is to disable Turbolinks caching on the audio and video media views.

There certainly may be smarter ways to fix all this. Here is a fun picture of a "hamburger" of player controls:
![screen shot 2017-08-09 at 4 06 35 pm](https://user-images.githubusercontent.com/9595080/29141573-c6c0109a-7d1c-11e7-8a79-7b4e2140080a.png)
