### ISSUE TITLE
Re-load preview/staging data

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1087]
After staging and preview are wiped and replaced with production data, re-load the staging and preview data that we'll need:

- [x] NYU
- [x] ACLS Humanities E-Book
- [x] Heliotrope Press EPubs

**Comment by mbakeryo** [comment]
https://heliotrope-preview.hydra.lib.umich.edu/presses/new

Subdomain HEB

**Comment by jmcglone** [comment]
HEB is already on staging and preview!:

https://heliotrope-preview.hydra.lib.umich.edu/heb
https://heliotrope-staging.hydra.lib.umich.edu/heb
