### ISSUE TITLE
Prioritize Gabii usability feedback

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1090]
Based on feedback from Gabii usability testing, create a prioritized list of improvements to Gabii beta.

**Comment by mbakeryo** [comment]
Use this doc: https://docs.google.com/document/d/1IpJhgf8fxTwfn9HuXxDpQRWILCG_JtknSrjDIrC2v7Y/edit#heading=h.r35dyc7tqk11

**Comment by jmcglone** [comment]
Prioritized issues are in this doc:
