### ISSUE TITLE
Access/read poster derivative

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1103]
- [x] Fallback on thumbnail if you don't have a poster
- [x] Set the poster to display on the asset page
- [x] Set the poster to display on the embed page

**Comment by conorom** [comment]
Because of this method, it's easier (and probably more correct) to call this derivative 'jpeg':
https://github.com/samvera/hyrax/blob/0b2536d2cd1531218d97305afd535f0af98743cb/app/services/hyrax/derivative_path.rb#L58
