### ISSUE TITLE
Investigate Penn State's GA

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1106]
Catalog page is currently showing zero pageviews.

**Comment by moseshll** [comment]
According to the production Rails cache, the last page view entry (which is used to calculate the number of views) by date was June 2. I surmise the `ga_cache.rake` cron job is not running, or is erroring out?

**Comment by moseshll** [comment]
(Oops, hit "Close and comment" by accident.)

**Comment by mbakeryo** [comment]
Once cron job is fixed (?) here is the activity for Volume 1 to check against:

Volume 1 (launched on 7/20/17) activity May 21-Sept 4, 2017:
Monograph page (kk91fk53m) = 10 pageviews (2 - 7/14/17, 1 - 7/19/17, 1 - 7/21/17, 1 - 8/2/17, 1 - 8/3/17, 2 - 8/16/17, 2 - 8/25/17)
Photo of Harriet Tubman (h415p953x) = 1 pageview (7/19/17)
Photo of the Fisk Jubilee Singers (5x21tf41f) = 1 pageview (8/16/17)
Photo of Paul Robeson (nv9352859) = 3 pageviews (7/14/17)

**Comment by sethaj** [comment]
My guess is that it's hitting a 10,000 count limit. Which is annoying since we explicitly set it for 100,000. So... I guess that doesn't work? Maybe there's something in the GA docs about this?

```
irb(main):020:0> pv = Rails.cache.read('ga_pageviews');0
=> 0
irb(main):021:0> pv.count
=> 10000
irb(main):022:0> 
```

**Comment by sethaj** [comment]
https://developers.google.com/analytics/devguides/reporting/core/v3/reference

"The Analytics Core Reporting API returns a maximum of 10,000 rows per request, no matter how many you ask for. It can also return fewer rows than requested, if there aren't as many dimension segments as you expect. For instance, there are fewer than 300 possible values for ga:country, so when segmenting only by country, you can't get more than 300 rows, even if you set max-results to a higher value."

I guess we have to rethink how we cache this...
