### ISSUE TITLE
Investigate Penn State's Google ranking

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1107]
Look at the webmaster tools

**Comment by jmcglone** [comment]
This ticket involves determining why a search engine result for Penn State's "Nothing But Love for God's Water" does not have the fulcrum page on the first page of results. Is there something Fulcrum can be doing to improve the SEO of monograph projects? Is there something in particular we can do with Penn State's title to improve its search engine ranking?

**Comment by mbakeryo** [comment]
Per our last sprint planning discussion, looking into generating a site map.

**Comment by sethaj** [comment]
sitemaps added: Note to self: will need an update to the crontab via sudo -u heliotrope-XYZ crontab -e if and when site mapper is deployed.

**Comment by jmcglone** [comment]
documentation for sitemap_generator https://github.com/kjvarga/sitemap_generator

**Comment by sethaj** [comment]
Sitemaps have been built in production:

```[sethajoh@bulleit-1:/hydra/heliotrope-production/current]$ sudo -u heliotrope-production RAILS_ENV=production bundle exec rake sitemap:refresh
In '/hydra/heliotrope-production/releases/20171207142859/public/':
+ sitemaps/sitemap.xml.gz                                723 links /    5.78 KB
Sitemap stats: 723 links / 1 sitemaps / 0m29s
In '/hydra/heliotrope-production/releases/20171207142859/public/':
+ sitemaps/sitemap.xml.gz                                723 links /    5.78 KB
Sitemap stats: 723 links / 1 sitemaps / 0m29s

Pinging with URL 'https://fulcrum.org/sitemaps/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing

Pinging with URL 'https://fulcrum.org/sitemaps/sitemap.xml.gz':
  Successful ping of Google
  Successful ping of Bing```

I'm not sure how we should trigger this in the future. Seems like we could:
1. Make a cron to do it weekly/monthly/whatever
2. Trigger it from the deploy script to update whenever we deploy
3. Since we really don't add that much content (at the moment), maybe just run the rake task manually when we need it.

I guess for now I'm leaning towards 3...

**Comment by moseshll** [comment]
The sitemap @sethaj generated was not saved because for whatever reason the `public/sitemaps/` directory wasn't created. I created it and re-generated the map in production, then verified with Webmaster that it could be accessed. A reindex is pending.

**Comment by sethaj** [comment]
I think we'll need to make some minor changes to the deploy project so that `public/sitemaps` persists across deploys. I think when we deployed the hotfix to production `2.1.1`, `public/sitemaps` went away. I'll make those changes today so that future deploy don't wipe out the sitemaps directory.
