### ISSUE TITLE
Add a redirection control field to FileSets

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1108]
This will be an optional field allowing a FileSet's page load to redirect to another FileSet (or a static page etc.). For now we just want to add the field.

- [x] decide on a name for the field that pleases everyone. Maybe redirect, redirection, redirect_to
- [x] add the field to the model
- [x] add the field to the Solr doc
- [x] add the field to the FileSet edit form (a regular single-value textbox type)
- [x] add the field label to the english internationalization thingy
- [x] add the field to the giant hash that controls CSV import/export
- [x] add the field to any places I've forgotten
- [x] add a test for the field, you could add it to the big create/edit FileSet feature test, `spec/features/edit_file_set_spec.rb`... and/or other appropriate tests

This field is going to be a single-value "control" type filed, along the lines of external_resource/allow_download etc. So not geared towards faceting, search or UI display. In any event, searching the codebase for those and working from their entries is the best way to go.

**Comment by moseshll** [comment]
I do have it in displaying in the FileSet document view (`_attribute_rows_info.html.erb`) for the sake of the test -- it can of course be suppressed.

**Comment by conorom** [comment]
Yeah, good point. I'll add a reminder to @gkostin1966's ticket to take it out of the info view (and corresponding expect(page).to have_content in the spec when he's working on #1080
