### ISSUE TITLE
Pagination next arrow bug

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1122]
The 'Next >>' link on the **bottom** of the monograph catalog is always clickable, even if there are no more results. Resulting in stuff like this:
![screen shot 2017-08-08 at 6 23 22 pm](https://user-images.githubusercontent.com/9595080/29097243-c5ae26bc-7c66-11e7-8fbb-820a81099ec0.png)

Once you're on the imaginary page of results, the top arrow becomes clickable too. Woo Hoo!

![screen shot 2017-08-08 at 6 23 37 pm](https://user-images.githubusercontent.com/9595080/29097261-d922e49e-7c66-11e7-843d-ea763e03275b.png)

- [ ] make it so 'Next >>' links are not clickable if there are no more results available (focus on bottom link)

**Comment by moseshll** [comment]
Bottom pagination seems to be from `Kaminari::Helpers::Paginator` assigning current and next page links `class="disabled"` without CSS for that class anywhere to be found.
