### ISSUE TITLE
Scrollwheel GA event tracking for leaflet zoom not working

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1126]
It looks like scrollwheel GA tracking for leaflet zoom isn't working (if it ever was). So it needs to be fixed.

https://github.com/mlibrary/heliotrope/blob/master/app/assets/javascripts/application/ga_event_tracking.js#L102

And tested in the browsers we support since the implementation will probably vary.

https://stackoverflow.com/questions/3715496/binding-to-the-scroll-wheel-when-over-a-div

GA events are really only tracked by publisher/press so they'll only work in preview (and production) but probably not in dev right now. So make-change/push-branch/deploy-branch-to-preview/test and repeat I guess.

**Comment by mbakeryo** [comment]
Maybe try using Leaflet event

**Comment by mbakeryo** [comment]
Jon will discuss with DAT in October 27, 2017

**Comment by conorom** [comment]
For now we're going to turn off scrollwheel zoom for usability reasons. But even if we end up turning it back on, I'm not sure we'll be tracking the associated event over the Leaflet map...

There are many ways for a user to zoom, even with the mouse: double-click (hold shift to zoom out), hold shift and draw a box, use the buttons. Then there are the keyboard interactions. This means that we would really need to track the triggered Leaflet events for any of this to make sense. But Leaflet doesn't make it easy to tell if actions (especially zoom) were programmatic or initiated by a user. See links below. So tracking zoom would mean every page load would track our best-fit zoom kicking in, probably resize zooming as well (EPUB reader etc). We could probably create work-arounds but given the open Leaflet issues I think it would be non-trivial and hard to maintain.

As scrollwheel-zoom tracking is broken on most browsers now, coupled with the above and the fact that this was probably not a hard requirement in the first place I think that tracking the 6 zoom/pan buttons on the map is enough. Will remove scrollwheel event tracking.

https://stackoverflow.com/questions/39893070/detecting-if-is-zoom-in-or-zoom-out-with-leaflet
https://github.com/Leaflet/Leaflet/issues/5884
https://github.com/Leaflet/Leaflet/issues/3088
