### ISSUE TITLE
Create screencast of EPUB reader

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1134]
In an effort to make sure demonstrations of the EPUB reader at various meetings/presentations, are stable.

Screencast would include:

- [x] Demo of the EPUB reader 
- [x] Demo of the EPUB reader integrated with the catalog page (how the EPUB is connected to the Fulcrum book page, etc.)

Please note: we are awaiting the director of NYUP to say it's ok that we use NYUP's Show Sold Separately as the subject of our screencast.

**Comment by mbakeryo** [comment]
8/21/17: Per Charles, "We should proceed on the basis that NYU will allow us to host a full text edition of Show Sold Separately as a Fulcrum Edition."

**Comment by mbakeryo** [comment]
We should identify the tickets that block this; use sprint planning on 8/30 to do this.

**Comment by mbakeryo** [comment]
From weekly check-in meeting on 8/23/17: Screencast:  Show only the things that work, will want to make as close to being further along as possible. Focus on monograph on Fulcrum. Will need to brainstorm and construct the script for this to ensure that all of the points have been made. Voiceover (record separately). Run this like we would typically run a live demo.

**Comment by jmcglone** [comment]
Blocked by the completion of #1157

**Comment by jmcglone** [comment]
Script/Outline of demo is in this document:

https://docs.google.com/a/umich.edu/document/d/1GukEZK0e48Ple2qAVQDIOib8uXxo4c3Jce2MvSlXrtY/edit?usp=sharing

**Comment by jmcglone** [comment]
Here's the screencast w/o narration:

https://drive.google.com/a/umich.edu/file/d/0B_JnCrIk48N0c0FkOVVZN1lRMXM/view?usp=sharing
