### ISSUE TITLE
Investigate SimplyE and BV E-Reader

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1136]
Look at these readers and see what features they have and use this as a base for what we should launch with.

**Comment by mbakeryo** [comment]
Here are the instructions on how to look at BV's E-Reader: To see any of your epubs in the new "Read Online"/"BiblioViewer" interface, look your title up at BiblioVault, choose "ePub Files" from the left navigation, then click on the "View this epub in BiblioViewer" button. Your epub will open up in BiblioViewer.

Or, for a detailed walkthrough of both customer options--"Download File" and "Read Online"--please watch our BiblioTalk from May 2017, at https://www.bibliovault.org/bv.ebook_demo_bibliotalk.epl

**Comment by mbakeryo** [comment]
Here are some screenshots of BV's BiblioViewer. I did not see search, share, annotation or citation. 

![biblioviewer](https://user-images.githubusercontent.com/17436011/29710033-afac3072-895c-11e7-804e-0be852ef0c43.png)
![biblioviewer_toc](https://user-images.githubusercontent.com/17436011/29710037-b1f7c0a8-895c-11e7-9a82-324a6fd59441.png)
![biblioviewer_settings](https://user-images.githubusercontent.com/17436011/29710040-b4a162e6-895c-11e7-8f48-16317e316cca.png)

**Comment by jmcglone** [comment]
SimplyE is a library e-reader app for iPhone, iPad, and Android. It is meant to allow users to navigate a library of ebooks (checkout books from library, download open access books) and also provides a reader for those books. Below are the basic features of the library and E-reader interface: 

Navigation of book library
- search (keyword of book metadata - not full-text);
- sort by author, title, or recently added;
- filters to let users see what content they have access to or all titles

E-Reader interface
- adjustable fonts
- background and font/type color selections;
- a slider for screen brightness

**Comment by jmcglone** [comment]
Based on our survey of readers, we should launch with the following features:

- increase/decrease font size
- sans serif/serif font style
- light/dark background control
- table of contents
- full screen mode
- page turning and scroll reading modes
- progress indicator (show position in text)

CSB has support for almost all features above and plans to support a progress indicator (CSB#64) and a fully functioning scroll reading mode (CSB#63).
