### ISSUE TITLE
Determine IE support for EPUBs

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1137]
Before we launch the EPUB reader make sure we do this.

Have message like Gabii if we can't support the browser.

**Comment by mbakeryo** [comment]
Refer to #1160

**Comment by mbakeryo** [comment]
Try to support IE 11

**Comment by mbakeryo** [comment]
Roger will bring it up with the LIT Coordinating Group.

**Comment by jmcglone** [comment]
Closing this -- new tickets have been created:

CSB: [CSB#110](https://github.com/mlibrary/cozy-sun-bear/issues/110)
Heliotrope: #1421
