### ISSUE TITLE
Usability testing on EPUB

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1144]
Conduct basic usability testing with 4-5 users on accessing and reading an EPUB in heliotrope.

Tasks to test:

- [x] finding an EPUB to read
- [x] launching the EPUB in the reader
- [x] using table of contents to get to chapter
- [x] paging through EPUB
- [x] user can identify their location within EPUB (progress indicator)
- [x] searching within EPUB
- [ ] citing the EPUB and using permalink
- [ ] changing display modes (font size, colors)
- [ ] scroll mode
- [x] closing E-Book Reader

Other things to do:
- [x] Conduct exit interview to gather basic feedback on the experience
- [x] When completed, create new tickets reflecting necessary changes to the EPUB reading experience

**Comment by jmcglone** [comment]
Some initial feedback from Charleston Jury Product Development Forum:

https://docs.google.com/a/umich.edu/document/d/1PHglPUPb78pR-_7LDts95JCekKn6wLu884SWN-TGSQA/edit?usp=sharing

**Comment by mbakeryo** [comment]
MSU UARC activity will cover some of this.

**Comment by jmcglone** [comment]
@mbakeryo is this ticket complete now that UARC is done? Do we wait until the report is delivered to close it?

**Comment by mbakeryo** [comment]
@jmcglone If you feel like the actual testing we wanted was done, we could probably close this and when we get the report, create the necessary tickets.
