### ISSUE TITLE
Investigate/Fix NYUP EPUB so TOC links work in EPUB reader

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1146]
Currently, when reading NYUP's EPUB in the reader, the TOC links do not work.

The thought is that the structure or the coding of the EPUB itself is preventing the reader's TOC from working as expected.

We should determine if this is the case and fix the EPUB so the links work.

We will want to make sure that we document how EPUBs need to be configured so we can communicate this as a requirement for Fulcrum partners in the future.

**Comment by jmcglone** [comment]
Fixed/working TOC EPUB:
https://heliotrope-preview.hydra.lib.umich.edu/epubs/gf06g265v?locale=en

File is shared in Slack

Documentation for EPUB folder structure:
https://github.com/mlibrary/heliotrope/wiki/Fulcrum-Edition-1.0-Specification

Note: internal links are not working in CSB and a ticket has been filed to reflect this (CSB#68)
