### ISSUE TITLE
Publish NYUP EPUB (Fulcrum Edition)

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1148]
Publish the NYUP EPUB to Fulcrum

MVP for EPUB reader needs to be in place:
- [x] Search - bug ticket 1189
- [x] Search results highlighting - ticket 1162
- [x] Increase/decrease font size
- [x] Sans serif/serif font style
- [x] Light/dark background control
- [x] Table of Contents
- [x] Page turning and scroll reading modes
- [x] Progress indicator (show position in text - CSB ticket 64, 1264)
- [x] Branding
- [x] Link to Read Fulcrum Edition (verify label - need to distinguish between this EPUB and the NYUPress EPUB)
- [x] Embed link to the asset page on Fulcrum (tooltip on embedded media) 1214
- [x] Obtain transcripts for videos

Also need to have the EPUB monograph page in place 

Determine if we need these done:
721 Validate an EPUB file - we could launch wout this
1137 Determine IE support for EPUBs
1158 Perform browser testing, bug fixes
1159 Brand EPUB reader - we could launch wout this
1161 Better phrase context for matched search terms
1170 EPUB search url has &amp; in it
1172 EPUB refactoring
1187 EPUB class
1190 CFI ranges don't work (BUG)
CSB ticket 69 Book title and chapter title can cause artifacts with presentation
CSB ticket 71 cleanup epub.js theme handling
#1147 Launch Cozy Sun Bear to Heliotrope

**Comment by mbakeryo** [comment]
Alex said she'd give us NYUP's final EPUB when she has it.

**Comment by mbakeryo** [comment]
Look in caption ticket to find service that was used for webvtt captions

**Comment by jgmorse** [comment]
Web service to pull SRT captions file from a Youtube video: [http://downsub.com/](http://downsub.com/)

Then convert from SRT to WebVTT here: [http://www.webvtt.org/](http://www.webvtt.org/)

(I said I'd put this in a previous ticket, but turns out I lied.)
