### ISSUE TITLE
Deploy Michigan/Turner to Production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1149]
- [x] decide if we want full text extraction on or off
- [x] import Michigan, overwrite derivatives ?
- [x] Generate handles for Turner

**Comment by mbakeryo** [comment]
Is this blocked by 1261?

**Comment by mbakeryo** [comment]
--Uploaded new cover on 11/28/17; also placed in the final folder here: https://drive.google.com/drive/folders/0B-CNui8jTxj4UkRVMS10WXIyYTQ

--Changing redirect URL that will be printed in the book from: http://www.press.umich.edu/p/selma_and_the_liuzzo_murder_trials to http://www.press.umich.edu/p/selma

**Comment by conorom** [comment]
Now that we're on Hyrax 2 there is a configuration setting that lets us Turner(!) off full text extraction without monkey patching anything. We should decide if we want to do this.

**Comment by mbakeryo** [comment]
At Sprint Demo Prep on 12/5, we decided to use OCR'd PDFs, but turn off the full text extraction.

**Comment by jgmorse** [comment]
Handles created:

> Start Time: Thu Jan 04 17:01:24 EST 2018
> ==>SUCCESS[0]: create:2027/fulcrum.4x51hj03c
> ==>SUCCESS[0]: create:2027/fulcrum.bn999674d
> ==>SUCCESS[0]: create:2027/fulcrum.fn106x94r
> ==>SUCCESS[0]: create:2027/fulcrum.rv042t060
> ==>SUCCESS[0]: create:2027/fulcrum.fj236212d
> ==>SUCCESS[0]: create:2027/fulcrum.4x51hj04n
> ==>SUCCESS[0]: create:2027/fulcrum.f4752g745
> ==>SUCCESS[0]: create:2027/fulcrum.41687h46v
> ==>SUCCESS[0]: create:2027/fulcrum.r494vk17h
> ==>SUCCESS[0]: create:2027/fulcrum.jq085j98n
> ==>SUCCESS[0]: create:2027/fulcrum.f4752g75f
> ==>SUCCESS[0]: create:2027/fulcrum.cr56n0995
> ==>SUCCESS[0]: create:2027/fulcrum.n009w228g
> ==>SUCCESS[0]: create:2027/fulcrum.m039k4903
> ==>SUCCESS[0]: create:2027/fulcrum.5q47rn74h
> ==>SUCCESS[0]: create:2027/fulcrum.t435gd000
> ==>SUCCESS[0]: create:2027/fulcrum.x633f104m
> Successes/Total Entries: 17/17
> Batch File Lines: 0
> Finish Time: Thu Jan 04 17:02:25 EST 2018
> This batch took 61 seconds to complete at an average speed of 0.2783782013493155 operations/second
