### ISSUE TITLE
Add search results highlighting

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1162]
As a reader, when I conduct a search inside an EPUB and I follow a link in the results list, I want the matched terms to be highlighted on the page so I can easily find my matched terms.

- [ ] Only matched terms/phrases are highlighted in the EPUB
- [ ] The highlighted terms/phrases match the searched term/phrase exactly

**Comment by jmcglone** [comment]
![screen shot 2017-08-29 at 8 02 03 am](https://user-images.githubusercontent.com/1686111/29820140-6ad315b4-8c91-11e7-8c10-a9254d0d18c7.png)
