### ISSUE TITLE
Fedora 4.7.4 Upgrade

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1178]
Sebastien Korner [14:56] 
Everyone, but in particular @sethajoh @conorom @gkostin @jmcglone: There is a Fedora 4.7.4 instance up on another server that has the nectar content loaded (nectar Fedora as it was Tue night). If you change your base fedora connection string from http://localhost:8080/fedora/rest to http://fedora-testing:8080/rest (note that both the path and host are different) you can test any nectar app against the new fedora. When you have a chance, can you do a quick smoke test with a Fulcrum instance? The upgrade needs were mostly driven by bugs affecting DBD, so for Fulcrum we just want to make sure there are no surprises. We'll of course provide time to run all apps on nectar against an updated local fedora on nectar before making this change in production. You can of course run manual curl commands from nectar against this new Fedora also. Let us know if anything looks wrong/wonky/whatever. Thanks!

**Comment by jmcglone** [comment]
Done on nectar. Still needs to happen on production (bulleit-1).

**Comment by sethaj** [comment]
This was finished on bulleit-1. Everything seems to be fine.
