### ISSUE TITLE
Add metatags to EPUB Reader view

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1181]
Currently, the EPUB reader lacks the metatags that appear in the `head` of the monograph and asset pages. To improve discovery and machine-readability of this page:

- [x] Add the same metatags from the monograph catalog page to the EPUB reader `head`.
- [x] Ensure the DOI for the EPUB asset is included.

**Comment by mbakeryo** [comment]
CoINs for zotero. We have this in heliotrope talk to @sethaj
