### ISSUE TITLE
Samvera Community Update - September 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1192]
- [x] Write up Samvera community update 
- [x] Check with devs to see if they had to do anything special bc of Hyrax during the last month of development
- [x] Send to Nabeela - due September 20

**Comment by jgmorse** [comment]
Here's what I've got.  Anything that should be added?

* We’ve created a screencast [Youtube link coming soon] highlighting our support for viewing Epubs with embedded, hyrax-hosted media.
* We will host a workshop on the first day of Samvera Connect to discuss the business cases Fulcrum is designed to support and possible overlap with the needs of Digital Commons/bepress users at Samvera institutions.

**Comment by mbakeryo** [comment]
Added in the link to the screencast (https://youtu.be/WdUOTzu-5hE); Nabeela sent out on 9/28/17
