### ISSUE TITLE
Add NYU Press to Fulcrum homepage

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1193]
Add to the home page:

- [x] cover of NYUP's Show Sold Separately
- [x] short description of the book/how Fulcrum is being used (or added to the experience of the book....)
- [x] link to the book on Fulcrum (links on the title, cover image and a View Project button)

**Comment by mbakeryo** [comment]
This is what I have so far:

Show Sold Separately gives critical attention to the ubiquitous but often overlooked phenomenon of audiences approaching movies and TV shows with preconceived notions about them, shaped by the onslaught of information and hype that surround them. This book examines a wide range of materials from DVD bonus materials to action figures that reveal the world of film and television that exists before and after the show. New York University Press used Fulcrum to host the book’s impressive array of video clips and images that are embedded in their open access Epub. The videos are presented using AblePlayer, a fully-accessible cross-browser media player. Users are able to pan and zoom the images from within the Epub, using the Leaflet viewer. Users are able to enjoy these media assets from the comfort of the Epub, providing them an integrated, seamless reading experience.

**Comment by mbakeryo** [comment]
Per Lisha and Alex, 10/3/17:

Show Sold Separately gives critical attention to the ubiquitous but often overlooked phenomenon of audiences approaching movies and TV shows with preconceived notions about them, shaped by the onslaught of information and hype that surround them. This book examines a wide range of materials from DVD bonus materials to action figures that reveal the world of film and television that exists before and after the show. New York University Press used Fulcrum to host the book’s impressive array of video clips and images that are embedded in the EPUB, which is available for reading in the New York University Press Open Access Books portal. The videos are presented using AblePlayer, a fully-accessible cross-browser media player. Users are able to pan and zoom the images from within the e-reader, using the Leaflet viewer. Users are able to enjoy these media assets from the comfort of the e-reader environment, providing them an integrated, seamless reading experience.

**Comment by jgmorse** [comment]
Thanks for the update @mbakeryo .  I think this is fine, though the use of past tense here strikes me as slightly odd.  Not enough to request a change though.

> New York University Press used Fulcrum to host the book’s impressive array of video clips
