### ISSUE TITLE
p class="quote" styles in CSB

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1194]
nyupress style
![p-class-quote-nyupress](https://user-images.githubusercontent.com/3924142/30336801-438a08fe-97b4-11e7-877e-41010e47b847.png)
CSB style
![p-class-quote-csb](https://user-images.githubusercontent.com/3924142/30336806-48095e0c-97b4-11e7-8e8d-9103d25dee14.png)

It looks like the vanilla CSB styles have something for `p class="quote"` that sort of turns it into a `blockquote`. Maybe we want something like that in our styles, maybe not.

**Comment by respinos** [comment]
That's from the epub's stylesheet.css.
