### ISSUE TITLE
Missing metadata causes 500 server error

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1196]
There are probably plenty of places like this in the code. Below is one I've encountered a few times. These errors will become more frequent when more stuff is created in the UI and not the CSV spreadsheet import process.

So, a FileSet never had a value for `allow_download` set. You go to download it and get a server 500.

```
FATAL -- : NoMethodError (undefined method `first' for nil:NilClass):
FATAL -- :
FATAL -- : app/controllers/hyrax/downloads_controller.rb:60:in `allow_download?'
```

- [x] fix the above with a nil check
- [x] look through the code for other "low-hanging fruit" problems with `.first` having no nil check
- [x] fix any you find!

**Comment by gkostin1966** [comment]
http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/
