### ISSUE TITLE
Command-line Monograph CSV metadata update

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1198]
A monograph has been created in the UI.

- [ ] Update its metadata and, more importantly, that of its FileSets from the command line with a focus on method reuse in a future UI trigger
- [ ] reorder the Monograph's FileSets as per matches found in the CSV file
- [ ] consider external resources. Probably file-less entries in the CSV file should be made into external resource FileSets, as long as `external_resource == 'yes'`

**Comment by mbakeryo** [comment]
Parking lot discussion

**Comment by mbakeryo** [comment]
Blocked by Hyrax 2
