### ISSUE TITLE
Dashboard list all users that have some level of privilege assigned

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#123]
**STORY**
As a platform admin, I would like to see a list of all privileged users (administrators, editors, other users with specific roles assigned) across all presses, so that I don't have to go-to each press's user page separately.

**ACCEPTANCE**
- [ ] There is a privileged users page that is restricted to platform admins
- [ ] The page lists all users that have a platform or press level role assigned
- [ ] For each user, the User ID, press(es), and role(s) is displayed

**Comment by acozine** [comment]
Related to #201

**Comment by gkostin1966** [comment]
Waiting on Sufia dashboard.
