### ISSUE TITLE
Handle EPub TOC better

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1231]
It looks like there are a couple (few? many?) different ways EPubs use Table of Contents. EPub.js has some code that shows some of the differences: https://github.com/futurepress/epub.js/blob/v0.3/src/navigation.js. Because we need to display the EPub's chapters in heliotrope, we need to be able to get the chapter titles from the TOC no matter how the EPub TOC is formatted. The nyupress book uses a `toc.ncx`, but moby-dick uses a `toc.xhtml`. We need to be able to handle both (or more?) cases.

**Comment by sethaj** [comment]
This from http://epubzone.org/news/epub-3-packaging-and-metadata makes me think we shouldn't support `toc.ncx` since we're only supporting EPUB3.

"The spine may also contain a toc attribute that identifies an NCX file. The NCX is how EPUB 2 specified navigation; it is superseded in EPUB 3 by the Navigation Document (nav, an XHTML document). In order to enable an EPUB 3 to be rendered by an EPUB 2 reading system, it has to include an NCX even though it also has to have a nav to conform to EPUB 3. Until EPUB 2 reading systems have become obsolete (no sign of that in the near future), publishers generally need to include both. The collision is prevented by the fact that the nav is pointed to by the manifest’s nav property and the NCX is pointed to by the spine’s toc attribute:
```
<package ...>
   ...
   <manifest>
      ...
      <item id="nav"
            href="nav.xhtml"
            media-type="application/xhtml+xml"
            properties="nav"/>
      <item href="toc.ncx"
            id="ncx"
            media-type="application/x-dtbncx+xml"/>
      ...
   </manifest>
   <spine toc="ncx">
      ...
   </spine>
</package>
```"

**Comment by gkostin1966** [comment]
Sounds good to me!

Would could charge the publisher a fee to convert their EPUB < 3 into a Fulcrum EPUB 3 edition.
