### ISSUE TITLE
Prep for Samvera Connect

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1251]
- [x] Poster, use AAUP poster with updated logos plus Architecture Overview diagram, Feature Matrix (Due November 1st) (Jeremy/Jon)
- [x] Plan out workshop (meet October 19th)
- [x] Create powerpoint presentation (Jeremy)
- [x] Pre-workshop survey, email Google Form and link from program to known attendees (due October 27). Questions: What is their specific interest in the workshop/hoping to get out of it?,  What is their library currently doing with publishing?, What systems are they using? How are you using Samvera now?  (MBY)
- [x] Screenshots/wireframes (stuff that isn't built yet), screencasts, etc. 
- [ ] Identify and obtain needed supplies (notepads, pens, markers, etc.) Also identify what conference will supply?
- [x] prepare feature matrix for Digital Commons, Hyrax, Fulcrum (Jon)
- [ ] contact Samvera members who are DC schools, encourage them to attend (Jeremy)
- [ ] List of Library Publishing Coalition members who are also Samvera members 
that he can update, perhaps use as a slide (Jon)

Planning doc: https://docs.google.com/a/umich.edu/document/d/1pb7deOCfAw6TUVXtMccCU_ab5eBlp25BWuD38KRmpoI/edit?usp=sharing

Workshop, as advertised:

Monday, November 6, 2017: 9:00-12:00
Hyrax as a Publishing Platform: An Update on Fulcrum

Following the acquisition of Digital Commons / bepress by Elsevier, there’s been a surge of interest in supporting campus publishing activity in Samvera. Fulcrum is in its third year of developing a publishing platform on Samvera (and is now running on Hyrax). While we’ll keep the structure of this workshop flexible to respond to the interests of the participants, we’ll work from this basic structure:

1. Presentation of the service model that Fulcrum is being built to support.
2. Presentation of the features and architecture of the platform, with an emphasis on Epub support and publishing workflows.
3. A group discussion of the kinds of publishing-related service requests attendees are hearing from their communities, in particular from those who are concerned about the Elsevier acquisition of Digital Commons / BePress, and what interest is there in a coordinated community effort around support for publishing and fully-encoded texts.

Presenters: Jeremy Morse, Melissa Baker-Young, Jon McGlone

Audience: Managers

**Comment by jgmorse** [comment]
The Adobe Illustrator file for the [Fulcrum poster presented at AAUP 2017](https://drive.google.com/open?id=0B-18ovAEQgwvcWJTM1d6OHBBSHBCVGI5ak1DTGJaR3h3TEpR) can be modified for Samvera Connect.  At minimum, the Hydra logo should be swapped with that for Samvera.

**Comment by mbakeryo** [comment]
Jon will switch out the Samvera logo for the poster and give the file to Jeremy.

**Comment by jmcglone** [comment]
Updated poster is here:

https://drive.google.com/open?id=0B_JnCrIk48N0MHpMbk81MzNVelE

**Comment by jmcglone** [comment]
List of Samvera partners that do Library Publishing: https://docs.google.com/a/umich.edu/spreadsheets/d/1iBFJncGHz4He3KpamBlc53RRLfG-2HrFTRzIsdp4Hzk/edit?usp=sharing

**Comment by mbakeryo** [comment]
Workshop participants: https://docs.google.com/spreadsheets/d/1W6jNxKcDLDqUCM3sBqnluq_UzdahzteNml0kQLjHETY/edit#gid=996905553

**Comment by mbakeryo** [comment]
Survey (draft) is here: https://docs.google.com/forms/d/e/1FAIpQLSd1RW0VDYdr_oUhPYaNNcc8gSuQqqTNhpCaiU7OBobUrQ3FqA/viewform

**Comment by mbakeryo** [comment]
Session notes: https://docs.google.com/document/d/1yI-UkgcfTPlRzUwiPr1pjaYsf7B6xJiWXuM890tmoI8/edit#heading=h.s64ulu7reloa
