### ISSUE TITLE
Turbolinks? Yea or Nay?

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1254]
...Or the third option is to review how we're using it and decide if we should have a best practices doc. Like how to tweak events to suit Turbolinks, bypass its cache when appropriate and test forward/back restoration behavior with greater regularity.

Somehow documenting the problems we've been having (and their workarounds) so we run into Turbolinks-related bugs less often in future might suffice.

note: Hyrax uses Turbolinks so we may be stuck with it if we can't turn it off for parts of the app only or if Hyrax gets very slow without it. Looks like the community plays whack-a-mole with Turbolinks and are content to do that. We can, of course, decide to follow suit (as a group) and close this ticket.

A selection of related issues follow. I think the fix for the first one went into CC:
https://github.com/mlibrary/heliotrope/issues/83
https://github.com/mlibrary/heliotrope/pull/750
https://github.com/mlibrary/heliotrope/issues/1084
https://github.com/mlibrary/heliotrope/issues/1127
This one has more detail on Turbolinks caching bugs and fixes:
https://github.com/mlibrary/heliotrope/issues/1228

update 20180403:
https://github.com/mlibrary/heliotrope/issues/1615
https://github.com/mlibrary/heliotrope/issues/1634
https://github.com/mlibrary/heliotrope/issues/1646
https://github.com/mlibrary/heliotrope/issues/1706

**Comment by conorom** [comment]
decision: Turbolinks is too fundamental to Rails to mess with. We just need to be aware of the problems it can cause, especially with any JS code, caching etc.

**Comment by sethaj** [comment]
We keep having various turbolinks problems, so maybe it's time to reopen this.
