### ISSUE TITLE
Investigate acce￼ssible PDFs

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1261]
We have 16 PDFs for Turner/Selma and the Liuzzo Murder Trials (UMP).

The PDFs were made up of page scans.

Find the files here: https://drive.google.com/drive/folders/0B-CNui8jTxj4ZEJnNXM4cTA3c28
Find OCR files here: https://drive.google.com/drive/folders/0B-CNui8jTxj4TkgyNUF3ZWhEd2s

- [x] Determine what our definition of accessible PDFs (from page scans) is
- [x] Determine how to meet this definition

Some resources:
- https://www.w3.org/TR/WCAG-TECHS/pdf.html#pdf_notes
- http://blogs.adobe.com/accessibility/2012/01/wcag-2-0-techniques-for-pdf.html
- http://www.adobe.com/accessibility/pdf/pdf-accessibility-overview.html

**Comment by jmcglone** [comment]
MBY has OCR'd the PDFs. We should provide the raw text of the page scans as available for download.

**Comment by mbakeryo** [comment]
Melissa should give Conor the ocr'd PDFs

**Comment by mbakeryo** [comment]
OCR'd PDFs are here: https://drive.google.com/drive/folders/0B-CNui8jTxj4TkgyNUF3ZWhEd2s

**Comment by jmcglone** [comment]
Based on conversation between @jmcglone and @mbakeryo on 12/6, we decided that:

- When creating PDFs from born-digital content, it is much easier to follow the guidelines for creating accessible PDFs and we should try and follow those guidelines.

- When creating PDFs from digitized content, especially page images, it is not easy to follow best practices and we should instead focus on providing an alternative method of access, like the raw OCR text file, much like how Library Digital Collections have been doing (see Bentley's Michigan Daily Digital Archive project) for quite some time.

- In larger scale projects, the OCR'd text in raw format does not need to be cleaned-up.

- For Turner, we should provide a download of the raw OCR text file that was generated by Adobe Acrobat Pro. We do not have the capacity or ability to create a fully accessible PDF that includes markup, etc.  Providing download of raw OCR text for an asset is new functionality for Fulcrum - it is equivalent to a transcript for an audio file or translation for an asset. This feature will require a new ticket.

- In the future, when we are given text-based assets that need to be digitized, we will want to ask the vendor to provide us with OCR text files along with the digitized content.

**Comment by mbakeryo** [comment]
To make raw OCR text file: In Adobe Reader Pro you can do Save As > Format: Text (Plain) and then in the settings make sure you change the Encoding to UTF-8.

**Comment by conorom** [comment]
Given that we're going to import the Turner PDFs OCR'ed with default Hyrax full-text-extraction settings, there will be an ExtractedText derivative file created and saved in Fedora automatically, whose contents will mirror these:
https://drive.google.com/drive/u/1/folders/0B4dD_OG8SQ_ZWTY5ZlZ1M045MXM

I don't know how hard it would be to add a download button to the asset page for this txt file, but it seems like that would be the first thing to try here.

Is it worth doing a comparison of this versus what Adobe Reader produces?

**Comment by conorom** [comment]
For the Turner sample I've been looking at, the Adobe and Hyrax/Solr/Tika extracted txt only differ in white space, especially the use of new lines. The actual detected _characters_ are of course the same (not very good), as the OCR step was done in advance by Acrobat and the same file used in both cases. Regarding the different white space, the Acrobat version looks better in some places, and the Tika version in others.

The reasons for these differences seem quite complex (probably different treatment of markup tags and maybe also x/y positioning data). I've scanned some of the links below but I think it's beyond the scope.

If we're set on adding an extracted text download then I guess we need to decide whether to use a new metadata field (like @jmcglone proposed) or the contents of the extracted text file in Fedora. The file I've been looking at is 9000 lines and it's not nearly the largest PDF we have so far. Kind of nasty to be pasting that into a metadata field, but it offers an easy way to update it through the UI. Obviously we wouldn't display it on the asset page!

I've explored changing `downloads_controller_behavior.rb` to allow the downloading of the extracted_text file and that seems to work too, but there would be some (possibly major) overhead in allowing this file to be changed in the UI. Parking lot!


I'm leaving some links here for posterity:
https://issues.apache.org/jira/browse/TIKA-724
https://issues.apache.org/jira/browse/NUTCH-2318
https://issues.apache.org/jira/browse/SOLR-4679?focusedCommentId=13733776&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13733776
https://stackoverflow.com/questions/7954788/pdfbox-adding-white-spaces-within-words

**Comment by mbakeryo** [comment]
Refer to work in #1423. 

Closing this investigation ticket. Put suggested steps for making accessible in file format guide (not final): https://docs.google.com/a/umich.edu/document/d/1u0y5ACjKxGvzZiuFSHCa5pDkvTFZVDZlRga5p4ya7yQ/edit?usp=sharing
