### ISSUE TITLE
Create Fulcrum EPUB version of Gabii Vol 1

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1265]
As we prepare to migrate Gabii from DLXS to Fulcrum, we'll need to create an EPUB version of the DLXS fully encoded text.

- [x] Migrate Gabii DLXS XML to EPUB 3.1
- [x] QA to ensure there was no data loss in the migration
- [x] Review tagging, accessibility, images, and tables for Fulcrum spec

**Comment by jmcglone** [comment]
This is currently being done by APEX

**Comment by mbakeryo** [comment]
Apex is to deliver by February 14th.

**Comment by jmcglone** [comment]
Delivered by Apex. Available at https://drive.google.com/file/d/1w-s7GdiVNktbJH8rvQwjiEfmN2UJjBRV/view?usp=sharing

**Comment by jmcglone** [comment]
From Apex: 

There are three primary points of interest for which Apex would appreciate your input.
 
1.  EPUB file structure – Apex split chapters into subparts by sections to reduce the size 
of individual HTML + the images associated with each HTML. This was done to facilitate fast loading in an online environment. So that each subpart is recognized as part of a chapter Apex inserted a metadata identifier for HTML as a proposed mechanism for Fulcrum to filter files to enable chapter by chapter release of content.
 
2. EPUB tagging – The EPUB was tagged to be compliant with EPUB 1.0 Accessibility Guidelines with the exception of integrating alt-text and long-descriptions. Does UM have any concerns or suggestions for improvement related to the deployment of this tagging model on Fulcrum?
 
3. Image treatments – Please confirm that the adjustments made to render the images supplied as source meet UM expectations.
 
We have tested the EPUB in Readium, Vitalsource Bookshelf, Firefox epub reader, on the iPad using iBooks, on an Android device using Gitden Reader. If UM uses any other rendering application for assessment as a preference, please let us know.

**Comment by jmcglone** [comment]
Updated versions based on feedback at https://drive.google.com/drive/folders/1KnpQw9vSG9lAFBepWFLzdeAyfJ64AzdX?usp=sharing

**Comment by mbakeryo** [comment]
Waiting for Apex to send final. Expecting by 3/15/18.

**Comment by jmcglone** [comment]
received full EPUB on 3/19/18
