### ISSUE TITLE
Add HREF for EPUB Chapter to Monograph Catalog TOC Tab

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1268]

**Comment by respinos** [comment]
cozy-sun-bear detects when the request has a chapter path after the `#`, e.g. `#/OEBPS/xhtml/01_Cover.xhtml`.

We could support a CFI: `#epubcfi(/6/24[Chapter04]!/4/20/13:38)` if that's more convenient.

**Comment by sethaj** [comment]
I think `#/OEBPS/xhtml/01_Cover.xhtml` is probably ok for now. It's just for chapters, so the CFI would be a "base" CFI anyway (`#epubcfi(/6/24[Chapter04]!`). It's hard to imagine we'd ever need more granularity from heliotrope, but who knows.

I guess if it's easier to keep all navigation in CSB consistant with "CFI-all-the-time" we should do that, but if supporting both kinds of navigation is easy enough I'm inclined to just leave it as is.

**Comment by respinos** [comment]
Something we should revisit. epub.js manages file paths for its table-of-contents, but in theory CFIs are more portable. SHAMELESS GREEN!
