### ISSUE TITLE
Add download widget to EPUB Reader

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1270]
Add the download widget to the EPUB view on heliotrope

- [ ] If the EPUB asset has downloading enabled, display the download icon
- [x] Clicking the download icon opens a modal menu that allows users to select the filetype and download the file.
- [ ] If a MOBI or PDF file is uploaded as an asset to the monograph make that downloadable too

**Comment by mbakeryo** [comment]
We need this for April HOB.

**Comment by jmcglone** [comment]
There are some TODO and comments in the e_pub show page related to #1270. I'm thinking you may have to create "representatives" for PDF and MOBI too so that we can know what files to serve.
