### ISSUE TITLE
Create Handles for monograph/assets

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#13]
For each partner Press (starting with Northwestern):
When a Press's metadata template is stable:

Once content is imported in production:
- [x] Choose a format for the handles. [ hdl.handle.net/2027/fulcrum.${NOID} ]
- [x] Seth sends Jeremy a CSV with fields: path_to_asset, filename, section
- [x] Jeremy creates handle batch file and registers the handles
- [x] Jeremy updates the CSV and passes back to Seth
- [x] Seth adds the handles to the respective assets' metadata
- [x] Run new export for Northwestern that contains handles plus whatever other fields they need (filename, title, handle). This should be in the same order as the metadata template.

**Comment by sethaj** [comment]
There is a rake task to do part of this, file_set_urls.rake. Currently is outputs:

"/concern/file_set/NIOD", "Filename"

which we can then assign handles to. But we need to add "Section Name" since "Filenames" are not unique and we need to be able to match generated handles back to the row in the metadata template.

**Comment by sethaj** [comment]
Here's how to run this in production:

`sudo -u heliotrope-production RAILS_ENV=production bundle exec rake "heliotrope:file_set_urls[bz60cw269]"`

**Comment by jgmorse** [comment]
Updated acceptance criteria to match new workflow.

**Comment by jgmorse** [comment]
Note that the script I used to create the handle batch file is here:
tang:/quod-dev/bin/f/fulcrum/makeHandleBatchFile.pl

It should Just Work if the next CSV file is in the same format as the one for Northwestern.

**Comment by jgmorse** [comment]
Here's the perl one-liner to add a new column 1 to the CSV containing the handle:
`perl -pi -e 's%^"(/concern/file_sets/)(\w+)"%"2027/fulcrum.$2","$1$2"%g' `

**Comment by jgmorse** [comment]
Changed last acceptance criteria; it will be easier and safer to export metadata (including handles) for presses who need to know what handles have been assigned, rather than try to get handles into existing metadata templates without errors.

**Comment by jmcglone** [comment]
Handle system gem exists for communicating with handle server:

https://rubygems.org/gems/handle-system/versions/0.1.1

OSU has implemented this with Sufia 7
