### ISSUE TITLE
Replace Penn St●	[ate PDFs that are images with actual image files

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1305]
In Vol 2. there are a series of assets that are images but the uploaded file is a PDF scan of the image. Replace these with actual images files.

- [x] do this on preview first and see how it goes.
- [x] if all is clear, go ahead and do it on production

The assets are:
Photo of Signing
Photograph from office of Rev. Clay Evans

**Comment by conorom** [comment]
After more experimentation, I'd rather delete the existing unwanted PDF files (and associated extracted text files) beneath the files container (which is left as-is) and _then_ attach the new JPG images to the FileSet (or rather the file container beneath it... retaining the FileSet NOID etc) than try to add a version to the FileSet and work from there. When using versioning a lot of tidying up is required. I'm not sure all of the (weird) behavior I see when uploading subsequent versions with a different filename/extension/type (PDF->JPG or vica versa) is even intended. One good example is here:
https://github.com/samvera/hyrax/blob/b64ea8e0d20a60327c2e7a37a919d6daef8d9f00/app/indexers/hyrax/file_set_indexer.rb#L14
... where you end up with all the mime_types indexed in Solr, like `jpeg (JPEG EXIF, JPEG File Interchange Format, Portable Document Format)`
You also end up with weirdness with multiple/mixed-up file sizes and checksums which I don't want to deal with in future. Looking in Fedora, the way the previous metadata "clings" to previous versions is also hard to understand. Best to start from scratch methinks... in the console like so:

```
FileSet.find('999999999').files.each { |f| f.delete }

Hydra::Works::AddFileToFileSet.call(FileSet.find('999999999'), File.open('/path/to/file.jpg'), :original_file)

CharacterizeJob.perform_later(FileSet.find('999999999'), FileSet.find('999999999').original_file.id, nil)

# Now change the FileSet's label ('downloadFilename' in Fedora). This would also have to be done if going the versioning route.

# At this point label is still 'file.pdf':
FileSet.find('999999999').label # => "file.pdf"

f = FileSet.find('999999999')

f.label = 'file.jpg' # => "file.jpg"

f.save!
```


For the record, deleting the files in the UI (just the first step) works like this:

Go to the files container (which is a child of the FileSet and a parent of the actual files):
http://localhost:8984/fedora/rest/fedora_namespace/99/99/99/99/999999999/files

Go into each of the children of this container, i.e. the actual files.
For images there will be only the `http://pcdm.org/use#OriginalFile`, but PDFs additionally have a `http://pcdm.org/use#ExtractedText` type file.
Click the red "Delete" button under the "Delete Resource" heading on the bottom-right of the page.
NB: do not delete the parent file container or the above console commands to add a new file will fail.

**Comment by conorom** [comment]
This is done and tested in production.
