### ISSUE TITLE
Determine how to allow users to customize display image

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1310]
Publishers may wish to choose a specific page of a PDF or a keyframe of a video, etc., to represent the asset on the catalog and asset pages.

Determine if there is a way for users to make this selection by providing a representative file for an asset. (Or is this just something that Fulcrum dev/rep will have to do for the user.)

**Comment by mbakeryo** [comment]
Per standup on 10/26/17, use Turner to help us figure out the best way to do this.

**Comment by conorom** [comment]
Chances are we'll want to add user-uploaded derivatives to the repository (as a backup), like a custom thumbnail for a PDF (the Turner use case) or custom thumbnail/poster for a video (which we've done many times):
https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/services/persist_derivative.rb

In cases where the playback derivative is the repository asset (MP4s) it probably does not make sense to do this, only to offer the ability to copy the repo asset to the derivatives folder. But would it make sense to back up the WEBM version in the repository? You could argue that subsequent versions of the derivative generation tools might not produce the exact same thing, thus warranting the repo backup.

**Comment by mbakeryo** [comment]
@conorom Can we close this ticket? This work was done on ticket 1405, right?

**Comment by conorom** [comment]
@mbakeryo Don't close yet. We need to duplicate the thumbnail upload/customization for video "posters" and then discuss whether both posters and thumbnails (especially custom thumbnails) should be stored in the repository.

**Comment by mbakeryo** [comment]
@conorom Sounds good!

**Comment by conorom** [comment]
Remaining work and discussion is split out into #1506 and #1508. Closing.
