### ISSUE TITLE
Create feedback bug report widget

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1337]
Heliotrope's side 

- [x] Add widget that allows users to submit problems/issues with the reader
- [x] Google form

**Comment by jmcglone** [comment]
After discussing with the team we decided a first iteration could be a link to a Google Form. We will want to monitor this and create a feedback mechanism that does not take the user away from the application in the future, and can also record other things like browser version, what book they were reading, what page they were on, etc. for troubleshooting purposes.
