### ISSUE TITLE
Upgrade to factory_bot

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1350]
Warning:[rake --tasks] DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from require at /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292)
Running via Spring preloader in process 16055

**Comment by sethaj** [comment]
This is a hyrax2.0.0 deprecation warning.
