### ISSUE TITLE
Remove e-book reader's footer

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1367]
While testing with users, it was reported that the copyright and publisher information was not helpful and confused readers. They thought this information was in relation to the platform, not the book.

- [x] Remove the footer controller when invoking CSB in the EPUB view
- [x] Ensure this information is contained in the "Information" widget/modal

**Comment by jmcglone** [comment]
Early screenshots of the re-worked navigation slider will re-use the footer space.

**Comment by respinos** [comment]
To enable the current Bibliographic Information widget:

```
cozy.control.bibliographicInformation({ region: 'top.toolbar.right' }).addTo(reader)
```

This is the metadata that's presented, if found:

```
    var metadata_fields = [
      [ 'title', 'Title' ],
      [ 'creator', 'Author' ],
      [ 'pubdate', 'Publication Date' ],
      [ 'modified_date', 'Modified Date' ],
      [ 'publisher', 'Publisher' ],
      [ 'rights', 'Rights' ],
      [ 'doi', 'DOI' ],
      [ 'description', 'Description' ],
    ];
```

**Comment by moseshll** [comment]
Some options for positioning the bib INFO button, if anyone would like to weigh in…

<img width="242" alt="2018-02-22 01 43 29 pm" src="https://user-images.githubusercontent.com/26604206/36557923-91c34172-17d7-11e8-8688-9df3416758f4.png">
<img width="197" alt="2018-02-22 01 54 35 pm" src="https://user-images.githubusercontent.com/26604206/36558088-f72b953c-17d7-11e8-83b8-e750d5d35c47.png">
<img width="214" alt="2018-02-22 01 44 14 pm" src="https://user-images.githubusercontent.com/26604206/36557924-91d5dd46-17d7-11e8-9b18-0bee6ac0c478.png">
<img width="603" alt="2018-02-22 01 44 57 pm" src="https://user-images.githubusercontent.com/26604206/36557925-91e6d3ee-17d7-11e8-8634-1340fd2707a0.png">

**Comment by respinos** [comment]
Maybe the CSS could introduce a border when `button + button` is true?

**Comment by jmcglone** [comment]
I'm partial to having the info button near the search icon (with the addition of borders for when buttons bump up against each other coming later). My reasoning for the location of the info button: It would be good to keep the "preferences" and "full screen" buttons grouped together as they are a set of tools/utilities for the reading experience, and the info button grouped with buttons/labels that are tied to the text itself (TOC, media, searching in text, etc.)

FWIW, I am okay with this getting merged without the button on button border if it easier to capture and work on that in a separate ticket.
