### ISSUE TITLE
Investigate tables as assets

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1381]
As a publisher, I would like to include tables as supplemental material.

How should a table be delivered/in what format?

Our current use case is Gabii. Tables were provided as Excel spreadsheets. In order for them to be part of the narrative on DLXS, they were transformed into HTML and embedded in the text. 

On Fulcrum, how should the tables be included as supplemental material? 

Is there a difference between the display version (perhaps the HTML) and the download version (perhaps the Excel)?

Important to note that while I haven't done a deep dive into the Excel versions of the tables, at a cursory glance, I could not see an easy match-up between the Excel file and the HTML version. It's possible also that the Excel version that was delivered is no longer the latest/greatest version as work was done to build the HTML version.

Here is the folder where the Excel files that were delivered reside: https://drive.google.com/drive/folders/0B-CNui8jTxj4U1ZFM19iM3lHcjA?usp=sharing

To view the HTML versions, go to Gabii on quod: https://quod.lib.umich.edu/g/gabii/mpub9231782?rgn=main;view=fulltext

Here is the current metadata template: https://docs.google.com/spreadsheets/d/1OzoRlpLJuYQ98mvxPZb05hfCHc9yzKfLm1KfVcYNBcc/edit#gid=1573645093

**Comment by conorom** [comment]
Per recent discussions we're thinking of storing each table as a FileSet and were leaning towards CSV for the storage format. Given that all tables use one or more colspan values, I think this will look sloppy, i.e. this:
![screen shot 2018-01-05 at 4 38 02 pm](https://user-images.githubusercontent.com/9595080/34629773-6be7f3dc-f237-11e7-8371-7bb900f71ca0.png)

...becomes this:
![screen shot 2018-01-05 at 4 37 40 pm](https://user-images.githubusercontent.com/9595080/34629784-778a6472-f237-11e7-9469-95fe3a48feab.png)


We can overcome this by storing them as Excel files or OpenDocument Spreadsheets.

Some other concerns:
- where to store the table caption in the downloaded file (file name, extra row at the top?)
- there are lots of charts (images), often paired with a corresponding table. Why are we not offering these for download? Maybe all of this stuff should only be in the EPUB.
- quality issues (starred/asterisked entries in tables with no explanation; missing table 7B referenced in text)

**Comment by conorom** [comment]
We've decided to either include tables as individual Excel files or all together in an archive of some sort. Awaiting feedback from authors.
Closing this ticket.
