### ISSUE TITLE
Improve keyboard control experience for panning images

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1382]
Based on #1302, the keyboard experience for panning images in the the Leaflet image viewer can be improved. Currently you can pan using keyboard controls, but a keyboard user would need to focus off the zoom buttons in order to pan.

Do we add pan buttons to the image viewer? Can we allow the current method for keyboard panning (directional buttons) to happen while a user is still focused on the zoom buttons?

**Comment by conorom** [comment]
By rights, shouldn't a keyboard user be using the +/- keys to zoom? I mean, with the focus on the map, the +/- keys combined with the arrows let you pan and zoom without tabbing, i.e. while keeping the focus on the map the whole time.

Regarding the use of the superimposed zoom buttons, here is a Leaflet issue which basically made the focus stick to the zoom button you just tabbed to and activated with the keyboard. Seems it was jumping back to the map before this and that was much worse:
https://github.com/Leaflet/Leaflet/issues/3159

One interesting thing is the demo map linked at the bottom of the issue, where a focus style is applied to the map. It seems to me that at least makes things very clear:
http://kara.62.free.fr/zoomfocus_3275/
Though I'm finding it hard to picture how this would look/work in an embedded map in an iframe.

... and here is the plugin we'd probably use for superimposed panning arrows. The size of the demo here is comparable to our assets page map:
http://kartena.github.io/Leaflet.Pancontrol/

**Comment by jmcglone** [comment]
@conorom Ok, here's some feedback:

1) Agree, we need to add focus style on the Leaflet viewer. This might work if added to `heliotrope.scss`:

```
figure #image:focus {
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
```

2) Can you put the zoom buttons above the pan buttons? The rationale here is that user will probably not pan unless they zoom first. After that switch is made you'd also want to test that the focus order matches the visual order, so that zooming comes first, then panning buttons.

Having a visual indication of the panning functionality *should* indicate to (all) users that this feature is available, so I don't really think there is more we need to do for this ticket if the above two things are taken care of.
