### ISSUE TITLE
Modify breadcrumbs for child publisher's views

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1384]
As a reader and publisher, I need to know who the child publisher's parent is as indicated by the breadcrumbs on a page.

![screen shot 2017-12-07 at 10 26 10 am](https://user-images.githubusercontent.com/1686111/33722888-3001cc36-db39-11e7-93b6-ab24133b5eda.png)
 
- [ ] If a publisher has a parent publisher, modify the breadcrumb to make the parent publisher "home". 

For example, if "Gabii Project" were the publisher, the breadcrumb would be:

Home / Gabii Project / A Mid-Republican House from Gabii

And Home links to the U-M Press publisher catalog page.

- [ ] Should a breadcrumb appear on the child publisher's Publisher catalog page? Currently that page is not designed with a breadcrumb in mind.

**Comment by jmcglone** [comment]
If using publisher for this case, would need to have the parent publisher added to the breadcrumb.

**Comment by jmcglone** [comment]
This ticket has been re-named and its acceptance criteria has been modified to reflect Gabii as a publisher (not sub-brand).

**Comment by sethaj** [comment]
I think whether or not a breadcrumb should appear on a child publisher's page is something we should spend time thinking about. If we decided we want to do it, we'll make a new ticket.
