### ISSUE TITLE
Support Aboutware for Gabii

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1388]
For books, I would like to store specific "aboutware" information about the book. In the case of Gabii, things like revision history, links to reviews of the product, help pages, and other information.

Per our discussion on 1/18:

- [x] Develop a method to store HTML files as assets tied to the monograph work
- [x] Allow those pages to be added as tabs on the monograph catalog page
- [x] Display the HTML asset in assigned tab

Existing mockups are at https://drive.google.com/open?id=0B_JnCrIk48N0SllfT251THJPM0E

NOTE: this does not have to be solved now, but consider the use case of when a publisher wants to put images or other media in the HTML -- where are those files stored and how are they referenced in the HTML?

**Comment by jmcglone** [comment]
This ticket has been modified based on our parking lot discussion on 1/18

**Comment by sethaj** [comment]
See #1394. I think this is done?
