### ISSUE TITLE
Create sample Gabii EPUB

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1393]
For prototyping Gabii on Fulcrum, create a sample Gabii EPUB from the text in DLXS. Be sure of the following:

- [x] It's a valid EPUB 3.1 file and uses good semantic HTML5
- [x] includes a figure
- [x] incudes a table
- [x] has more than one section
- [x] includes internal links
- [x] include SU links to points in the 3-D model

**Comment by mbakeryo** [comment]
We have a fake epub we use for testing so maybe similar to this:
https://github.com/mlibrary/heliotrope/blob/master/lib/spec/fixtures/fake_epub01.epub which was created by hand and then zipped into an epub using this method: http://www.ebookconverting.com/zip-up-an-epub-on-a-mac

**Comment by tbelc** [comment]
Created initial sample epub consisting of Gabii information. It is a valid epub with valid HTML5, but I don't consider it be clean and well formed.

It contains several tables, images, 4 top level sections with a few subsections, and several valid internal links. 

There are several SU links in the markup. The epub contains a JS file that is referenced by one of the content documents to provide a simple implementation of displaying a popup window.. In Calibre, the popup windows do appear when a SU link is selected. Currently, the links do not point to a 3D model.

The sample is available on my Google drive. Contact me for the link.

**Comment by jmcglone** [comment]
Feedback document at https://docs.google.com/document/d/1dKylUJIPcQ6rT0gREg17Wc1bOXMPrxNLq3s9PB7b1xo/edit
