### ISSUE TITLE
Import sample Gabii to staging or preview

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1395]
- [x] Import sample EPUB
- [x] Import DLXS database as single external resource
- [x] Import sample media that is part of the sample EPUB
- [x] Import latest compressed WebGL

**Comment by mbakeryo** [comment]
Gabii metadata template: https://docs.google.com/spreadsheets/d/1OzoRlpLJuYQ98mvxPZb05hfCHc9yzKfLm1KfVcYNBcc/edit?usp=sharing

The Gabii Final files folder with the assets: https://drive.google.com/drive/folders/0B-CNui8jTxj4clBvUWR1YnpVODA

Summary of the files and some questions that will need to be answered once on preview: https://docs.google.com/document/d/1IQUetuowoOWeD0_wOvAuJqsr2GpZQb4rXMajFp-TFjw/edit?usp=sharing
