### ISSUE TITLE
Modify EPUB view for Monographs with WebGL asset

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1396]
If an EPUB monograph has a WebGL and other special assets (database) associated with it, include a custom UI of cozy-sun-bear that includes:

- [x] a link to the database
- [x] link to media
- [x] #1441 3-D model toggler
- [x] #1441 WebGL viewer
- [x] style the 3D model panel
- [x] calculate webgl aspect ratio on resize

See wireframe: https://drive.google.com/file/d/0B_JnCrIk48N0SEtjQ0pIdzhqNTg/view?usp=sharing

**Comment by sethaj** [comment]
See #1396
