### ISSUE TITLE
Display assets associated with a monograph

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#14]

**Comment by shanitajohn** [comment]
Wireframe reference: http://mlibrary.github.io/elderberry/press/book/index.html

As a first pass for release 0.2, make a catalog search results page scoped to assets that belong to a certain monograph.

For now, results will be unsorted, we will write a future story that outlines the default sort should be the asset order.

Acceptance criteria
- [ ] If you're on the main catalog page and you click on the monograph title the user should see a page that looks like the above wireframe.

**Comment by sethaj** [comment]
AC: One of the facets/filters should be sections

**Comment by sethaj** [comment]
"As a general public user, I should be able to see the title of a file and what resource type it is in the search and browse listings"

**Comment by sethaj** [comment]
- [ ] Show monograph thumbnail
- [ ] Show Asset thumbnail for each search result
- [ ] Complete Monograph detail sidebar
- [ ] Change search results to be like elderberry
- [ ] Show correct facets
- [ ] Create the Section facet
- [ ] Write tests
- [ ] Make sure permissions are working (preferably in a test)
- [ ] Preserve monograph file addition functionality for privileged users
