### ISSUE TITLE
Samvera Community Update for November/December 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1404]
- [x] Write up Samvera community update
- [ ] Check with devs to see if they had to do anything special bc of Hyrax during the last month of development
- [ ] Send to Nabeela - due December 13

**Comment by jgmorse** [comment]
Here's my draft; it was pretty easy to identify the highlight this time! Any objections to the direct link to the Google Form?

> It’s a landmark month for Fulcrum as we have now published the first [fully digital book](https://hdl.handle.net/2027/fulcrum.w0892995q) on the platform, which is [readable in our Cozy Sun Bear Epub reader](https://hdl.handle.net/2027/fulcrum.t722h883s). Lots of recent development on CSB has focused on its accessibility, so please [let us know](https://docs.google.com/forms/d/e/1FAIpQLSeY04WhBtHGSXONu3jGiYnOcVzZxzHi3FGbS9ELg8rJdMpgpw/viewform) if you observe any issues (or if you have any other feedback).
> 
> Heliotrope is now on Hyrax 2.0.0! We’ve added a lot of information on our [GitHub wiki](https://github.com/mlibrary/heliotrope/blob/master/README.md) for anyone curious about our project; those looking deeper may be interested in the [notes and slides from our Samvera Connect workshop](https://docs.google.com/document/d/1yI-UkgcfTPlRzUwiPr1pjaYsf7B6xJiWXuM890tmoI8) in November.
