### ISSUE TITLE
CSB "Skip to main content" anchor

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1409]
When navigating CSB with the tab key on any "page" you will soon get to the "Skip to main content" anchor. In fact, on a fresh load of the EPUB this is the first tab item you will get. If you hit enter on this link you will get infinite loading.
Also it shunts the reader down when it appears which seems unintended.

- [x] remove this
OR
- [ ] fix this

**Comment by jmcglone** [comment]
In thinking this over, I'm advocating for keeping skip links, but moving them over to cozy-sun-bear proper. So, essentially:

1. Removing the skip link in heliotrope's epub show page (skip link is coming from `app/views/layouts/boilerplate.html.erb`)
2. Placing "Skip to main content" (the EPUB) and "Skip to table of contents" (the TOC modal) links in cozy-sun-bear.

@roger - do see any potential problems with this approach?

**Comment by jmcglone** [comment]
#2 could also be done on the heliotrope side as a widget, however I am not sure heliotrope's knowledge of the proper ID for the TOC is not clear to me. For example, the `id` attribute looks dynamically generated:

```
<div class="cozy-modal modal-slide left" id="modal-1515174711905-334" aria-labelledby="modal-1515174711905-334-title" role="dialog" aria-describedby="modal-1515174711905-334-content" aria-hidden="false">
```

**Comment by respinos** [comment]
(The ids are dynamically generated.)

What about:

* heliotrope sets up the skip `<div>`
* heliotrope configures cozy-sun-bear to fill in skip links in said `<div>`
* cozy-sun-bear does something appropriate
  * link to the main viewer
  * opens the table of contents panel

Do you ever have lists of skip links? Not that I'm advocating for it --- the contents panel as target seems easier to hook into vs. whatever the current iframe is.

**Comment by jmcglone** [comment]
The new work has moved to:

Heliotrope -> #1461 and 
Cozy Sun Bear -> [CSB#121](https://github.com/mlibrary/cozy-sun-bear/issues/121)
