### ISSUE TITLE
Show child publisher's monographs on the parent publisher's catalog page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1413]
As a publisher, I would like the monographs associated with all my children publishers to appear on my publisher catalog page.

- [ ] Create mockups and user flows that include monographs from a child publisher on its parent publisher catalog page.
- [ ] Should the parent publisher catalog page list only the monographs, or should it also list the child-publisher?

**Comment by mbakeryo** [comment]
For MVP have Gabii show up on Michigan's publisher page.

**Comment by conorom** [comment]
based on recent conversations I'm simply displaying child publishers' monographs alongside their parent's on the latter's press catalog page
