### ISSUE TITLE
E-Reader should show message to IE11 and below users

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1421]
Because not all features of cozy-sun-bear work for IE10 and IE11, we should let those users know their browser is not fully supported when they open the e-reader.

On the e_pub show page:

- [ ] use existing third-party library [bowser.js](https://github.com/lancedikson/bowser) to detect IE11 and below
- [ ] show a [bootstrap modal alert message](https://getbootstrap.com/docs/3.3/components/#alerts) that reads: "Internet Explorer {{ Version # }} is not fully supported and some features of this e-reader may not work as expected. We recommend you upgrade your browser to a current version of Edge, Firefox, or Chrome for the optimal reading experience."
- [ ] allow the user to close the alert message

**Comment by mbakeryo** [comment]
Currently compatible.
