### ISSUE TITLE
Download a FileSet's ExtractedText file

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1423]
- [x] Enable the downloading of a FileSet's ExtractedText file
- [x] use `extracted_text` as the `file` URL param

This ties in with #1261

**Comment by mbakeryo** [comment]
I've put together a pretty lame example of multiple format types on one asset page with the OCR disclaimer. More to do here, but this is a start to a document to try and determine the best way to move forward: https://docs.google.com/document/d/1KDBh5jCth5R53MUPli8ZjQxy1asfN9KE13-EaM7X_hg/edit.

I appreciate any comments you may have. 

This is also related to #1429

**Comment by mbakeryo** [comment]
This is blocked by Apex - waiting for the final files.

**Comment by conorom** [comment]
I'm reissuing a rebased PR for this work where the method that decides whether the FileSet's `extracted_text` association has a non-zero-size file available always returns false in production. I've tested that the download button no longer appears on staging assets with extracted text.

If nothing else, the code provides a place to work from if and when we want to add the downloading of custom/new FileSet associations (`accessible_version` or what have you).
