### ISSUE TITLE
Disable survey

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1445]
Disable the survey mechanism on heliotrope.

**Comment by conorom** [comment]
I'm going to move the two survey divs (monograph catalog and FileSet/asset page) into respective partials and then comment out the rendering of those partials.

**Comment by conorom** [comment]
Decided to move the JS/CSS out as well so re=enableing the survey required uncommenting the following 4 lines:
app/assets/javascripts/application.js
`// require application_survey`
app/assets/stylesheets/application.css
` * require application_survey`
app/views/monograph_catalog/index.html.erb
`<%# render 'survey' %>`
app/views/hyrax/file_sets/show.html.erb
`<%# render 'survey' %>`
