### ISSUE TITLE
EPUB loading issues

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1459]
Investigate loading issues with Gabii EPUB

https://heliotrope-preview.hydra.lib.umich.edu/concern/monographs/hm50tr73g?locale=en

- [x] Diagnose what is causing the Story section to bring CSB to a halt
- [x] Is it caused by too many links in that section?
- [x] Does the Story section need to be broken into several parts?
- [ ] Search is also a problem, and most likely linked to the diagnosis

**Comment by sethaj** [comment]
Take a look at http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Reader

**Comment by jmcglone** [comment]
Breaking this into parts helped solve the performance issues in paging the EPUB, but search issues still remain

**Comment by jmcglone** [comment]
Tim will discuss with Apex what they are doing to address the performance issues and if they are planning to break this into separate chapters/sections like we are.

**Comment by jmcglone** [comment]
Testing search locally with the Apex encoded EPUB and performance is not terrible. A search for a word like "courtyard" which has over 70 matches throughout the text took about 5 seconds. It would still be a really good UX idea to open the Search Results modal (after hitting enter in search form or clicking search icon) and display a loading icon/gif while waiting for results to display.
