### ISSUE TITLE
Batch ingest for multiple monographs

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1477]
Using the same metadata template, I want to ingest multiple monographs to Fulcrum. 

- [ ] The ingest should support one template file that contains monograph metadata, a cover, and the EPUB file for each monograph.
- [ ] Test to see what the threshold is for ingesting batches of monographs and their associated works (eg, 100, 200, etc)

**Comment by mbakeryo** [comment]
MBY will set up a meeting this sprint so we can figure out how to move forward with this.

**Comment by mbakeryo** [comment]
Blocked by 1475
