### ISSUE TITLE
Initiate Monograph batch upload via GUI

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1482]
As a user, I want to upload a batch of monographs and their associated assets through the administrator dashboard.

**Comment by mbakeryo** [comment]
Related to 1477

**Comment by mbakeryo** [comment]
We don't need this for the ACLS migration, but we will need for future MPS needs.

**Comment by conorom** [comment]
When the time comes to do this, it might make sense to revisit Google Drive integration as the UI batch upload mechanism:
https://github.com/samvera/browse-everything
