### ISSUE TITLE
Determine asset metadata needs/desirability for HEB frontlist titles

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1484]
Specifically, the media in /img/a/acls, NOT in imageclass.  Do ACLS want to put in the work of making these assets?

**Comment by mbakeryo** [comment]
Is this blocked by HEB meeting on June 8th?

**Comment by jgmorse** [comment]
This was discussed by phone with Chris @ ACLS on 5/7. We'll only whatever minimal metadata we can algorithmically assign for these assets.
