### ISSUE TITLE
Add new press to config files

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#150]
**STORY**
As a platform admin, I'd like an easy way to add new press definitions, so that I don't have to do it manually from the rails console.

**DETAILS**
Right now, trying to re-run `rake db:seed` results in an error because the seeds task tries to re-create presses that already exist.  

**ACCEPTANCE**
- [x] I can add new press definitions to a config file and run an update script (rake db:seed or something similar) to add new presses
- [x] I can edit the press definitions config file and rerun the update script to change the name, description, or logo for an existing press
- [x] Re-running the update script with no changes to the config file does not produce an error (i.e. it's basically a no-op)

**Comment by jmcglone** [comment]
Resolved by #414
