### ISSUE TITLE
Set order of authors for monograph

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1504]
In Gabii, the order of additional authors for a monograph as they are input in the metadata form is not held when displayed in the UI. The order of additional authors in the form should match the order that is displayed on the show pages for a monograph.

- [x] use a freeform field for display

**Comment by conorom** [comment]
I take it the definitive order of the editors and authors will be in the order they appear on quod? Let me know so I can add them to the CSV.
```
Rachel Opitz, Marcello Mogetta, and Nicola Terrenato, Editors

Written and crafted with Tyler Johnson, Antonio F. Ferrandes, Laura Banducci, Francesca Alhaique, Laura Motta, Shannon Ness, Jason Farr, Sam Lash, and Matt Naglak
```

**Comment by jmcglone** [comment]
Yep, what's on quod.lib is the correct order!

**Comment by jmcglone** [comment]
Use as a freeform field for display

**Comment by jmcglone** [comment]
Revisit contributor role and editor field in Spring.
