### ISSUE TITLE
EPUB search for "page image" epubs

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1511]
EPUBS that have `rendition:accessMode="visual"` are essentially "page image" epubs with some text OCR (*not* markup!). How can search work with these? Should it? What's the expectation for "page image" epubs?

**Comment by sethaj** [comment]
Right now my understanding is that each "page image/fixed layout" epub will have a corresponding OCR text file for each image.

We can run search off of each text file (and consider them a chapter for the current sqlite style indexing?)

However getting a CFI that will actually correspond to a syntax highlighted result probably won't happen.

Because there's no syntax highlighting in the epub itself (via CSB), do we need a separate "search results" page for this?

**Comment by mbakeryo** [comment]
Blocked by 1477
