### ISSUE TITLE
Upgrade to Hyrax 2.0.1

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1517]
- [ ] as stated in the release notes "Update your Gemfile to use version 2.0.1 and run `bundle update --conservative hyrax`"

More details:
https://github.com/samvera/hyrax/releases/tag/v2.0.1
https://github.com/samvera/hyrax/compare/v2.0.0...v2.0.1

**Comment by jmcglone** [comment]
Agreed to wait for Hyrax 2.1

**Comment by conorom** [comment]
RE: 2.1, I'm wary that data can be corrupted somehow. I'm sure the migration notes will be improved, but it's not trivial, I don't think (see link). Definitely something to try out in dev/staging first. Possibly backup Fedora as well if there's any chance things will be messed up.
https://github.com/samvera/hyrax/issues/1596
