### ISSUE TITLE
Samvera Community Update - February 2018

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1536]
Due 2/16/18

**Comment by jgmorse** [comment]
Here it is:

> Seth Johnson and Conor O’Malley are participating in the Hyrax Analytics Working Group (HAWG) community sprint.
> 
> Experimenting with encoding fixed-layout, page-scan EPUBs that will perform well in our Cozy Sun Bear ebook reader.
> 
> As an example of enabling flexible metadata to accommodate publishing needs, we’ve created a new metadata field called Authorship Display (free-form text) in order to display a specific order of the authors/editors/other collaborators of a title, as well as to accommodate special roles. For example, with Gabii, we need to have the three main editors and then nine people with a written and crafted by attribution.
> 
> Usability and accessibility testing is underway, conducted by Usability/Accessibility Research and Consulting at Michigan State University. We will have a report back on their findings by March.
