### ISSUE TITLE
Gabii assets in Media and downloadable from EPUB

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1537]
Per feedback from Rachel:

- [x] Make all tables available individually in the media gallery
- [ ] Link each asset from caption in EPUB (including tables)
- [x] In Media gallery, option to download all tables as a zip file

**Comment by conorom** [comment]
Can you confirm that Excel format is OK? CSV is off the "table" <groan> unless someone reformats the header rows on these. ODS file could be an easy alternative, too, if sticking to free format is important.

**Comment by mbakeryo** [comment]
Will need author to extract out the tables and to fill in the metadata template for tables 1-17.

**Comment by mbakeryo** [comment]
Link to  asset page in the caption; do for the tables bc of the download. Not doing the zipped file option.
Will have to import monograph as a draft to be able to do this. Noted this in release steps for Gabii ticket (#1563)
Need to have time in order to do this/make sure this.

**Comment by mbakeryo** [comment]
Broke apart huge table and uploaded individually (and added metadata).

**Comment by mbakeryo** [comment]
Rachel would prefer .csv format for tables, instead of Excel. I converted the Excel files into .csv and sent to Rachel to ok. The formatting was lost on .csv and 2 of the tables (Table 2 and Table 27_A_and_B) had different numbers.

**Comment by mbakeryo** [comment]
Yes, we will do the zipped file in the Media Gallery.

**Comment by mbakeryo** [comment]
These are the questions/requests that should go to the Gabii team when they preview:


Tables: Rachel requested that the tables be made available as .csv files instead of Excel. There are 2 tables that when converted to .csv files they were completely changed, meaning the numbers are no longer the same as what was shown in the Excel file. For these files, could you please provide the correct and final .csv file? [These tables can be found in this Google folder - Content. Please note that the Excel and .csv files have been provided so that you can see the difference.]

Tables: When the Excel files were converted to .csv, the heading and column formatting was lost. Can you please make any adjustments to the formatting and send the final .csv file(s)? If you are fine with the files as is, let us know. [These tables can be found in this Google folder - Formatting.]

Assets and Metadata: Please review all of the assets in the Media tab. Please confirm that all of the assets you wish to be included are displaying *and* that all metadata for the assets is accurate. [Please note that there is an asset for all of the tables as a zipped file. Please confirm that the metadata is as you wish.]

**Comment by mbakeryo** [comment]
Assets and metadata template reside here: https://drive.google.com/drive/folders/0B-CNui8jTxj4clBvUWR1YnpVODA?usp=sharing

**Comment by mbakeryo** [comment]
For linking the assets to the epub, see ticket #1563 - Release Gabii.

**Comment by mbakeryo** [comment]
Rachel will not have time to give us csv files before the launch on Thursday, March 29th. These may come after, but timing is unknown.
