### ISSUE TITLE
Login redirect from the Gabii monograph page is the UnityLoader.js file

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1538]
After logging in successfully to the dashboard on heliotrope-preview using the Login link in the footer of the Monograph catalog page for Gabii, I am redirected to:

![screen shot 2018-01-31 at 1 21 28 pm](https://user-images.githubusercontent.com/1686111/35639919-b682398c-0689-11e8-8bd3-6f67167ce35e.png)

I should be redirected to the dashboard (or possibly the previous page, I can't remember what it is supposed to be, but it definitely should not be the UnityLoader.js file).

Setting as low priority

**Comment by sethaj** [comment]
It's trying to redirect the newly logged in user to the last url they were at before logging in. Which the app beleives is that .js file.

Need to add exceptions for this file (all .js files probably) here:

https://github.com/mlibrary/heliotrope/blob/master/app/controllers/application_controller.rb#L43

**Comment by mbakeryo** [comment]
Resolved by #729

**Comment by jmcglone** [comment]
Tested, and this is working properly now.
