### ISSUE TITLE
Add multiple-value field to importer

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#154]
**ISSUE**
Import an example of a metadata template with multiple values within the field. e.g. Image, Etching, Engraving

**ACCEPTANCE CRITERIA**
- [ ] When a user uploads a metadata template with a field with multiple values, the importer accepts all values and presents them individually within the UI.

First, look through fields to determine which are multi-value

**Comment by sethaj** [comment]
I think this is essentially done with the csv importer, but there are some instances in the UI where this is not right (keywords?).

**Comment by jgmorse** [comment]
That's what was discussed yesterday: keywords entered in the UI don't split
on the semicolon.

On Wed, Jun 15, 2016 at 10:41 AM, Seth Johnson <notifications@github.com>
wrote:

> I think this is essentially done with the csv importer, but there are some
> instances in the UI where this is not right (keywords?).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlibrary/heliotrope/issues/154#issuecomment-226208430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABoqqTfIY9-S2C_J2OnNzy7IgBjdYMkHks5qMA8OgaJpZM4IHopF>
> .
>



-- 
Jeremy Morse
Director of Publishing Technology
Michigan Publishing
734.615.5739
