### ISSUE TITLE
Receive and review updated WebGL file

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1540]
A new WebGL file from the Gabii team will include updated and improved JS for performance, better visual loading screens for the WebGL file, and tutorials for users.

**Comment by jmcglone** [comment]
Meeting with Gabii Team to discuss new WebGL build, performance improvements, and other details on 02/07/18.

**Comment by mbakeryo** [comment]
Gabii team should deliver by 2/16.

**Comment by mbakeryo** [comment]
Tyler will deliver once he returns - should be around March 12th. We want that week so we can send out to Gabii team for review on 3/16.

**Comment by mbakeryo** [comment]
Would be ideal to get this by 3/26/18.

**Comment by jmcglone** [comment]
Turning out to be much more iterative, with Tyler passing along an updated build and me loading it onto preview for review.

**Comment by mbakeryo** [comment]
Expecting to receive final on 3/28/18.
