### ISSUE TITLE
Workflow to create licenses for subscribers

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1544]
- [ ] As a Gabii subscription manager, I can feed subscriber info (username, institution ID) to a process that will create a license to the Gabii monograph for those subscribers.

**Comment by jgmorse** [comment]
For Gabii launch: This can be a Dumb Process that adds ids to a Dumb Table.
Later, we'll want to be able to feed the data in more seamlessly.

**Comment by gkostin1966** [comment]
Workflow: creating licenses in heliotrope
https://docs.google.com/a/umich.edu/document/d/1lFESeXo4VcTVaQ6qJHGFHLxMQhe3V0Em4IJFC9hISF8/edit?usp=drive_web

**Comment by mbakeryo** [comment]
@jgmorse @gkostin1966  What is the status of this ticket?

**Comment by mbakeryo** [comment]
Blocked by API cards -
