### ISSUE TITLE
Create page for Fulcrum Services

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1545]
As a potential client, I need to find information about what services Fulcrum offers, on the Fulcrum website. As a Fulcrum service owner, I want to direct link potential clients to a page with service information.

- [ ] Once content is received, mockup the services page. Include:
- [ ] Link to Fulcrum Services page in the For Publishers section of about page
- [ ] Link to Fulcrum Services in the footer and mobile menus
- [ ] Include Fulcrum Services logo on services page
- [ ] Page should include three areas of service: Hosted platform, Editorial design/production, Distribution
- [ ] Use icons to illustrate each service area
- [ ] Each area may include a case study to help provide examples of services.
- [ ] Upon approval, create static page that lives at https://fulcrum.org/services
- [ ] After launch, tweet a link to the page and announce services in Newsletter item.

Blocked until content is provided by MPS
As of May 2, 2018, no idea when we'll have this - not for LPF

**Comment by mbakeryo** [comment]
Meeting with MPS is on 2/22

**Comment by jmcglone** [comment]
Copy is at https://docs.google.com/document/d/18QFay9iz-1-QpP3hk3_vkn9wsMzM9f99-dv44HoDWMc/edit?usp=sharing
