### ISSUE TITLE
rake task to clear cache

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1552]
We have a cache (not the Rails.cache) that we store epubs, webgls, etc in. When a user uploads a new version of a file, the cache should be cleared so it can be rebuilt.

The cache code is in here: https://github.com/mlibrary/heliotrope/blob/master/app/services/factory_service.rb

There are already mehods to do this (FactoryService.clear_caches for example).

We should have a rake task to clear the cache of:

- [x] Everything (ie: FactoryService.clear_caches)
- [x] A specific File (base on it's FileSet.id or something)

(While a rake task is great and obvously better than restarting the app we should also integrate this into the app when a new version of a file is uploaded)

- [ ] Write a new ticket to integrate automatic cache clearing into heliotrope where appropriate

**Comment by gkostin1966** [comment]
Rake Task: https://github.com/mlibrary/heliotrope/wiki/Rake-Tasks
