### ISSUE TITLE
Interactive tutorial for Gabii

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1556]
As a user, I would like a guided tutorial on how the components of Gabii (3-D model, text, database) work together. Using the technology identified in #1392 

- [ ] Storyboard a tutorial for the text-side of Gabii that begins on the E-Reader view.
- [ ] Share storyboard with Gabii team
- [ ] Implement interactive tutorial

**Comment by jmcglone** [comment]
Pushed to Spring
