### ISSUE TITLE
Deploy HOB to production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1557]
- [x] Create HEB press in fulcrum (subdomain TBD) (this is in seeds.db but that might be old. Might make sense to do this in the UI)
- [x] import monograph and assets
- [x] Google Analytics id - make sure this is in the Press record
- [x] Due to a code change for citations, gabii needs to have an author (not just the free-text author field). Either add an author, a contributor or an editor (the editor field works fine for citations too). This won't be displayed in the UI.
- [x] Set FeaturedRepresentative epub/mobi

**Comment by mbakeryo** [comment]
We are currently waiting for confirmation as to what the Fulcrum URL will be. It'll be either fulcrum.org/heb or fulcrum.org/humanitiesebook

**Comment by jgmorse** [comment]
Moved a couple acceptance criteria to #1743 since they happen after release.

**Comment by mbakeryo** [comment]
Order of how the release will go:
1. Seth:	code release (remember: auths name for Gabii and ACLS use current Google Analytics ID)
2. Jon: make press
3. Conor: import
4. MBY/Jon: set the representative for EPUB and MOBI
