### ISSUE TITLE
One asset in multiple sections

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#156]
**ACCEPTANCE CRITERIA**
- [ ] Allow for 1 asset to be included in 2 sections when uploaded from the metadata template

**NOTES**
Semicolon is the delimiter for multiple variables, can't be used to titles, section headers.

**Comment by sethaj** [comment]
This ticket includes dealing with the "clone" relationship between assets,  so is a much bigger story, really almost an epic.

- encode clone relationship in predicate

**Comment by conorom** [comment]
Shortly after this ticket was created we decided that another row in the template was preferable to multiple section names in the section field as:
- section names might have semi-colons
- metadata for the reused assed might be slightly different in each place where it is used
