### ISSUE TITLE
QA Gabii on Preview

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1561]
Before moving to production, we should check the following to make sure all is in order:

- [x] EPUB is QA'd and finalized #1559 
- [x] Assets are loaded and displaying correctly on asset pages
- [x] Tables are broken up into separate files
- [x] About page in Vol. 1 monograph page is error free
- [x] Accessibility mode works when reading on E-Reader
- [x] Alert messages work for unsupported browsers and devices
- [x] Test Auth on preview ( #1541 )

...

**Comment by mbakeryo** [comment]
Here are some issues identified on 3/19/18 before sending Preview to the Gabii team: https://docs.google.com/spreadsheets/d/1WOnS2K1s40ewx4P752uHGFIH6dLovayBuyYJcm54fnM/edit#gid=0
