### ISSUE TITLE
Release Gabii

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1563]
Steps and tasks related to the launch of Gabii on production:
- [x] QA #1561
- [x] Create publisher: Gabii Project Reports ('gabii') as a sub-press to Michigan - use existing GA ID
- [x] Create monograph as draft
- [x] Import assets as draft
- [x] Set WebGL, EPUB, Aboutware, Database as representative
- [x] #1593 Assign DOIs: EPUB, EPUB subsections, 3D model, assets - Database has an existing DOI
- [x] Modify EPUB, put links to assets in captions
- [x] Import existing subscribers to Auth
- [x] "Publish" monograph and assets (remove draft mode)
- [x] Setup redirect on DLXS Gabii (https://quod.lib.umich.edu/g/gabii) to point to Fulcrum Gabii
- [x] Release updated homepage/navigation on DLXS

...

**Comment by mbakeryo** [comment]
Assets and metadata template reside here: https://drive.google.com/drive/folders/0B-CNui8jTxj4clBvUWR1YnpVODA?usp=sharing
