### ISSUE TITLE
Preview first row of metadata template import

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#157]
**STORY**
As an editor, when uploading a metadata template through the importer I would like to receive a "preview" notifications that shows me the first row of the spreadsheet that will be upload so that I can confirm that I have not put monograph content in the 2nd row, which will not be displayed in the UI

**Comment by mbakeryo** [comment]
The dev team decided to close this at the Dev Planning Session on June 14, 2016
