### ISSUE TITLE
user whitelist for cosign

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1576]
With the new cosign login, we've realized that the app isn't ready for non-privileged users to be able to log in. They can see links and trigger actions that they shouldn't (see, e.g. #1572 and #1573).

Until we patch all that up, we'll need to whitelist certain cosign users for the production site and, if it's easy to do, perhaps preview as well (it's not behind a VPN and is shared with our partners).

**Comment by gkostin1966** [comment]
Allow login only for users listed in the Users table.
