### ISSUE TITLE
Allow user to merge sections via the UI

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#158]
**BACKGROUND**
Sometimes authors will provide content to two fields of the metadata template that need to be combined. 

**STORY**
As an editor, I would like to be able to merge or rename the sections of the metadata template after import. 

**ACCEPTANCE CRITERIA**
- [ ] As an editor/admin with appropriate rights, I can choose one section and specify a different section to merge it into

**Comment by mbakeryo** [comment]
We're not clear as to what this is anymore, we'll let the issue represent itself if it so chooses.
