### ISSUE TITLE
after release to production task

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1584]
For now, pending the migration to fauxpaas, after a release to produciton, run:

`sudo -u heliotrope-production RAILS_ENV=production bundle exec rake sitemap:refresh` in the current directory.

Then make sure the sitemaps directory is group writeable so the deploy can be deleted later on.

**Comment by gkostin1966** [comment]
[  ] Append the following line to ./config/settings/production.yml
`cosign_logout_url: "https://weblogin.umich.edu/cgi-bin/logout?"`

**Comment by sethaj** [comment]
We don't yet have the cosign stuff enabled for production, A&E is in the process of doing it, so I'm going to leave this open until that's done.

**Comment by sethaj** [comment]
We'll make the cut over sometime on the 12th.

**Comment by sethaj** [comment]
cosign login is enabled in production
