### ISSUE TITLE
Clicking [X] in WebGL panel does not trigger state change

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1586]
When I use the X in the WebGL panel to close the panel and then try to re-open it, it does not open on first click. After a second click, it opens. 

I believe this is because a state change is not being registered when clicking the X button from the WebGL panel.

**Comment by respinos** [comment]
@respinos needs to check whether the problem is the panel widget needing a way to invoke a callback to communicate state back to the reader.

**Comment by jmcglone** [comment]
Resolved by #1633
