### ISSUE TITLE
WebGL display issues when E-Reader is in full screen mode in CSB

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1588]
As a user, if I have the WebGL game open and select full screen mode for the e-reader, the WebGL is oversized and cut-off.

It is possible that the WebGL itself is attempting to go Full-Screen too.

Fix this so that when a user goes fullscreen with the e-reader the game is correctly proportioned to the panel.

This may be related to #1587

**Comment by mbakeryo** [comment]
Blocked by 1587.
