### ISSUE TITLE
Create prompt on metadata template import

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#159]
**STORY**
As an editor, when importing a second metadata template to an existing monograph, I would like to receive a prompt or notification for the following use cases, as needed: 
- [ ] Delete existing assets first
- [ ] Overwrite assets if file exists 
- [ ] Add files even if there are duplicates

**Comment by mbakeryo** [comment]
@jgmorse Based on our conversations as of late about the metadata template and UI entry, do you think that this is still needed? Should we close this and regenerate if necessary once we've established the workflow?

**Comment by mbakeryo** [comment]
No longer relevant.
