### ISSUE TITLE
Fix publication date in the Info widget

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1592]
Display only the publication year.

Currently shows MM/DD/YYYY.
![screen shot 2018-03-01 at 7 02 53 am](https://user-images.githubusercontent.com/17436011/36844104-4e9415b4-1d1f-11e8-80ac-0acce2e5748e.png)

**Comment by respinos** [comment]
See: https://github.com/mlibrary/cozy-sun-bear/issues/139
