### ISSUE TITLE
Add IDs to Sections in Gabii database HTML

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1624]
- [x] Each `<section>` element in the database HTML should have an @ID attribute, so the 3D can link directly to the relevant section of the imageclass UI.

Links in Unity will append the ID to the database entry's DOI, 
e.g. https://doi.org/10.3998/gabii.1.11?#foo
resolves to 
https://quod.lib.umich.edu/g/gabii_1_data/stratigraphic_units/11#foo

**Comment by jgmorse** [comment]
Every <section> in the SU entry has an @id that corresponds to its name as found in the @class attribute:

On SU entries:
```
<section id="basic_description_and_interpretation" class="metadata grouped basic_description_and_interpretation">
<section id="detailed_description" class="metadata grouped detailed_description">
<section id="finds" class="metadata grouped finds">
<section id="special_finds" class="metadata grouped special_finds">
<section id="identification_and_documentation" class="metadata grouped last identification_and_documentation">
```

On Special Finds:
```
<section id="basics" class="metadata grouped basics">
<section id="object_type" class="metadata grouped object_type">
<section id="stratigraphic_units" class="metadata grouped last stratigraphic_units">
```

On Spot Dates:
```
<section id="basics" class="metadata grouped basics">
<section id="date_range" class="metadata grouped date_range">
<section id="stratigraphic_units" class="metadata grouped last stratigraphic_units">
```

If we need @id attributes for sub-sections (e.g. 'Stratigraphic Sequence') they will have to be done one by one in a number of .xsl files; let @jgmorse know if that's needed.

**Comment by jmcglone** [comment]
Gabii team asked for more specific ID attributes -- these have been added.
