### ISSUE TITLE
Create a dev seeds file for development purposes/ingest

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#163]
**STORY**
After the database as been cleared of sample data, as a presenter, I would like to be able to run a simple importer script that will populate the demo site with sample content.

**ACCEPTANCE CRITERIA** 
- [ ] If I run a script, I expect to have a least monograph with one asset attached.

**Comment by shanitajohn** [comment]
Shanita to follow-up, create sample template, confirm with team.

**Comment by mbakeryo** [comment]
We've decided not to do this.
