### ISSUE TITLE
Mobile detection for WebGL is causing Unity JS errors

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1634]
When I load the e-reader from the monograph catalog page or press catalog page, the e-reader does not load and throws a JS error. Upon refresh of the page, the e-reader loads. After playing around with the mobile detection conditionals for WebGL, and eventually completely removing it, I can get this error to go away. There may be something going on with turbolinks and storing the conditionals in the asset pipeline JS (`app/assets/javascript/common/heliotrope_mobile_user.js`) instead of the show page itself.

**Comment by conorom** [comment]
Dang, and I thought I was being clever storing the value where it could be reused by other scripts. I did notice that `removeCurrentHeadProvisionalElements` and `uninstallProgressElement` are both Turbolinks methods. Those the errors you mean?
