### ISSUE TITLE
UnityLoader.js error on loading WebGL

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1646]
When launching the WebGL, the console often logs a `UnityLoader is not defined` error. The game eventually loads,  but as has been suggested, this is probably an error related to our misuse of turbolinks on the EPUB show page, and other show pages where the WebGL is loaded.

![screen shot 2018-03-21 at 10 37 14 am](https://user-images.githubusercontent.com/1686111/37716127-218879b8-2cf4-11e8-9ff2-745d30fce065.png)

**Comment by conorom** [comment]
The most consistent way to trigger this is to click the Gabii "Read" button straight from the publisher/press catalog page.
