### ISSUE TITLE
UX for WebGL failures and slow loading

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1649]
As a user, I'd like help if the WebGL file fails to load on error, or loading freezes for more than 2 minutes (not sure if this time amount is fair). By freeze I mean it does not progress for more than 2 minutes. Can we even check that / is that a common problem?

In the `div` where the game was supposed to load, provide the user with a message that includes:

1. Helpful message about experimental nature of WebGL/3D model:

>Sorry, it looks like [loading the 3D model failed with an error / your browser is having trouble loading the 3D model]. Please check our [compatibility requirements](http://hdl.handle.net/2027/fulcrum.9231782/about). If this problem continues, please submit a [bug report](https://goo.gl/forms/v6uRBVAzoTHEUWuS2) or send an e-mail with your problem to umpress-gabii@umich.edu.

2. A button that on click re-loads the page and 3D model. Text for button:

Try Loading Again

3. A button that on click sets the reader in "accessibility mode". Text for button:

Continue Without 3D Model

How can we detect if an error occurs? What errors should we be looking for? How can we detect if loading has "frozen"? What's an appropriate load time baseline?

**Comment by jmcglone** [comment]
A very rough whiteboard of how this message should be presented in the 3D model panel:

![img_0104](https://user-images.githubusercontent.com/1686111/37851554-be3bb8d4-2eb5-11e8-93cb-5c860a80e781.jpg)

**Comment by jmcglone** [comment]
We decided to delay this to after the release on March 29. There is really no good way to detect failures or freezing loading processes at this point. We also think the work being done with #1654 will help solve a lot of the loading issues.

**Comment by mbakeryo** [comment]
We are not going to do this until we receive feedback from actual users indicate that we need to move forward with.
