### ISSUE TITLE
Maybe use Brotli instead of gzip for WebGL builds

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1651]
Given the fact that we're already running into download speed complaints and now know that older browsers will fall back on Unity's built-in JS decompression anyway, we should discuss switching the Unity build to Brotli compression.

It should result in both smaller unityweb files and faster (or at least as fast) unpacking. Either way it's the lowest-hanging fruit in complaints about start-up time for the WebGL content.

Drawbacks:
1) release build time. One-off and presumably minimal. After that it should be quicker to download and unpack than gzip/deflate
2) what will the version of `mod_deflate` on our servers do with a file marked with `Content-Encoding: br`?

notes:
- The compatibility on Unity's own docs is out of date, showing Safari as not brotli-capable, which it is:
https://caniuse.com/#feat=brotli
https://docs.unity3d.com/2018.1/Documentation/Manual/webgl-browsercompatibility.html
- Performance:
http://blog.catchpoint.com/2017/06/22/compression-making-big-smaller-faster-part-2/
https://www.opencpu.org/posts/brotli-benchmarks/

**Comment by jmcglone** [comment]
@conorom should have a brotli build today...

**Comment by conorom** [comment]
Looking at the the brotli-compressed `.unityweb` files the size reduction is 6.57% when taken together and 5.86% on the largest data file itself (the main cause of startup delays).
I guess the fact that the bulk of the contents are textures (compressed image formats) means that there isn't much benefit to be had here.

Supposedly there will be a slight speed gain in decompressing brotli over deflate but I can't see it being worth the trouble. We should focus on making the download process more communicative and robust instead. Maybe even cache it:
https://forum.unity.com/threads/webgl-settings-data-caching.322559/
