### ISSUE TITLE
WebGL Screen position out of view frustum

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1652]
This extremely prolific console error message _might_ be something we can ignore. It happens when the game is loaded but the gameContainer/canvas is no longer visible.

aside: I don't ever remember seeing it get as far as the alert box (even before UnityLoader's error handler was set to NOP). Then again maybe only errors during loading (UnityLOADER) got to that alert and this is a "runtime" WebGL error.

Having said all that, it seems pretty messy to ignore this, it can spam up the console with 100s of repetitions.

Almost all search hits for the error are from people seeing it while actually editing the "game" project. All seem to hint that the camera is the culprit and solutions are not relevant to us. The best (and weirdly perfectly timed) hit for the problem in our context is this, though the solution involves editing the game file:
https://stackoverflow.com/questions/49335738/hidden-unity-webgl-app-screen-position-out-of-view-frustum

We could ask the guy for the function to put in the Unity code?!

**Comment by conorom** [comment]
I asked the StackOverflow guy to share his workaround. Will see.

**Comment by conorom** [comment]
It's hard to know where to fix this with no experience working on a WebGL project. I may have jumped to the conclusion that this can't be avoided with a hidden div, but apparently the original Gabii on quod never had this issue when hidden (so says @jmcglone). Plus there is someone here saying "you will have same error in the build, as well.", i.e. if you see this error in the WebGL editor preview.
https://forum.unity.com/threads/screen-position-out-of-view-frustum.9918/

**Comment by conorom** [comment]
Ideally this would be fixed somehow on the WebGL side only. Some of the threads listed above indicate this is possible.
Either way it's not something we can fix by ourselves, even with the SO hack. Closing.

**Comment by MuhammadFaizanKhan** [comment]
I am getting the same camera frustumer error when i am disabling the webgl using display:none. ? Do you have solve the problem.? I tried to disable my camera in order to resolve this issue but it didn't work.

**Comment by conorom** [comment]
@MuhammadFaizanKhan Sorry for the delay. We worked with a WebGL developer who was external to the project team, so I cannot definitively tell you what solution was used to fix this. I can tell you that the problem seems to be resolved in our WebGL view now, I'm not seeing the console spamming like before.

I don't think the WebGL developer used the StackOverflow solution at the top of this thread, so I think either an update to the WebGL editor solved it (our file now lists engine version: 2017.3.1f1 fc1d3344e6ea) or else it was one of the mundane fixes listed in the Unity forums. Things like closing and reopening views in the WebGL editor:
https://forum.unity.com/threads/screen-position-out-of-view-frustum.9918/#post-4059724

If that doesn't work then there are more complex solutions around:
https://forum.unity.com/threads/solved-screen-position-out-of-view-frustum.60851
https://answers.unity.com/questions/783730/screen-position-out-of-view-frustum-error-1.html
https://issuetracker.unity3d.com/issues/screen-position-out-of-view-frustum-error-printed-non-stop

Again, sorry I can't be more help. I have no WebGL development experience! Post back for future readers when you figure it out. Good luck!
