### ISSUE TITLE
update keycard in Gemfile.lock

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1653]
There have been some changes to keycard that we'll want so do:

`bundle update keycard` and make a PR

**Comment by gkostin1966** [comment]
https://ilikestuffblog.com/2012/07/01/you-should-update-one-gem-at-a-time-with-bundler-heres-how/

bundle update ––source gemname

**Comment by gkostin1966** [comment]
bundle update

**Comment by gkostin1966** [comment]
rm Gemfile.lock
bundle install

**Comment by gkostin1966** [comment]
bundle update --conservative keycard loofah rails-html-sanitizer
