### ISSUE TITLE
Remove "Switch Language" Dropdown

### ISSUE THREAD

**Issue by moseshll** [mlibrary/heliotrope#1665]
Switching to another language besides English causes localization-related errors. For Gabii, these should be suppressed for now. The dropdown is rendered via `shared/_locale_picker.html.erb`.

- [x] Remove dropdown from `_my_actions.html.erb`
- [x] Remove dropdown from `_institutions.html.erb`

Hyrax seems to think we have seven localizations available. The dropdowns should just be commented out until we have a chance to decide if we need to flesh out some additional locales.

**Comment by jmcglone** [comment]
Resolved by #1666
