### ISSUE TITLE
Harris Matrix errors in Gabii Database

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1679]
- [x] Sometime the lines in the grid aren't drawn completely; see the descender from node 363 here: https://quod.lib.umich.edu/g/gabii_1_data/x-stratigraphic_units/363
- [x] Sometimes nodes are linked when they shouldn't be (and lead to an error when clicked): try 462 here: https://quod.lib.umich.edu/g/gabii_1_data/stratigraphic_units/462

**Comment by respinos** [comment]
@moseshll - the matrix never drew the same as actual gabii, partly because of Bootstrap 2 vs. Bootstrap 3 differences. One strategy would be to rebuild the matrix in something like codepen with Bootstrap 3 and see if that fixes things.

**Comment by respinos** [comment]
The "current" node is always wrong, setting up a classic-style ImageClass link to an attachment.

**Comment by moseshll** [comment]
For reference:
https://gabii.cast.uark.edu/data/browse/stratigraphic_units/1016
vs
https://quod.lib.umich.edu/g/gabii_1_data/stratigraphic_units/1016

**Comment by moseshll** [comment]
Slacked an invite to jgmorse to preview cosmetic changes on test.quod.

**Comment by jgmorse** [comment]
Definite improvement, but for very large matrices, the graph is drawn over the nodes, e.g. http://test.quod.lib.umich.edu/g/gabii_1_data/x-stratigraphic_units/1016

**Comment by jgmorse** [comment]
Looks good! I think this is okay to release.

**Comment by moseshll** [comment]
Released to Production.

**Comment by jgmorse** [comment]
Problems are fixed.  I'll close it.
