### ISSUE TITLE
Create sheet for devs to report hours

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1683]
Create a spreadsheet that devs can easily drop hours into.
To include:

- [ ] Ticket number
- [ ] Dev name
- [ ] Closed date?

We no longer need this:
- [ ] As a dev team member, I need to be able to select a Sprint, then export, from all Issues in that Sprint, the following fields:
- - [ ] blank (for estimated hours)
- - [ ] blank (for actual hours)
- - [ ] Assignee
- - [ ] Issue number
- - [ ] Title
- - [ ] labels (repeating)

- [ ] (Optional) If there is more than one Assignee on the ticket, then the Issue should appear once in the CSV for each Assignee, with all the fields repeated.

**Comment by mbakeryo** [comment]
@jgmorse Should I close this ticket?

**Comment by mbakeryo** [comment]
We're going to close this, as we're reviewing another tool that will give us the ability to track hours in the way that is needed.

**Comment by mbakeryo** [comment]
@jgmorse I changed the ticket title, but kept the original acceptance criteria, just for history's sake. Please take a look at the new acceptance criteria, however, and adjust as is appropriate.

**Comment by mbakeryo** [comment]
@jgmorse Is this more in line with what was discussed last week: https://docs.google.com/spreadsheets/d/1jXBHs8ASQwfwALxAZuNfwN4BaWfImZCPvnXViiHi0u0/edit#gid=1855009352

If not, either let me know how to change, or go ahead and modify as you see fit.

**Comment by mbakeryo** [comment]
A simple sheet to record hours on tickets: https://docs.google.com/spreadsheets/d/1jXBHs8ASQwfwALxAZuNfwN4BaWfImZCPvnXViiHi0u0/edit#gid=1855009352
