### ISSUE TITLE
Cleanup webgl js in epub show.html.erb

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1690]
There's a lot of webgl specific js code in https://github.com/mlibrary/heliotrope/blob/master/app/views/e_pubs/show.html.erb that we should try to organize better.

There's so much of it in once place that it's confusing. And it's all there for an edge case, the webgl, and not for epubs.

I'm not sure exactly how to do this, maybe we can extract it to a .js.erb file and include that somehow. Not sure.

**Comment by conorom** [comment]
It's also hard because there are no automated tests for all the edge cases these things were shoehorned into that file to solve. Weren't we kicking around the idea of more UI tests somehow? Maybe it's not worth it from a time perspective, given how complex the whole CSB app has become.

**Comment by jmcglone** [comment]
After adding support for WebGL, `app/views/e_pubs/show.html.erb` has become unruly. I would suggest:

- [ ] moves lines 6-20 to a partial called `_webgl_scripts.html.erb`
- [ ] the largest chunk of WebGL stuff, lines 90-358 to a partial called `_webgl.html.erb`
- [ ] move lines 429-451 to `_webgl_accessibility.html.erb`
