### ISSUE TITLE
Messaging about Gabii free-trial

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1695]
On monograph and e-reader pages, add a message about Gabii being free through June 2018 as part of our launch of the publication on Fulcrum. Include a link to buy access

**Comment by jmcglone** [comment]
Language and display on monograph catalog page:

![screen shot 2018-04-04 at 1 24 07 pm](https://user-images.githubusercontent.com/1686111/38324132-67ae3382-380d-11e8-9e2f-026a67a917c5.png)

Language and display in e-reader (box will be dismissible when implemented):

![screen shot 2018-04-04 at 1 35 59 pm](https://user-images.githubusercontent.com/1686111/38324173-82daed94-380d-11e8-9a1d-63c4f8368b63.png)

**Comment by jmcglone** [comment]
@mbakeryo @jgmorse thoughts on these mockups and their language?

**Comment by mbakeryo** [comment]
@jmcglone This looks really good! 2 thoughts, that you can probably ignore: 1. I love commas, so, I tend to believe one is needed after "Afterwards," but, again, I'm a comma freak, so... 2. Once the free-trial access is gone, the messaging will disappear, which makes sense. But, I'm wondering, should there be something here that says what kind of access is being purchased (like access to the full publication, which is said in the e-reader)? Or maybe this should be handled with changing the Buy Book to Purchase Access.  Anyway, this is a thought for later...
