### ISSUE TITLE
caching unityweb data file

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1698]
Although our WebGL build is supposed to have Unity's built-in caching (somehow based on build ID) enabled, it's obvious that the large data file is downloading every time. Why is this?

A good explanation for Unity versus browser caching is here (Search for "there are two independent layers of .data caching"):
https://forum.unity.com/threads/webgl-settings-data-caching.322559/

You can go to e.g. `chrome://cache` and see that the `unityweb` files are in there, though the data file is not always among them.
There are also a bunch of IndexedDB entries for Fulcrum.
Either way it's downloading every time.

There could be a bug in the version of Unity editor that built the file (note after `5.6.x` they moved to year/date based versioning starting with `2017.1`):
https://forum.unity.com/threads/data-caching-on-unity-5-6-is-not-working.468305/page-2
https://unity3d.com/get-unity/download/archive

**Comment by jmcglone** [comment]
@conorom Tyler reports that after each build this setting gets un-checked in Unity. It looks like the build he gave us didn't have data caching turned on! We're waiting on yet another build from him with data caching on and we'll see if this makes any difference.

**Comment by conorom** [comment]
@jmcglone That's interesting. So some of what I'm seeing is plain browser caching and the `data.unityweb` file is probably too big for the browser to cache without some shenanigans with some arcane settings, which I guess is why Unity developed the IndexedDB workaround in the first place!
I was wondering why the IndexedDB thing was present with Unity-related field names but no apparent data... hopefully that is why ;-)

**Comment by conorom** [comment]
Hmm. "After each build" does make it sound like he thinks one of the previous ones might have worked, which isn't the case, I don't think. We'll see, I guess.

**Comment by jmcglone** [comment]
Latest build seems to be accessing the cached version correctly
