### ISSUE TITLE
Configure robots.txt per environment

### ISSUE THREAD

**Issue by val99erie** [mlibrary/heliotrope#170]
Since we aren't in production yet, I changed the robots.txt file to prevent web crawlers from indexing our demo server.

Before the production server goes live, we'll need to come up with a way to deploy different robots.txt files to different environments.  For example, for a staging or QA environment, we want to ban robots, but for the live production environment we want to allow them.

ACCEPTANCE CRITERIA:
- [ ] The deploy scripts have some way to configure the robots.txt file so that different environments can use different settings.

**Comment by sethaj** [comment]
MLibrary doesn't really need multiple robots.txt files based on environments, just a production one. So just make a single static robots.txt and commit it.

**Comment by jmcglone** [comment]
Since the testing/demo will be public, we need to have a robots.txt files for production that allows indexers and a robots.txt file for test that denies indexers.
