### ISSUE TITLE
3D model links to text reference - handles need to be registered

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1700]
Clicking on the permalink in the text reference link goes to an Error - Not Found page

How to recreate this:

Go to the 3D model tab from the monograph page.

In the 3D model, select a trowel and click.

In the SU popup, select "go to reference in text."

A popup will tell you: "To view a textual reference to this stratigraphic unit in the publication, please use the following permalink (will open in new window)" - and then the permalink is listed

An example, SU 1257
Permalink is listed as http://hdl.handle.net/2027/fulcrum.9231783/par78

Clicking on that link goes to an Error - Not Found page
![screen shot 2018-03-30 at 6 27 51 am](https://user-images.githubusercontent.com/17436011/38137001-0f147a9a-33f0-11e8-9824-62f2f9ffb086.png)
![screen shot 2018-03-30 at 8 01 41 am](https://user-images.githubusercontent.com/17436011/38137096-a0509dea-33f0-11e8-8c8d-b79c53fc9d5a.png)

**Comment by jgmorse** [comment]
They were in the spreadsheet linked in #1593 but I didn't see that tab.  Working on it....

**Comment by jgmorse** [comment]
Handles created.  Links work now.
