### ISSUE TITLE
Add Gabii to Fulcrum homepage

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1704]
Add to the home page:

- [x] cover of Gabii - located here: https://drive.google.com/file/d/10i3_rCYX49BYiseG_bi7uMX_WEkt7xSF/view?usp=sharing
- [x] short description of the project and how Fulcrum is being used (or added to the experience of it....) Use this:

Since 2009 the Gabii Project, an international archaeological initiative led by Nicola Terrenato and the University of Michigan, has been investigating the ancient Latin town of Gabii, which was both a neighbor of, and a rival to, Rome in the first millennium BCE. The trajectory of Gabii, from an Iron Age settlement to a flourishing mid-Republican town to an Imperial agglomeration widely thought to be in decline, provides a new perspective on the dynamics of settlement in central Italy. A Mid-Republican House from Gabii focuses on the construction, inhabitation, and repurposing of a private home at Gabii, built in the mid-Republican period. Published in digital form as a website backed up by a detailed database, the publication provides a synthesis of excavation results linked to the relevant spatial, descriptive, and quantitative data. Fulcrum brings together the database, narrative, and interactive 3D model of the reconstructed ancient site to give the user a seamless reading experience, presenting the narrative and 3D model side by side and including comprehensive linking throughout all components enabling the reader to move through the project in a number of ways.

- [x] link to the monograph page on Fulcrum (links on the title, cover image and a View Project button) - http://hdl.handle.net/2027/fulcrum.n009w229r
- [x] reverse-order the projects and put Gabii and NYU first

**Comment by mbakeryo** [comment]
Suggested short description:

Since 2009 the Gabii Project, an international archaeological initiative led by Nicola Terrenato and the University of Michigan, has been investigating the ancient Latin town of Gabii, which was both a neighbor of, and a rival to, Rome in the first millennium BCE. The trajectory of Gabii, from an Iron Age settlement to a flourishing mid-Republican town to an Imperial agglomeration widely thought to be in decline, provides a new perspective on the dynamics of settlement in central Italy. A Mid-Republican House from Gabii  focuses on the construction, inhabitation, and repurposing of a private home at Gabii, built in the mid-Republican period. Published in digital form as a website backed up by a detailed database, the publication provides a synthesis of excavation results linked to the relevant spatial, descriptive, and quantitative data. Fulcrum brings together the database, narrative, and interactive 3D model to give the user a seamless reading experience, presenting the narrative and 3D model side by side and including comprehensive linking throughout all components to enable the reader to work through the project in a number of ways.

**Comment by mbakeryo** [comment]
@jgmorse @jmcglone Is this brief summary for the Fulcrum homepage ok? I can send to marketing for their ok. Let me know. Also, does it need to be on Fulcrum in time for Charles' e-blast (which is when?)? (Fwiw, I'm guessing he's sending people directly to the project, not the Fulcrum homepage, but it'd still be good to have this up probably.)

**Comment by jgmorse** [comment]
Looks good to me.

**Comment by mbakeryo** [comment]
Awaiting ok from Mary/marketing.

**Comment by mbakeryo** [comment]
Updated the summary above with the changes suggested by Mary and Ellen.
