### ISSUE TITLE
Discuss/document handles/DOIs/deletions/moves/redirects

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1717]
Some notes from working on #1696 

1) the HandleService takes values in the manually-entered `hdl` field to be NOIDs (and not a full URL), so it prepends our handle provider's address (and our base path) to anything in this field for use as the `citable_link` in the display. This assumption probably arose from an action that an early version of the importer was taking, as almost half of assets on production have a NOID in this field (up to the original Canoes monograph, looks like, before the extra FileSets were added to it).
2) my assumption that the DOI field wouldn't be needed when doing the "add a handle to a Monograph" work (#1460), which then used `hdl` instead. I even had a comment in there about how a partner-supplied DOI wasn't likely for monographs. Not realizing that this was actually going to happen right away with Gabii, leading to #1696

I think we should eventually revisit/discuss/document the way we're using these fields and the auto-generated-from-actual-NOID handle. Or how we think they might be used in different scenarios.

point 1) above touches on:
- you need the `hdl` field of an object to be the NOID of another. Why? Something was deleted, maybe, and replaced by this object. You want to retain a single, canonical, citable link for this thing and show that, with its "old" NOID, in the UI
- right now we've taken the road of creating handles at `handles.net` for all entities in the system, but I guess a replacement object for a deleted one would be an exception, lest it be used somehow and break the canonicalness of the citable link?
- Making the old `handle.net` value continue to work requires either editing the `handle.net` handle anyway (to point to the replacement item instead) or using the `redirect_to` field on the old item, without deleting it (possibly removing it from its parent or just from the catalog results)
- Fundamentally we need to decide if never needing to edit a preexisting `handle.net` value is the desirable workflow. Then a combination of the `hdl` field (what other use does it have anyway if we always use `handle.net` as the provider?) and the `redirect_to` fields would be the way to go
- should we delete the current values stored in objects `hdl` fields in production

**Comment by sethaj** [comment]
See 1775

**Comment by conorom** [comment]
There has been some cleanup around handles since this was written (1775 etc). So closing. See also https://tools.lib.umich.edu/jira/browse/HELIO-1717

**Comment by conorom** [comment]
There has been some cleanup around handles since this was written (1775 etc). So closing. See also https://tools.lib.umich.edu/jira/browse/HELIO-1717
