### ISSUE TITLE
Refactor EPUB show page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1718]
After adding support for WebGL, `app/views/e_pubs/show.html.erb` has become unruly. I would suggest:

- [ ] moves lines 6-20 to a partial called `_webgl_scripts.html.erb`
- [ ] the largest chunk of WebGL stuff, lines 90-358 to a partial called `_webgl.html.erb`
- [ ] move lines 429-451 to `_webgl_accessibility.html.erb`

**Comment by conorom** [comment]
same as #1690, or a good start? ;-)

**Comment by jmcglone** [comment]
Indeed! A dup of #1690
