### ISSUE TITLE
File manager changes Monograph visibility

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1725]
Steps to reproduce:
- Click '+' > 'New Monograph'
- select, say, two small image files and enter minimum required metadata
- select public visibility and check the Deposit Agreement thing
- Save
- give a couple minutes for Resque to finish
- go to `concern/monographs/999999999/file_manager`
- swap the order of the files around and click 'Save'

You get the `/concern/permissions/999999999/confirm_access` page, asking if you want to change the permissions ("Apply changes to contents?" because "You have changed the access level on work "Monograph Title"). Obviously this doesn't make sense. 

- click "No. I'll update it manually"
 
The monograph will be set to "draft" visibility.

Presumably the `file_manager` is not interfacing with the actor stack correctly. By the time you see the `confirm_access` page, it has decided the Monograph visibility is changing (maybe private/draft is default)

The FileSets will still be public/open, but presumably that's only because of the choice made on the `confirm_access` page.

**Comment by conorom** [comment]
Given that we saw this happen with Gabii on production, you would presume a previously-imported monograph will see the problem.

**Comment by moseshll** [comment]
The permissions do appear to be changing: the publisher information is dropped after the update. Example permission (one of several) below -- note loss of `nyupress`. Example from debugging `after_update_response` in `works_controller_behavior.rb`:

Before: `<Hydra::AccessControls::Permission id: 8703ced3-72ae-4b8e-a739-dabe1a3c3dec/33/e0/ea/5f/33e0ea5f-208d-4f45-9d41-4a5ba37cde74 agent: "http://projecthydra.org/ns/auth/group#nyupress_editor" mode: "http://www.w3.org/ns/auth/acl#Write" access_to: "fj2362114">`

After:
`<Hydra::AccessControls::Permission id: 8703ced3-72ae-4b8e-a739-dabe1a3c3dec/3d/bf/c8/6e/3dbfc86e-13b0-4584-a454-7d0d8a2d4477 agent: "http://projecthydra.org/ns/auth/group#_editor" mode: "http://www.w3.org/ns/auth/acl#Write" access_to: "fj2362114">`

**Comment by moseshll** [comment]
Time spent: 5h.

**Comment by conorom** [comment]
This was closed here:
https://github.com/mlibrary/heliotrope/commit/9a1aa170dcde1e5ca0fc7ab3612c2e74d5f05796
