### ISSUE TITLE
Determine how to improve title/sections in CSB

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1730]
Feedback regarding HOB:

In CSB, the current section displays after the title, separated by a •. If the title is long, it often gets truncated and isn’t all that obvious. Can it be made more obvious?

Discuss possibilities for improving usability:

- [ ] Decrease the font size of the title/sections
- [ ] Redesign this section
- [ ] Add ellipsis if the section is cut-off

Need to discuss with Jason

Not needed for April launch, but try to do between now and summer.

**Comment by sethaj** [comment]
See 1676. It's starting to look like we won't be able to support chapter/section titles at all due to the what is allowable in epub3 tocs and what epubjs does . In the words of one developer, the outlook is "grim".
