### ISSUE TITLE
HOB Post-deploy clean-up

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1743]
- [x] Modify handles for HEBs to fulcrum URL
- [x] Register handles for Lake Erie Fisherman assets
- [x] Send Fulcrum .epub/.mobi download URLs to Chris, so he can update links on their HOB info page [http://www.humanitiesebook.org/the-collection/humanities-open-book/]

Blocked by #1557

**Comment by conorom** [comment]
All assets attached to the 13 monographs now have the usual handles.

**Comment by mbakeryo** [comment]
@jgmorse Do you know what the status of this ticket is?

**Comment by jgmorse** [comment]
@conorom Can you get me the list of download links for the epub and mobi files for each HOB title? Then I'll pass those to ACLS staff.

The I will confirm with them that they actually want those redirects set up.

**Comment by conorom** [comment]
@jgmorse Sent you a link to a Google Sheet

**Comment by jgmorse** [comment]
URLs sent to Chris at HEB. Finding out if they want the HOB redirects now or as part of final migration.

**Comment by jgmorse** [comment]
HEB has indicated redirects can happen as part of final migration, so closing.
