### ISSUE TITLE
Press parameter in caps breaks monograph search

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1744]
Entering a URL like `/NYUPRESS` seems to not return any monographs, at least for some presses/publishers. Probably this search term should be forced to lowercase in the PressSearchBuilder before sending the query to Solr.

**Comment by sethaj** [comment]
Maybe just change this:

https://github.com/mlibrary/heliotrope/blob/master/app/models/press_search_builder.rb#L10

`solr_parameters[:fq] << "{!terms f=press_sim}#{all_presses.join(',')}"`

to this:

`solr_parameters[:fq] << "{!terms f=press_sim}#{all_presses.map(&:downcase).join(',')}"`

Might work...
