### ISSUE TITLE
Duplicate epub search results

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1746]
Search terms are giving duplicate search result "snippets". Searching nyupress for "star wars" gives duplicate results.

This: https://github.com/mlibrary/heliotrope/blob/master/lib/e_pub/search.rb#L39

Is in the wrong place. Probably should strip out duplicate snippets right before sending the data, maybe around here: https://github.com/mlibrary/heliotrope/blob/master/lib/e_pub/search.rb#L80

**Comment by jmcglone** [comment]
Resolved by PR #1822
