### ISSUE TITLE
Add a link back to publisher page from logo on E-Reader

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1748]
As a user, when I'm reading an EPUB, I want an easy way to return to the Publisher's page. 

Make the logo on the E-Reader a link that goes to the Publisher's page.

This is based on feedback from HEB.

**Comment by conorom** [comment]
@jmcglone Going to open a PR that creates a linking image with role and alt set as shown here:
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/link/link.html

...where the alt lets you know where the link's going to take you (not what the image is).
