### ISSUE TITLE
Change loading icon for epub

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1750]
The current (honeycomb) icon creates problems for people with trypophobia.

Find a new icon that doesn't have holes or patterns.

**Comment by jmcglone** [comment]
Here's a start at a Loading icon that uses the Fulcrum logo:

https://codepen.io/jwmcglone/pen/BxyMqB

**Comment by jmcglone** [comment]
Resolved by PR #1825
