### ISSUE TITLE
Add zoom/pan functionality to image viewer

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#179]
**STORY**
As a general user, when I click on an image asset I would like to be able to zoom in and zoom out of the image, as well as pan left, right, up and down (and controls are keyboard accessible).

**REFERENCE**
Michigan would like the same functionality used here: 

http://wustl.curationexperts.com/concern/images/zw12z561q

**Comment by mbakeryo** [comment]
Use Leaflet. Can we have Roger do this? What is the time commitment?

**Comment by jmcglone** [comment]
Use DCE's RIIIF gem? https://github.com/curationexperts/riiif

**Comment by jmcglone** [comment]
We will need to regularly clear out the cache so we don't run out of disk space https://github.com/loris-imageserver/loris/blob/607567b921404a15a2111fbd7123604f4fdec087/bin/loris-cache_clean.sh

**Comment by sethaj** [comment]
I've broken a couple of stories out of this ticket:

#296 is for accessibility in leaflett
#297 is for clearing out the IIIF generated images cache in produciton
