### ISSUE TITLE
Accessing a monograph or section that does not exist should not give a something went wrong message

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#180]
**ISSUE**
When I try to access a monograph or section that has been deleted, I get a "We're sorry, but something went wrong."

I get the same message when I try to access a non-existent monograph or section like http://press.curationexperts.com/concern/monographs/nothere or http://press.curationexperts.com/concern/sections/Im_not_here

**ACCEPTANCE**
- [x] Invalid section/monograph references give a unauthorized response.

**Comment by val99erie** [comment]
This problem should be fixed by upgrading the curation_conerns gem.  I confirmed that the error happens in version 0.12.0 of curation_concerns, but it is fixed on the master branch.

**Comment by acozine** [comment]
After upgrading to curation_concerns 0.14.x, missing monographs return the error message "Unauthorized"; missing sections still return the "We're sorry something went wrong" error message.

**Comment by gkostin1966** [comment]
CurationConcerns responds with "Unauthorized" for non-existent and tombstone objects.

**Comment by mark-dce** [comment]
That's probably the right default behavior and probably got updated from earlier versions of curation_concerns that just threw a stack dump. 

From a general security standpoint, when someone is trying to scan your repository to identify the existence of private material they shouldn't have access to, the default behavior should be to provide the same response for 1) IDs that never existed 2) IDs that exist, but the current user doesn't have access to, and 3) IDs that have been tombstoned.  If you provide differentiated responses for each, that would allow someone to generate random IDs and know that they had found restricted content if they got a different response for situation 2 than they get for 1 & 3.  This is the default behavior you'd want in lower_level gems; if this specific attack isn't a concern, then it would be fine to have differentiated response codes.

My initial ticket was that there was a stack dump happening on an earlier version of curation_concerns.  If folks are OK with the "Unauthorized" response and the user still has a usable search UI, I would think it's fine to close this ticket.
