### ISSUE TITLE
Add "Edit" button to monographs for platform and press admin

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#181]
**STORY**
As a platform admin, if I visit the show page for a monograph, I should see the buttons to Manage the Monograph: Edit this Monograph, Attach a File, Organize Sections, Delete this Monograph and Publish this Monograph

**ACCEPTANCE** 
- [x] These buttons appear on the page for a platform admin regardless of who created the monograph originally.

- [x] These buttons appear on the page for a press admin regardless of who created the monograph originally.

**Comment by sethaj** [comment]
Also Presss admin (not only Platform Admin)
