### ISSUE TITLE
Table of Contents data mismatch

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1811]
This is a similar problem to #1805, where data pulled directly from the EPUB content won't match (and, in the long term, would be impossible to keep in sync with) data stored in Fedora.
For EPUB monographs, on the monograph catalog page we show a bunch of attributes on top and the default TOC tab below can have the same information but it's from a different source.

Already we see TOC items such as the EPUB's Copyright section with values that differ from the attributes shown above: DOI, year etc. For HEB, we're going to pull in a specific copyright holder value for Monographs and display it with the Monograph catalog attributes. This will often differ from the value in the EPUB, e.g. when the copyright has reverted back to the author after a period of time etc.

Here is one solution (quoting @jmcglone)
> Improve the EPUB TOC display on that page by having that bit of code that unpacks the EPUB contents package up all the EPUB's parts before the first chapter and call it "Front Matter", linking to the first section (in most cases a Cover). So: Cover, Title page, Copyright, Dedication, Contents, all that stuff that is really not of interest to a user on this page (probably) is collapsed into a single section. Sounds tricky, but I think if we write our spec to clearly identify what the Front Matter parts are of an EPUB, this wouldn't be hard at all.

**Comment by mbakeryo** [comment]
Will wait for feedback from MPS.
