### ISSUE TITLE
Review predicates prior to production launch

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#193]
ACCEPTANCE CRITERIA
- [x]  Document all RDF predicates for each type of Work or Fileset or Monograph
- [x]  Share document with Matt Carruthers
- [x] Ask Matt if he ever reviewed predicated for UMRDR, and how we compare

NOT a blocker for Beta release.

Use the current predicate mappings to keep development momentum, but it would be worth doing a quick cross-check with other team 4-6 weeks out from the production data ingest.

Provide predicate mappings to other UMich Hydra Teams (and possibly circulate with Hydra Metadata Working Group) for feedback and make any potential changes to achieve better alignment with other systems.

Schedule sometime shortly before final (re)ingest of files and metadata for production bets.

**Comment by sethaj** [comment]
Jon says we could talk to Matt Carrurthers (sp?) metadata librarian to get his input on this.

**Comment by jmcglone** [comment]
Living google doc: https://docs.google.com/spreadsheets/d/1Xzod0SL-Dev1Bh5TklU0OuvSsQhErfG_huDP3dpLcPo/edit#gid=0

**Comment by jmcglone** [comment]
Wiki page: https://github.com/mlibrary/heliotrope/wiki/Metadata-Fields

**Comment by jmcglone** [comment]
Matt has agreed to take a look at our metadata fields and RDF predicates.
