### ISSUE TITLE
Index normalized dates

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#200]
**STORY**
As a user, I would like to be able to facet or sort by dates, so I can find assets based on relevant dates.

**DETAILS**
Input fields for dates are not guaranteed to be normalized by the user inputting them (author for metadata templates, editor for UI based input).  So, the system needs to attempt to parse any input dates and normalize them to some standard.  Ruby provides nice support for [ISO-8601 format date-time values](http://ruby-doc.org/stdlib-2.1.0/libdoc/time/rdoc/Time.html#method-i-xmlschema).  So, we probably want to index & store a parsed version of the date that can be used for faceting, searching, and sorting.  It's generally cheapest to do this a single time on ingest or edit of metadata than trying to parse on-the-fly when faceting or sorting.

**ACCEPTANCE**
- [ ] The original user-supplied date is retained as an unmodified string
- [ ] The system saves a parsed version of the date (when possible) in ISO-8601 format
- [ ] Unparseable date strings do not get indexed into the ISO-8601 date index (or get index as nil)

**Comment by sethaj** [comment]
Add the sort date to the Assets (it's already in the metadata template)
