### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#201]
**STORY**
As a press platform user (author, editor, admin), I'd like a place to go to find relevant information for my role, so that I don't have to search all over the UI for links

**DETAILS**
For the first pass, the dashboard page will just be  a blank landing point for all users.  We'll add content to the dashboard as individual features like "show my uploaded content" or "show users I administer" are implemented.  Some features will only display for authorized users.

See http://mlibrary.github.io/elderberry/admin/index.html# for a potential layout for the page.

**ACCEPTANCE**
- [x] There is a "Dashboard" link under the user menu
- [x] Only authenticated users have access to a "dashboard"
- [x] Non authenticated users will be redirected to the login/registration page.
- [x] The page displays the heading "Dashboard" (for now, we'll be adding content as we execute other feature stories)

**Comment by sethaj** [comment]
Some of this might be covered by the CC "admin dashboard", or we could use that as a base for adding more features.

https://github.com/projecthydra/curation_concerns/wiki/Admin-Menu-for-apps-based-on-Curation-Concerns

**Comment by jmcglone** [comment]
Address this in a few months, especially with what we get from Hyrax
