### ISSUE TITLE
Allow the same asset (file) to be attached to two different sections via the importer (*interrelate*)

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#202]
**STORY**
Initial file upload (CSV importer):
As an author or editor, I would like a means to reuse the same asset within multiple sections of a monograph, so that I don't have to maintain multiple copies of the same file and associated metadata.

**ACCEPTANCE CRITERIA**
- [ ] When the user uploads a file, the CSV template has a way for them to select zero or more sections (within the same monograph) to attach the file to.
- [ ] An asset must belong to at least one monograph or section.
- [ ] When I view the imported asset from a specific section, I should get an indication of the other sections the asset is included in.  (e.g. Links to the related assets) - see the wireframe http://mlibrary.github.io/elderberry/press/book/item/video.html
- [ ] After the asset is imported, the asset appears in the file list for all sections it belongs to (on the section show page).

**Comment by mark-dce** [comment]
Related tickets for context
#202 Attach the same file to multiple sections in a template (via importer)
#203 Attach the same file to multiple sections from the UI
#204 Edit metadata for a file that's attached to multiple sections
#205 Delete a file that's attached to multiple sections

**Comment by conorom** [comment]
This ticket includes dealing with the "clone" relationship between assets, so is a much bigger story, really almost an epic.

encode clone relationship in predicate

**Comment by mbakeryo** [comment]
760 should be done first

**Comment by conorom** [comment]
Now that a FileSet's section(s) are simply stored as a multi-valued field (section_title) there is no issue with adding additional section relationships in the importer. Type the section names in the cell, separated by a colon, no "clone" relationship exists, there is nothing complicated in the data model RE: sections.
