### ISSUE TITLE
Allow the same asset (file) to be attached to two different sections via the browser UI

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#203]
**STORY**
As an editor, I would like a means to reuse the same asset within multiple sections of a monograph, so that I don't have to maintain multiple copies of the same file and associated metadata.

**ACCEPTANCE**
- [ ] After the user attaches a file to a section or monograph, the UI provides a way to clone the file and its associated metadata to a new section.
- [ ] After I clone the asset, if I visit the section page that I that I copied the asset to, I should see the asset in the file list for that section.  (And the asset still appears in the file list for the section that it originally belonged to)

**Comment by val99erie** [comment]
As discussed at the mid-sprint meeting on 5/3/2016, this story won't be high priority for the near future.

**Comment by mark-dce** [comment]
Related tickets for context
#202 Attach the same file to multiple sections in a template (via importer)
#203 Attach the same file to multiple sections from the UI
#204 Edit metadata for a file that's attached to multiple sections
#205 Delete a file that's attached to multiple sections

**Comment by conorom** [comment]
Now that a FileSet's section(s) are simply stored as a multi-valued field (`section_title`) there is no issue with adding additional section relationships in the browser. Type the section name in the box. Eventually a drop-down would be nice to prevent section title typos. But no "clone" relationship exists, there is nothing complicated in the data model RE: sections.
