### ISSUE TITLE
Handle missing-press errors gracefully

### ISSUE THREAD

**Issue by acozine** [mlibrary/heliotrope#207]
## STORY:

As user, when I hit a URL that doesn't exist, I shouldn't think the site is broken. We're currently returning 500 errors for presses that doesn't exist (press.curationexperts.com/michigan-state) and for the resque admin pane (press.curationexperts.com/resque) if the user is non-privileged.
### CURRENT BEHAVIOR:

User gets a 500 error (We're sorry, something went wrong). 
### DESIRED BEHAVIOR:

User gets a flash message (The press "michigan-state" doesn't exist) and gets redirected to the home page.

**Comment by acozine** [comment]
Related to #197.

**Comment by val99erie** [comment]
This can probably be fixed here, by adding a check for existence of the press before trying to load it:
https://github.com/curationexperts/heliotrope/blob/master/app/controllers/press_catalog_controller.rb#L22

**Comment by jmcglone** [comment]
The only case this could be a problem is when a user types in the press URL which is printed in the book front matter. It would be good to test this during Winter 2017 usability testing (#719). 

An option could be to redirect a user to a page that lists all the presses if they type in a press URL that does not exist.

**Comment by gkostin1966** [comment]
Implemented redirect_to(presses_path) option as recommended by @jmcglone.
