### ISSUE TITLE
Deleting a section within a monograph, resolves to catalog page

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#215]
**STORY**
As a user, when I delete a section within a monograph I would like to remain within the monograph I was editing when the page reloads. 

**CURRENT BEHAVIOR**
Currently, when the section is deleted I am taken back to the main catalog page, where I see the confirmation of deletion message.

**ACCEPTANCE**
- [ ] When I click on the button to delete a section within a monograph, the correct section is deleted, I see a confirmation message, the monograph detail page loads. 
- [ ] When I click on the button to delete a section within a monograph, the correct section is deleted, I see a confirmation message, the main catalog page does not load.

**Comment by mbakeryo** [comment]
No longer an issue, as we don't have sections.
