### ISSUE TITLE
When I try to create a file asset without choosing a file, I get JSON instead of a friendly error

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#222]
**STEPS TO REPRODUCE**
on press.curationexperts.com
1. Log-in as a user with privileges to create an monograph
2. Create a new monograph with no files attached
3. Click on the "Add file" button (instead of the select files button)
4. Give the new "file" a title
5. Click save

**Expected results**
I get an error asking me to please choose a file

**Actual results**
I get this JSON
```
{"code":400,"message":"Error! No file to save","description":"Unable to process your request.  See errors for more info."}
```

**Comment by sethaj** [comment]
This behavior is part of curation concerns. We should wait for CC 1.0 to come out and see if it's changed or if they keep it. 

If it stays in CC, maybe one possible way to override it could be something like:

In ```controllers/curation_concerns/file_sets_controller.rb```

```
def create
	unless params.key?(:file_set) && params.fetch(:file_set).key?(:files)
		redirect_to :back, :flash => { :error => "You must attach a file!" }
	else
		super
	end
end
```

**Comment by gkostin1966** [comment]
I went through the steps to reproduce the issue using the current version of the software.  The current behavior is to return to the "Describe Your Monograph" form and display the "flash" message (I believe that is what they are called): "Wait don't go! There was a problem with you submission. Please review the errors below:".  The errors below have the publisher select box highlighted in red.  After selecting a publisher and resubmitting the form the Monograph is created with no file attached.  I am closing this issue assuming the current behavior is correct.

**Comment by gkostin1966** [comment]
Oops, misread the issue, the problem still exist for attachments to monographs, reopening issue.

**Comment by gkostin1966** [comment]
Seth was right, there is problem in Curation Concerns.  I overrode the FileSetsController create method as was suggested and placed a TODO comment to fix CurationConcerns.
