### ISSUE TITLE
Nicer UI for selecting sub-brands (Monograph edit form)

### ISSUE THREAD

**Issue by val99erie** [mlibrary/heliotrope#224]
On the form for editing/creating a monograph, there is a multi-select tool for selecting sub-brands that the monograph should belong to.  There are some problems with that field:
- When more than one sub-brand is selected, it's easy to accidentally un-select sub-brands that were previously selected, so the user might unintentionally remove sub-brands from the monograph.
- The sub-brands in the drop-down are currently scoped to the press, but if you select a different press, the sub-brand choices don't update for the new press.

ACCEPTANCE CRITERIA:
- [ ] On the monograph edit form, there is a user-friendly way to select (one, several or none) sub-brands.  It's easy to add or remove sub-brands without accidentally losing data.
- [ ] On the monograph edit form, if I select a different press than what was previously selected, the choices for the sub-brands should dynamically update to be the sub-brands for only that press.

**Comment by mbakeryo** [comment]
Per Jeremy, We may need something like it for series in HEB, so Aug 2018. Need to define requirements.

**Comment by sethaj** [comment]
Instead of using SubBrands, we've decided that Presses can have a parent/child relationship so we no longer need to complete this story.
