### ISSUE TITLE
Update to Curation Concerns 14

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#230]

**Comment by mark-dce** [comment]
Depending on how far along you are in the process, you might want to try the 1.0 Beta:
https://rubygems.org/gems/curation_concerns/versions/1.0.0.beta4

I'm sure folks would be happy to have feedback.  It should be very similar to 0.14.0 but with lots of small bug fixes and enhancements (I don't thing there are any major feature changes between 0.14.0 and 1.0.0.beta4, but you could give a holler on the software-development channel on the Hydra slack and see if anyone has any cautionary words to offer.)

**Comment by mark-dce** [comment]
Actually - by the time Seth is back, there may be a release candidate (or even a release version), so just check the most recent version listed on rubygems.org:
https://rubygems.org/gems/curation_concerns

**Comment by mark-dce** [comment]
https://github.com/projecthydra/curation_concerns/compare/v0.14.0...v1.0.0.beta4
