### ISSUE TITLE
What should the default setting for a File's Creator be?

### ISSUE THREAD

**Issue by acozine** [mlibrary/heliotrope#233]
Related to #188. 

As a platform admin, if I create a Monograph and upload a file as I create the Monograph, the Creator on the file I upload is set to my email address. I can edit the file's metadata and change the Creator. If I upload a file using the colored buttons (Select Files . . . Start Upload), I get the same behavior - the Creator defaults to my email address, I can edit it later. If I use the Attach a File button and I don't enter a Creator, the field defaults to nil.

What should the default Creator for a file be? Should it be nil? Should it default to the Creator of the Monograph?

**Comment by sethaj** [comment]
Blocked until #155 is done.

**Comment by sethaj** [comment]
A consensus of "default to nil" for FileSets was talked about. I think that's what we want here.

**Comment by mbakeryo** [comment]
Closing until this becomes an issue.
