### ISSUE TITLE
Update Capistrano to point to mlibrary url

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#238]
Update the repo pointer here: https://github.com/mlibrary/heliotrope/blob/master/config/deploy.rb#L5

**Comment by mark-dce** [comment]
You may also want to update the local pointers for git remotes on your development machines:
```
git remote -v
```
Then google how to update the link.

**Comment by jmcglone** [comment]
After updating the deploy scripts we should test that the deploy to UM servers is still successful

**Comment by jmcglone** [comment]
See https://help.github.com/articles/changing-a-remote-s-url/ for changing the remote URL
