### ISSUE TITLE
Review what FITS gives us for technical metadata

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#243]
We'd like to make sure that the technical metadata derived by FITS and saved in fedora is going to be sufficient for our long term purposes. Are we saving enough technical information about objects? Do we need more? In Elderberry there's a technical metadata section that will display this info. What can be listed there for different kinds of objects/media?

*\* Acceptance Criteria **
- [x] Find out what investigation Lance / UMRDR have already done on this topic.
- [x] Find and report on what technical metadata is derived from different kinds of objects. Show whether or not this metadata is in solr (so easily displayed) or in fedora (or captured, but not displayed).
- [ ] Get Lance's sign-off that technical metadata capture is sufficient.

**Comment by sethaj** [comment]
I've looked at mp3, mp4, pdf and png. Generally (what I consider) the technical metadata that's indexed in solr for a FileSet (Asset) for heliotrope is fairly limited. So there won't, by default, be a whole lot to show in elderberry


**mp3 in solr technical metadata**
```
"file_format_tesim": [
	"mpeg (MPEG 1/2 Audio Layer 3)"
],
"file_size_is": 3327538,
"mime_type_ssi": "audio/mpeg",
```

**mp4 in solr technical metadata**
```
"file_format_tesim": [
          "mp4 (MPEG-4, ISO Media, MP4 v2 [ISO 14496-14])"
        ],
"file_size_is": 1150969,
"mime_type_ssi": "video/mp4",
```

**pdf in solr technical metadata**
```
"file_format_tesim": [
	"pdf (Portable Document Format)"
],
"file_size_is": 854195,
"mime_type_ssi": "application/pdf",
```

**png in solr technical metadata**
```
"file_format_tesim": [
	"png (Portable Network Graphics)"
],
"file_size_is": 85783,
"height_is": 423,
"width_is": 1257,
"mime_type_ssi": "image/png",
```

But there's more available information saved in Fedora, so we could index some of this into solr to make it available in the views if we want.

**mp3 in fedora technical metadata**
```
ebucore: fileSize
	3327538
ebucore: filename
	My mp3 Filename.mp3
ebucore: hasMimeType
	audio/mpeg
ebucore: sampleRate
	44100
ns010: exifVersion
	10.00
ns011: channels
	2
ns011: duration
	0:2:18:639
premis: hasFormatName
	MPEG 1/2 Audio Layer 3
```

**mp4 in fedora technical metadata**
```
ebucore: fileSize
	1150969
ebucore: filename
	Screencast 2016-04-01 14:03:34.mp4
ebucore: hasMimeType
	video/mp4
ns011: duration
	17946
premis: hasFormatName
	ISO Media, MP4 v2 [ISO 14496-14]
	MPEG-4
```

**pdf in fedora technical metadata**
```
ebucore: fileSize
	854195
ebucore: filename
	my_pdf_filename.pdf
ebucore: hasMimeType
	application/pdf
ns010: exifVersion
	10.00
ns011: pageCount
	13
ns012: valid
	true
ns012: wellFormed
	true
premis: hasCreatingApplicationVersion
	0.10.1
premis: hasFormatName
	Portable Document Format
```

**png in fedora technical metadata**
```
ebucore: fileSize
	85783
ebucore: filename
	my_png_filename.png
ebucore: hasMimeType
	image/png
ebucore: height
	423
ebucore: width
	1257
ns010: exifVersion
	10.00
ns010: orientation
	normal*
ns010: software
	gnome-screenshot
s014: compressionScheme
	Deflate
premis: hasFormatName
	Portable Network Graphics
```

**Comment by jmcglone** [comment]
Thanks @sethaj - we might want to do something with duration metadata for time-based media, so it could be useful to have that in Solr.

What we're capturing in Fedora is still a limited set of what FITS can get from a file. For a full list (I think this is complete) see:

http://projects.iq.harvard.edu/fits/fits-xml#metadata

For example, I wonder if we would want sample rates and bit rates for time-based media -- I believe I have seen both listed as important specs in [Deep Blue's best practices for video and audio](https://deepblue.lib.umich.edu/bitstream/handle/2027.42/83222/Video-Best_practices_1.1.pdf?sequence=7&isAllowed=y).

**Comment by jgmorse** [comment]
Sending Lance a link to this card to see if he or UMRDR has looked into this already.

**Comment by mbakeryo** [comment]
Talk with Lance about looping Matt Carruthers into the conversation.

**Comment by jmcglone** [comment]
See also https://wiki.duraspace.org/display/hydra/Technical+Metadata+Application+Profile
