### ISSUE TITLE
Enable non-Mich users to preview development

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#250]
Northwestern University Press partners Mike Levine (as the Acq Ed) and Dassia Posner (as the Author) will need to have the ability to view the development environment on their own in preparation for Beta 1 release.

What abilities should they have - read-only? 

Need to contact A&E for support
See #248

- [x] Contact A&E to remove IP restriction when we're ready to release to partner(s).
- [x] Remember to do #170

**Comment by sethaj** [comment]
Before we do this we need to have the following done:

- [ ]

**Comment by conorom** [comment]
the /tmp problem is solved by setting these environment variables when starting the Resque pool. On nectar that is here:
`/etc/systemd/system/heliotrope-testing-resque-pool.service`
These are the added lines, the first one specifically allows child processes (mini magick etc) time to clean up:
```
Environment="RUN_AT_EXIT_HOOKS=true"
Environment="TERM_CHILD=1"
```

**Comment by jmcglone** [comment]
@conorom @sethaj Can this be closed?

**Comment by conorom** [comment]
I do believe it can, by dad (at loooooong last).
