### ISSUE TITLE
Make asset show page look like Elderberry

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#251]
Elderberry wireframes:

Asset (Image) page: http://mlibrary.github.io/elderberry/press/book/item/image.html
Asset (Audio) page: http://mlibrary.github.io/elderberry/press/book/item/audio.html
Asset (Video) page: http://mlibrary.github.io/elderberry/press/book/item/video.html

**Comment by jmcglone** [comment]
Breadcrumbs may require a separate ticket with a gem to help in breadcrumb creation

http://stackoverflow.com/questions/2280648/breadcrumbs-in-ruby-on-rails
