### ISSUE TITLE
Modify Monograph Metadata UI

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#253]
Blocked by #14

The monograph metadata in the UI needs to be customized for our needs; remove some of the out-of-the-box Curation Concerns fields.

- [x] Creator - Rename label Creator to Author. 
- [x] Change Primary Creator (family name) label to (last name) and Primary Creator (given name) label to (first name)
- [x] Contributor - Remove Contributor
- [x] Press - Rename Press label to Publisher, remove the Publisher field
- [x]  Source - Remove Source
- [x] ISBN - Create additional ISBN fields to capture Hardcover, Paperback, Ebook ISBNs
- [x] Editor - ~~Remove Editor (what does this mean?)~~ - KEEPING FOR NOW

**Comment by jmcglone** [comment]
Editor refers to the editor of a book -- sometimes there is no author and only an editor(s). It is important to make this distinction in the metadata for display purposes, generating citations, etc. We don't need the field for the Beta 1, but, I'd prefer to keep it for now. This is not an out-of-the-box field but one that was added during the first or second sprint.
