### ISSUE TITLE
Display Google Analytics usage stats to the public

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#256]
- [ ] Page views
- [ ] Include in the "Stats" tab on asset show page

**Comment by jmcglone** [comment]
find out what’s going in Hydra community regarding public metrics (what dev in CC looks like for future, also look at Sufia); press partners/author reports can be handled separately through GA dashboard and sent to stakeholders

**Comment by mbakeryo** [comment]
Look at Highsoft

**Comment by jmcglone** [comment]
Pageviews and downloads in Sufia/ScholarSphere - See https://scholarsphere.psu.edu/files/xw42n792v/stats

**Comment by sethaj** [comment]
In Sufia: https://github.com/projecthydra/sufia/blob/master/app/services/sufia/analytics.rb
