### ISSUE TITLE
Add Altmetrics and Dimensions badges to Monograph and Asset pages

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#257]
In order to do this, we'll need to start a conversation with Charles about modifying our contract with Altmetric.

**Comment by mbakeryo** [comment]
Blocked by #482

**Comment by jmcglone** [comment]
Just do this for Monographs - Jon to share things to crawl with Altmetric and add JS to relevant pages to display altmetric badges. Dimensions badges too.

**Comment by jmcglone** [comment]
Will need mockups of where the badges will be displayed.

**Comment by jmcglone** [comment]
Blocked  by #1713

**Comment by jmcglone** [comment]
Add to `<head>` or anywhere on page:

Altmetric
```
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
```
Dimensions
```
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
```

Altmetric badge for monograph

`<div data-badge-popover="right" data-badge-type="donut" data-doi="10.1038/nature.2014.14583" data-hide-no-mentions="true" class="altmetric-embed"></div>`

Dimensions badge for monograph
`<span class="__dimensions_badge_embed__" data-doi="10.1001/jama.2016.9797" data-hide-zero-citations="true" data-legend="hover-bottom" data-style="small_circle"></span>`

Altmetric badge for monograph stats

`<div data-badge-details="right" data-badge-type="medium-donut" data-doi="10.1038/nature.2014.14583" data-hide-no-mentions="true" class="altmetric-embed"></div>`

Dimensions badge for monograph stats

`<span class="__dimensions_badge_embed__" data-doi="10.1001/jama.2016.9797" data-hide-zero-citations="true" data-legend="always" data-style="large_circle">`
