### ISSUE TITLE
Display assets in list, thumbnail, or gallery view

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#263]
**BETA 1 BUBBLE**

**USER STORY**

As a general public user, I should be able to view the assets in list, thumbnail, or gallery view in search and browse results.

**Comment by sethaj** [comment]
List: 
  http://mlibrary.github.io/elderberry/press/book/index-list.html

Thumbnail (default, we already have this):
  http://mlibrary.github.io/elderberry/press/book/index.html

Gallery:
  http://mlibrary.github.io/elderberry/press/book/index-gallery.html

**Comment by sethaj** [comment]
![screencapture-127-0-0-1-3000-concern-monographs-6108vc59n-1478275493551](https://cloud.githubusercontent.com/assets/3924142/20012813/25594872-a287-11e6-8afd-2fcbd0d0b734.png)

**Comment by sethaj** [comment]
In blacklight a "list" view is what this story calls a "thumbnail" view. So right now we have the "thumbnail" (default) view and the "gallery" view. We're going to skip the "no thumbnail" view for now, but might circle back and create it in a different story.
