### ISSUE TITLE
Make Press landing page look like Elderberry

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#264]
**Reference**

Elderberry: http://mlibrary.github.io/elderberry/press/index.html

If the book is not yet published, do not have a link to the book page.
Label "forthcoming"

**Comment by jmcglone** [comment]
This is mostly completed in a modified form.

Post pilot/beta launch of the five titles, we should have a future discussion about what it means to "publish" a monograph and how to control that within the application -- for example, how do I create a monograph, make it's information visible, but indicate that its assets and the content itself is not yet ready (ie forthcoming)?

Also, the elderberry wireframes contain thumbnails of assets associated with the monograph. We will hold off on displaying this until this actually comes in as a feature request.

**Comment by mbakeryo** [comment]
@jmcglone What is your opinion on this ticket? Do you think we should call this closed and generate a new ticket once we've determined the "forthcoming" display aspect? Also, do you think we will display thumbnails of assets on this page?

**Comment by jmcglone** [comment]
@mbakeryo yep, I think this can be closed and agree we should create a ticket or series of tickets around the forthcoming display stuff once we're there.

I like the idea of displaying thumbnails of assets on the pub page but we really should wait until that comes in as a request, or when we refactor the publisher and book catalog pages to deal with full text.
