### ISSUE TITLE
Create Google Analytics usage reports to send to partner presses

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#267]
Determine who at each partner press should receive reports:
- [x] Minnesota: Terence: https://datastudio.google.com/open/0B-CNui8jTxj4Wjh2MGMzVG53ck0
- [x] Northwestern: Emily: https://datastudio.google.com/open/0B-CNui8jTxj4ZU1JSy1yYWVZdG8
- [x] Penn State: Patrick: https://datastudio.google.com/open/0B-CNui8jTxj4M2F4UWlPOF9iNTA
- [x] Indiana: Gary: https://datastudio.google.com/open/0B-CNui8jTxj4aTZwOHZvdl9oZTg
- [ ] Michigan: Charles, Mary: https://datastudio.google.com/open/0B-CNui8jTxj4MHByUVlwRnJfQWc [need to ask Becky]

Determine how often reports are sent:
- [x] Weekly - saved to Google folders: https://drive.google.com/drive/folders/0B-CNui8jTxj4NlZIc2o4YXFCcUU?usp=sharing
- [ ] Monthly
- [ ] Quarterly
- [ ] Annually

Determine what types of reports to send:
- [x]  Audience Overview
- [x] Referral Traffic
- [x] Landing Pages
- [x] Exit Pages
- [x] Pages
- [x] Channels
- [x] Search Terms (will we have Google Search to enable this?)
- [x]  Organic Search Traffic
- [x] Any technical reports - Devices, Browsers/OS
- [x] Any events - set-up on click on buy book link, assets, download button, scroll position, etc.

**Comment by mbakeryo** [comment]
I set-up weekly reports for Audience Overview, Location, Browser and OS, Devices, Channels, Referral Traffic, Pages, Landing Pages, Exit Pages, Site Search Usage, and Search Terms.

Jon and I have a meeting on 10/13 to work out what would work best (reports and how often they should go out).

**Comment by mbakeryo** [comment]
I emailed NU and MN again on 12/5/16 to ask about reporting wants. Also gave contacts access to the Google Folder where weekly reports are being uploaded.

**Comment by mbakeryo** [comment]
As I'm not getting any feedback from client's, I'm going to set-up quarterly reports through GA and let that prompt what other metrics needs there are. Do this for MN, NU, and MI.

**Comment by jmcglone** [comment]
Per our 5/3 weekly meeting, investigate doing these reports in Google Data Studio to mockup and get feedback from partners on what they'd like to see in their reports.

**Comment by mbakeryo** [comment]
7/11/17: emailed Terence and Emily with new Data Studios reports for feedback.

**Comment by mbakeryo** [comment]
Emily's feedback:
-Can you drill down and see the states that the page visits came from? 
-Is it possible to see what sections are being accessed ? After the Project Muse conference we're talking more and more about chapter level metadata and abstracts, and a feature like that might be a useful to see what type of content is popular.

**Comment by mbakeryo** [comment]
8/11/17: I'm closing this ticket, as all partners have GA properties set-up, Data Studios reports (visualization reports) created, and canned usage reports saved weekly to the Google Drive. Further finessing of reports, or who should receive them, will be handled in other tickets.
