### ISSUE TITLE
Set-up redirect for press subdomain

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#268]
Need help from A&E

Acceptance criteria:
- [x] Content currently at fulcrum.www.lib.umich.edu should be served under fulcrum.org
- [x] Corollary: Content currently at fulcrum.www.lib.umich.edu/northwestern should be served under fulcrum.org/northwestern
- [ ] Redirect fulcrumscholar.org/northwestern -> fulcrum.org/northwestern
- [x] Redirect northwestern.fulcrumscholar.org -> fulcrum.org/northwestern

**Comment by jgmorse** [comment]
Blocked until we have final acceptance from Northwestern that https://fulcrum.www.lib.umich.edu/northwestern looks ready.
