### ISSUE TITLE
Disable downloads

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#287]
In the metadata template, there's a column called "Allow Download?". If it's marked "no" then the asset should not be downloadable.

- [x] If the asset is marked download = no, disable download
- [x] Create JS snippet to ~~remove `src` attribute from video tag~~ disable right click on video elements

**Comment by sethaj** [comment]
PR #301 for images, office docs and pdfs. If we include video or audio in this, then there is no preview available and the asset can't be seen or heard. This might be what we want to do, I'm not sure.

**Comment by sethaj** [comment]
We're waiting for feedback on the video/audio assets.

**Comment by jmcglone** [comment]
Stopping the download of audio and video as recommended by Mozilla includes removing the `src` tag by using some javascript outlined here:

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML5_audio_and_video#Stopping_the_download_of_media
