### ISSUE TITLE
Page title for asset pages should be the asset title

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#333]
Change the page title to use the asset title.

Currently, the page title uses the file name. The file name should never be public-facing.

<img width="458" alt="screen shot 2016-08-01 at 7 34 02 pm" src="https://cloud.githubusercontent.com/assets/17436011/17312188/f72a724e-581e-11e6-89c6-fd2ddee25608.png">

The page title should instead be: Photograph of Nina in The Seagull

**Comment by sethaj** [comment]
Change app/views/curation_concerns/file_sets/show.html.erb line 1 from this:

```
<% provide :page_title, @presenter.page_title %>
```

to this:

```
<% provide :page_title, @presenter.title.first %>
```

**Comment by conorom** [comment]
I have a memory of seeing markup/underscores in page titles recently (was it a dream or was someone experimenting on nectar?), so that should be confirmed and stripped before setting :page_title.

You can do it manually or get redcarpet to do it:

```
require 'redcarpet'
require 'redcarpet/render_strip'

md = Redcarpet::Markdown.new(Redcarpet::Render::StripDown, space_after_headers: true)
md.render(title)

```

**Comment by gkostin1966** [comment]
**curation_concerns**/app/models/concerns/curation_concerns/solr_document_behavior.rb
```
def title_or_label     
  return label if title.blank?    
  title.join(', ')     
end

def to_s               
  title_or_label       
end
```
                                                                                 
**curation_concerns**/app/presenters/curation_concerns/file_set_presenter.rb     
```
def page_title
  label
end
```   

app/presenters/curation_concerns/file_set_presenter.rb
```
def page_title
  Array(solr_document['label_tesim']).first
end 
```

app/views/curation_concerns/file_sets/show.html.erb
```
<% provide :page_title, @presenter.page_title %>   
```

**Comment by gkostin1966** [comment]
**curation_concerns** add/models/concerns/curation_concerns/basic_metadata.rb
```
property :label, predicate: ActiveFedora::RDF::Fcrepo::Model.downloadFilename, multiple: false
```
https://www.infoq.com/articles/properties-metaprogramming

**Comment by mbakeryo** [comment]
Double-check to make sure that the file name does not also appear on the Technical Info section of the asset page.
