### ISSUE TITLE
Add markdown capability to Display Date asset field

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#334]
There is at least one case where an asset has a display date that contains italics.

<img width="548" alt="screen shot 2016-08-01 at 9 02 50 pm" src="https://cloud.githubusercontent.com/assets/17436011/17313640/5f39002e-582b-11e6-84ac-23949c4e1f30.png">

**Comment by sethaj** [comment]
Change app/views/curation_concerns/file_sets/_attribute_rows_info.html.erb from this:

```
<%= presenter.attribute_to_html(:display_date, label: 'Date') %>
```

to this:

```
<%= presenter.attribute_to_html(:display_date, label: 'Date', render_as: :markdown) %>
```
