### ISSUE TITLE
Fix Year Facet results

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#340]
Situation:

1. When clicking on the More link in the Year facet, selecting a Year to facet on results in a We're sorry, but something went wrong page.

2. When clicking on the More link in the Year facet, there should be only a single entry for a particular year. E.g., there should only be one listing for 1914, not two.

<img width="546" alt="year_facet" src="https://cloud.githubusercontent.com/assets/17436011/17362164/d60c1382-5941-11e6-9772-86dc3a90d95d.png">

**Comment by sethaj** [comment]
1. is addressed in #331
2. Right now we're faceting by YYYY-MM-DD but only showing YYYY. We'll need a way to "compress" YYYY-MM-DD into just the YYYY for the facet. Hopefully something here  https://github.com/projectblacklight/blacklight/wiki/Configuration---Facet-Fields will help with this.
