### ISSUE TITLE
Fix Exclusivity Facet

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#341]
Situation:

The Facet results show "Appears in book" twice.

<img width="272" alt="screen shot 2016-08-03 at 6 25 50 am" src="https://cloud.githubusercontent.com/assets/17436011/17362658/11f2d154-5944-11e6-8c84-a2a2da2e1c24.png">

Should be:

If there are both Book and Platform (BP) and Platform-only (P) assets, the Facet should show Appears in book and something else, like Website-only or Exclusive to platform.

In addition: 

We also need to decide what the behavior should be if  none of the assets are Platform-only. If that's the case, does the Facet appear at all?

**Comment by sethaj** [comment]
Right now exclusivity is looking for "yes"/"no". What it should be looking for is "P" (Platform only) or PB (Platform and Book). Fix in app/helpers/facet_helper.rb

**Comment by conorom** [comment]
This is the sort of thing I was trying to foresee by changing values like this at import time and/or it could feed back to a future iteration of the spreadsheet's column descriptions? If it makes code more readable I should change P to true and BP to false on import. Maybe.
