### ISSUE TITLE
Monograph catalog view: only show assets related to parent monograph

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#345]
All assets in the repository, regardless of what parent monograph they belong to, are displaying on any monograph catalog view.

Current behavior: When I go to a monograph catalog view page, I see a list of all the assets that have been loaded to the repository, including assets that do not belong to that parent monograph.

Expected behavior: When I go to a monograph catalog view page, I only see the assets that belong to that monograph.

**Comment by sethaj** [comment]
Maybe https://github.com/mlibrary/heliotrope/blob/master/app/models/monograph_search_builder.rb#L22

```
docs = ActiveFedora::SolrService.query("{!terms f=id}#{ids.join(',')}")
```

should be

```
docs = ActiveFedora::SolrService.query("{!terms f=#{id}}#{ids.join(',')}")
```

Also: write a test to make sure we check this so it doesn't happen again.

**Comment by jmcglone** [comment]
@sethaj When I make that change to line 22 I get no assets in the result set.

**Comment by jmcglone** [comment]
The above line *does* fix the problem.

However, there are still remnants of this bug lingering -- If I create a second monograph and it has zero asset, the monograph catalog pages will display all assets in the repository. However, once the second monograph has a child asset created, the bug goes away, and the expected behavior is successful.

It may be worth adding a bit of logic to not display anything if the monograph has no child objects.

**Comment by jmcglone** [comment]
lower priority because we are launching beta 1 with one monograph
