### ISSUE TITLE
Determine how external (non-Michagan) press admins will be authenticated and authorized

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#35]

**Comment by sethaj** [comment]
There are some different option to explore, cosign friend accounts, shib, etc, but for now we're going to stick with internal rails user/role management of both internal and external users. At some point, and this would be dictated by changes A&E make to infrastructure, we'll plan on moving away from this. For now it's fine to use rails, but I'll leave this ticket open as a reminder to periodically check-in with A&E about other approaches.

**Comment by jmcglone** [comment]
This will be a front door card for the next LIT front door cycle
