### ISSUE TITLE
Facet on Content Type (subfacet of Format)

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#368]
Is there a way for when faceting on Format, a user could then be presented with subcategories (Content Type) to choose from?

Research how this would work and what it would look like.

**Comment by jmcglone** [comment]
Looks possible. See for example config in Solr:

http://yonik.com/solr-subfacets/

**Comment by jgmorse** [comment]
Eventually we'll wan to use a GUI metadata editor for this akin to Columbia's Hyacinth (https://github.com/cul/ldpd-hyacinth) -- though we have to wait until it's compatible with Fedora 4.
