### ISSUE TITLE
Integrate fulcrum.org info pages into heliotrope

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#373]
- [x] User going to document root sees the jekyll site currently at fulcrum.org

If our initial production deployment was to fulcrumscholar.org/northwestern:

- [ ] Redeploy Northwestern production site to fulcrum.org/northwestern
- [ ] Redirect fulcrumscholar.org/northwestern -> fulcrum.org/northwestern

**Comment by jmcglone** [comment]
See

https://blog.engineyard.com/2012/introducing-bloggy-a-simple-way-to-add-a-jekyll-blog-to-any-rails-application

and

https://github.com/zbruhnke/bloggy

**Comment by jmcglone** [comment]
The above gem is way out of date and not maintained. This tutorial seems like a better way forward:

https://www.sitepoint.com/jekyll-rails/

**Comment by jmcglone** [comment]
For getting jekyll assets into the asset pipeline, a jekyll plugin!

https://github.com/jekyll/jekyll-assets
