### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#379]
A GET for favicon happens on every request on the different deploy targets on nectar resulting in an error because the app thinks "favicon" is a subdomain.  Add a route to fix this. It's possible that we'll also need to put a favicon.ico into /public to also fix this. This only happens in "production" not test or dev since only production has apache in front.

From the production.log

```
I, [2016-08-11T09:07:53.990107 #13491]  INFO -- : Started GET "/favicon.ico" for 141.211.43.239 at 2016-08-11 09:07:53 -0400
I, [2016-08-11T09:07:53.993895 #13491]  INFO -- : Processing by PressCatalogController#index as 
I, [2016-08-11T09:07:53.993975 #13491]  INFO -- :   Parameters: {"subdomain"=>"favicon"}
... and then errors ...
```

**Comment by sethaj** [comment]
While the favicon is showing and looks great, the app still thinks there's a /favicon.ico route in production which pollutes the logs. Opening this back up to fix the route.

```I, [2016-09-12T16:17:22.627806 #26518]  INFO -- : Started GET "/favicon.ico" for 141.213.171.75 at 2016-09-12 16:17:22 -0400
...
D, [2016-09-12T16:17:22.668113 #26518] DEBUG -- : Solr fetch (18.5ms)
I, [2016-09-12T16:17:22.669115 #26518]  INFO -- : Completed 406 Not Acceptable in 39ms (ActiveRecord: 6.9ms)
F, [2016-09-12T16:17:22.671834 #26518] FATAL -- : 
ActionController::UnknownFormat (ActionController::UnknownFormat):
  blacklight (6.3.0) app/controllers/concerns/blacklight/catalog.rb:176:in `block in document_export_formats'
```

**Comment by sethaj** [comment]
I've been trying to reproduce the 406 log errors for the /favicon.ico route and I can't, it seems like  the application no longer has this problem. It might be some changes to the apache config on nectar that were recently made. Closing this, if it ends up being a problem again I'll reopen.

**Comment by conorom** [comment]
Loading any of the Resque pages will produce this error in the logs.

**Comment by sethaj** [comment]
Looks like @gkostin1966 saw this again and opened #851. But then closed it again unable to reproduce. This problem is elusive...

**Comment by jmcglone** [comment]
have a link element with the data uri that points to the favicon

**Comment by respinos** [comment]
Ex: 
```<link href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII=" rel="icon" type="image/x-icon" />```

**Comment by sethaj** [comment]
It looks to me like this was fixed with this: https://github.com/mlibrary/heliotrope/pull/1456/files#diff-21497849d8f00507c9c8dcaf6288b136R94

I don't see the error in preview, even when going to `/resque` and I don't see it in dev. I'm going to close this (again, optimisitcally :smile:).
