### ISSUE TITLE
Automatically associate a new monograph with a press

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#38]
**STORY**
As a press  editor, I don't want to have to choose which press each new monograph belongs to, so that I don't get errors if I choose a press that I don't have rights within.

**DETAILS**
In the list of presses displayed when a user creates a new monograph (see #95), more than one press may be displayed.  

**ACCEPTANCE**
- [x] Only the presses I have been granted administrator or editor privileges to show up in the list of available presses when I create a new monograph (provided by #95)
- [ ] If only one press is in the list, it is automatically selected when I create a new monograph
- [x] If more than one press is available to me, none is selected by default and I have to manually select before saving the new manuscript. (default behavior from #95)

**Comment by mark-dce** [comment]
Blocked by #95

**Comment by mbakeryo** [comment]
This was done (sort of). May need adjustments, but we'll know more once roles are fleshed out. See #844.
