### ISSUE TITLE
Disable downloads

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#385]
As a user, I should not be able to right-click (or control click) on an image and download it.

**Comment by jmcglone** [comment]
To clarify, and push back a little, this is not a bug. #287 only specified right-click disabling for video, and later audio -- before that feature was in place, if a user right clicked and "save as" on a video/audio player, they were able to download the ENTIRE video.

For images, if a user right clicks and selects "save as" on an image, they only get a portion of the image and that portion of the image is a low-res version (max size was 256px x 256px). We had agreed that this functionality was acceptable. In addition, if the metadata for an image asset specifies that the image cannot be downloaded, then no "Download" button is provided for the image -- which was also part of what was introduced in #287.

**Comment by mbakeryo** [comment]
Removed Bug label per Jon's comment.
