### ISSUE TITLE
Enable line break spacing in translations

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#399]
On an asset page, in the translations section of the page, the copy should be able to withstand single line breaks (in addition to multiple line breaks).

Line breaks should be retained through the importer, or made possible through the UI.

- [ ] Prevent empty paragraphs with only line breaks

**Comment by conorom** [comment]
We're going to set the redcarpet renderer's hard_wrap flag to true. This will mean *all* fields rendered as markdown (i.e. not just translation) _should_ get get <br> tags where the original content had line breaks, with no double spaces required beforehand.
