### ISSUE TITLE
Upgrade to CC 1.6.2

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#402]
Just noticed we've missed a few CC upgrades while we were busy in July and August -- we're still using 1.1.

https://rubygems.org/gems/curation_concerns/versions/1.3.3

**Comment by jmcglone** [comment]
Testing new GH integration.

**Comment by sethaj** [comment]
We should coordinate with umrdr on this since we're sharing an environment and use whatever version of CC their version of Sufia is using.

**Comment by jmcglone** [comment]
@sethaj Good point. UMRDR is currently using Sufia 7, which uses CC 1.1. So we're okay for now. Sufia 7.1 uses CC 1.4

**Comment by sethaj** [comment]
I don't think (anymore) that we should necessarily follow DBD/umrdr updating curation concerns as long as we can stick to a shared version of Fedora (currently 4.5.1). CC is currently on 1.6.2. We should try to keep up with updates, probably evaluating and upgrading quarterly if at all possible.
