### ISSUE TITLE
Resolve Typekit JS loading time

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#434]
I've only noticed this on the Northwestern press landing page. The biggest problem is on Chrome where the fonts don't download/cache fast enough the first time this page is loaded in a tab. Chrome seems to give up on waiting and so the fonts on the page are not styled as Jon intended. This means you are left with text wrapping under the NU Press logo etc.
However, even when the Typekits fonts do load, they kick in slowly enough that it is too easy for the eye to see the jarring change.

- [x] speed up Typekit loading (maybe store locally). This should solve both issues.
- [x] verify that Chrome loads the page fully the first time round
- [x] verify that the time taken for the fonts to change is acceptable to the 'AVERAGE USER'

**Comment by jmcglone** [comment]
By moving the font load before the CSS and other JS calls, the FOUT (flash of unstyled font) time is dramatically reduced AND loads properly on Chrome.
