### ISSUE TITLE
Ensure that non-press items are not discoverable through Press platform

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#44]

**Comment by val99erie** [comment]
For example, if the production heliotrope is using the same fedora as deep blue or some other app, make sure that the heliotrope data isn't accidentally exposed by some other app, and make sure the other app data isn't accidentally exposed by heliotrope.

**Comment by mbakeryo** [comment]
This is related to #347.

**Comment by sethaj** [comment]
If you try to access a deep blue data file_set  (like https://deepblue.lib.umich.edu/data/concern/file_sets/h128nd778) you get the unauthorized (or login) page. If you try to access a fulcrum file_set (like https://fulcrum.www.lib.umich.edu/concern/file_sets/0g354f20t) from deep blue data, you get the unauthorized (or login) page. So it seems each app can't access the other's data in any way through the UI.
