### ISSUE TITLE
Add aiff file support

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#441]
This originally related to #342. We were having some problems with job characterization of audio files. It turns out that .aiff is not supported by hydra-works, but we've been asking Presses to submit .aiff files. The near term fix is to ask for .wav files. But we should submit a pull request to hydra-works at some point with .aiff support.

https://github.com/projecthydra/hydra-works/blob/master/lib/hydra/works/models/concerns/file_set/mime_types.rb#L39

**Comment by jmcglone** [comment]
Try adding it to the list of mime types and it might work!
