### ISSUE TITLE
Use handle service to create handles on asset creation

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#478]
Blocked by:
- [x] NOIDs for objects have to persist after asset creation (either because we're creating in production, or we're migrating content from dev in such a way that NOIDs persist with the object).

Acceptance Criteria:
- [x] When an asset is created (either via GUI or importer), a central Handle creation service is called.
- [ ] The handle service creates a unique Handle that resolves to the asset display page in heliotrope, and returns the Handle URL to the calling method.
- [ ] The Handle URL is added to the asset's metadata.

**Comment by mbakeryo** [comment]
we will need this for HEB

**Comment by jmcglone** [comment]
#847 is a duplicate

**Comment by jgmorse** [comment]
Note from Sebastien that should be investigated: "Aaron hits the database directly, as the Java tool is too slow for his needs. Handle 8 that we are now using has new REST API we should explore. That will take a bit of playing around and updating of local tools though."
