### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#480]
Write Rachel Vacek and communicate our desire for an external accessibility audit for the platform.

**Comment by mbakeryo** [comment]
Blocked by #258 and #260

**Comment by jmcglone** [comment]
1) Conduct our own audit using the Chrome [AXE plugin](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) and make changes based on the accessibility report.

2) Request functional accessibility audit from Scott Williams to test screen reader and other assistive technology on Fulcrum platform.

3) Make changes based on Scott's report.

**Comment by jmcglone** [comment]
We're making several updates to the UI during Sprint 18, so let's schedule conducting our own audit and making changes (step 1 in the above comment) for Sprint 19.

**Comment by jmcglone** [comment]
The report is available at

https://docs.google.com/a/umich.edu/document/d/1AlzbI1TjUDbce4CxzCmkWZplTtIHLMllYzL3162k3TE/edit?usp=sharing
