### ISSUE TITLE
Investigate contract issues with Altmetric to use on Fulcrum

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#482]
Talk with Charles to determine:
- [ ] Does our current contract cover this use on Fulcrum
- [ ] Does Altmetric have any interest in tracking this type of material

**Comment by jmcglone** [comment]
E-mail was sent to Altmetric on Nov. 9

**Comment by mbakeryo** [comment]
Awaiting Charles to work this out with Altmetric. They may be waiting until February 2017 when our contract expires.

**Comment by mbakeryo** [comment]
8/21/17: I'm closing this as this is a contract issue. The actual Heliotrope work is captured in ticket 257.
