### ISSUE TITLE
Create and add GA ID for partners

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#483]
Need to create GA IDs for:
- [x] Minnesota: UA-77847516-5
- [x] Indiana: UA-77847516-6
- [x] Penn State: UA-77847516-7
- [x] Michigan: UA-77847516-8

Add GA ID to Fulcrum:
- [x] Minnesota
- [x] Indiana
- [x] Penn State
- [x] Michigan

**Comment by sethaj** [comment]
GA IDs are in the seeds file. Presses will get they're GA ids as they are added to production.
