### ISSUE TITLE
Brand Minnesota

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#486]
Add branding elements/customize Minnesota

Due from Minnesota by October 7:

- [x] Minnesota landing page copy
- [x] Colors to use for header, footer, links, etc.
- [x] Font to use for word logo in header/footer
- [x] Footer links

Special note: Minnesota's logo is horizontal. Sizing, placement may be challenging

**Comment by jmcglone** [comment]
Did these materials arrive?

**Comment by mbakeryo** [comment]
This is what has arrived:

Landing page copy: 

Established in 1925, the University of Minnesota Press is recognized internationally for its innovative, boundary-breaking editorial program in the humanities and social sciences, and is committed to publishing books on the people, history, and natural environment of Minnesota and the Upper Midwest.

This page is the home of supplemental content for select University of Minnesota Press books. You can find the full catalog of Minnesota titles on the publisher's website.

("Publisher's website" should link to: https://www.upress.umn.edu/)

Hex code: 800000

This is what has not arrived:

As of yet, I have not received any font preferences for the header/footer. If you need a specific font to do the branding, please say so and I'll ask Terence for it.

Also, I have not received any links to put in the footer. It's possible that they don't have any/want any for right now. I'm currently checking.

What do you need:

Please let me know if you need anything else in order to start branding MN.

**Comment by mbakeryo** [comment]
Font: There are no font preferences coming from Minnesota.

Footer Links: Beyond a link back to the University of Minnesota Press, there are no additional links.

Logo in the Footer: Terence says that "There looks like there's a bit of a white border in the footer around our logo. Let me know if you need us to adjust that; likewise feel free to do so there if it's easier. Either way."

Authors' Social Media: One of the author's has a Twitter account. Terence says: " https://twitter.com/mrneuzil (@mrneuzil). Let me know if you want me to draft some copy or if you guys would prefer to take the first stab at it." MBY note: I've asked Terence to articulate what he is imagining for this, as I was thinking it'd just be a Twitter icon on the Landing Page that went to the author's Twitter feed. 

Landing Page regarding logo: From Terence/UMP reviewer: "Front page of website: UMN Press logo seems too large on the screen in relation to other text"

**Comment by mbakeryo** [comment]
Here is some language regarding one of the author's Twitter feeds that should be added to the book description: Follow author Mark Neuzil (@mrneuzil) on Twitter for regular updates about this project and the continuing story of the canoe.

**Comment by jmcglone** [comment]
![minnesota-branding](https://cloud.githubusercontent.com/assets/1686111/19577010/6f624c8e-96e3-11e6-93f1-68b37069273c.png)

@mbakeryo thoughts? It will be easier to look at if it were deployed to preview, but if you have any initial bad reactions to the colors or fonts let me know before I commit, merge, and deploy the "Minnesota Theme"
