### ISSUE TITLE
Fix weird breaking keywords issue on asset page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#487]
On some asset pages, keywords are breaking onto a new line, but should be on the same line as the preceding keyword.

See examples: 

Playbill for Columbine’s Veil at https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/db78tc01m

Cover design for the journal Love for Three Oranges
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/wm117p028

**Comment by conorom** [comment]
It's probably worth thinking about the fact that these are set to become links in #490. If they are still displayed inline in link color, will it be obvious that multi-word keywords are one link, etc.
Maybe just removing the `display: inline` on these is the way to go.

**Comment by gkostin1966** [comment]
Changed `display: inline` to `display: inline-flex` and added style to separate keywords by commas.
