### ISSUE TITLE
Add ability to navigate to the next and previous asset from the asset page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#489]
As a general public user, while on an asset page, I should be able to navigate to the next asset, or move to the previous asset, in the relevant results list, so I don't have to go back to the main results page.

Is this straight-forward or is additional work needed?

For example, do we need to work out what assets this navigation will be applied to? Will facets, sort order, etc., be considered in this navigation.

**Comment by mbakeryo** [comment]
Need to have a deep dive conversation about this.

**Comment by jmcglone** [comment]
See arrows under breadcrumbs at http://mlibrary.github.io/elderberry/press/book/item/audio.html
