### ISSUE TITLE
Make metadata fields interactive on asset page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#490]
As a general user, when I go to an asset page, some of the metadata should display as links, so that if clicked, I will be taken to a list of all assets that have that same classification.

Metadata that should be linked:
- [x] Creator
- [x] Creator Role ? (low-priority)
- [x] Contributors ? (low-priority)
- [ ] Subjects (low-priority)
- [ ] Date ? (uncertain if this is useful/wanted since it's the Display Date and could be confusing)
- [x] Related Section 
- [x] Keywords
- [x] Content Type
- [x] Language

To start, should the results be contained to the monograph the user is on and not across presses? (For example, if a keyword is shared by Minnesota and Northwestern, if a user is on Northwestern's book, the results would only show Northwestern assets?)

**Comment by jgmorse** [comment]
I think we should limit it to within the same press, as that reinforces the white-label hosting solution we want to offer.  (The cross-press searches can come later in a different set of views.)

**Comment by sethaj** [comment]
Would it be ok if this was initially limited to within the individual monograph? I think by default that's what's going to happen. As we get multiple books per Press we can revisit how it works...

**Comment by conorom** [comment]
For now I think we can punt Subject altogether, given that Subject is a monograph attribute and therefore will search at the press level. Right now that would always return the one and only book under that press.

I agree that linking Display Date to anything requires more thought, given that it is free text and can have any ol' thing in there. It might be cool to detect a valid year value and use that as the search term.
