### ISSUE TITLE
Multiple instances of the same asset should only appear once in browse/search results

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#491]
Assets that are associated with multiple sections should not show up multiple times in browse and search results (including facet results).

The solution may be tied to the work being done with Capybara (now Capable Bear ie: full text search with hydra).

**Comment by conorom** [comment]
Now that sections are represented by the multi-valued field, `section_title`, they will not appear twice in future. I will create a separate ticket RE: existing duplicated assets in the NW monograph.
