### ISSUE TITLE
Figure out tombstone process

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#493]
What do we do when either permission for an asset expires or a rights-holder requests we take down an asset from the site (define what "take down" means).
- [ ] Do we remove the asset from Fedora or just no longer display the asset? Delete from Fedora.
- [ ] Can we continue displaying all of the metadata?
- [ ] Does the metadata change at all - for example, the permissions information?
- [ ] What messaging do we put up to indicate that this asset has been "taken down" or that permissions has expired?  (Awaiting Amy to send HathiTrust language to see if we can leverage)
- [ ] Is the process the same for both taking down due to a request and a permission expiration?
- [ ] Write up take down language to use for rights holders
- [ ] Write up information for rights holders about how to request the asset to be taken down
- [ ]  Email Melissa L. and Charles to see what can be leveraged from DBD (of the take down process and language to use, what our rights are and what we can still display)
- [ ] Need to articulate - putting up the tombstone and removing the file/bitstream. These are separate requests and will need to decide how to handle this.

Need to make an item unavailable that used to be available. Need a way to trigger this behavior. 
- [ ] Then a user that follows the direct URL, what do they see?
- [ ] What search behavior needs to change?
- [ ] Nothing happens except for when you land on the view page, the page is different. 
- [ ] Read/Download/Preview - access to the bitstream is disabled.

**Comment by gkostin1966** [comment]
Current behavior is to `raise CanCan::AccessDenied` when encountering a tombstone a.k.a. ldp::Gone.

**Comment by mbakeryo** [comment]
@jgmorse Can you and I meet to go through the above checklist and capture answers/next steps?

**Comment by jgmorse** [comment]
Meeting scheduled for 7/10.

**Comment by mbakeryo** [comment]
This is more of a business process question, so we are going to remove it from this board until there are actual tasks to do on the platform.
