### ISSUE TITLE
Brand Penn State

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#494]
Add branding elements/customize Penn State

Emailed Jennifer Norton 9/13/16

Outstanding:
- [ ] Penn State landing page copy
- [ ] Footer links

Already have:
- [x] Colors to use for header, footer, links, etc.
- [x] Font to use for word logo in header/footer

**Comment by jmcglone** [comment]
@mbakeryo where is the penn state landing page copy?

**Comment by mbakeryo** [comment]
@jmcglone Use what we have on staging for now. I've unchecked landing page copy from the list above. I think it was checked bc the Book copy was confirmed, but we never got the PS landing page copy.
