### ISSUE TITLE
Create Gabii (on DLXS) wireframes

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#505]
- [x] Due October 7 for author visit
- [x] Due October 21 for Charleston visit

The wireframes will show what the Gabii book (narrative, 3D model and database) will look like on DLXS.

**Comment by jmcglone** [comment]
PDF versions of the wireframes are available here

https://drive.google.com/a/umich.edu/file/d/0B_JnCrIk48N0SHhTV042NjNHOTg/view?usp=sharing

**Comment by jmcglone** [comment]
Over the next couple weeks I will be converting these wireframes to HTML-y things for Charleston

**Comment by jmcglone** [comment]
HTML/JS Prototype

![gabii-prototype-1](https://cloud.githubusercontent.com/assets/1686111/19656292/6354b140-99ed-11e6-945e-c6a19bc7b157.png)

![gabii-prototype-3](https://cloud.githubusercontent.com/assets/1686111/19656301/6c0fce50-99ed-11e6-8ced-7cc330e10dfd.png)
