### ISSUE TITLE
resque workers

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#507]
Right now in staging and preview we only have 1 resque worker running due to some issues we had running multiple workers.
- [ ] Try to reproduce the errors in staging by running multiple workers while importing a monograph

**Comment by sethaj** [comment]
I think that part of issues with multiple workers is really a problem with how the importer works.

When the importer, lib/importer/importer.rb, calls:
```
monograph_builder.run
```

The monograph and every single one of the assets are created. For each asset a series of FileSet jobs are kicked off, ingest, derivatives, characterization. Those jobs can finish "whenever" and there's no guarantee when they will finish. But importer.rb keeps on going next calling:

```
update_fileset_metadata(monograph, monograph_file_attrs)
```

Which then updates the metadata for each FileSet by doing:
```
        monograph.ordered_members.to_a.each_with_index do |member, i|
          builder = FileSetBuilder.new(member, user, attrs[i])
          builder.run
        end
```

I think part of the problem is that when this happens monograph.ordered_members isn't actually complete yet. So only some of the FileSets ever get metadata. The assets are still there, with thumbnail and technical metadata from characterization, but some (usually in the "back" on the catalog page) have no metadata from the metadata template csv file.

This hasn't been a problem with only 1 worker, but when there are 3 or so it all starts to fall apart. We might have to revisit how the importer works if we want to add more workers.

**Comment by mbakeryo** [comment]
We will need this for when other people begin uploading content to the platform.

**Comment by sethaj** [comment]
Unfortunaly this ticket didn't capture the actual error we were seeing. After the Hyrax2 update this problem (whatever it was...) seems to be gone. But we also made some changes to the importer for Hyrax2, so maybe that's related.

I think we should set the resque pool to 5 (umrdr has more than this so 5 seem safe). This happens in the heliotrope-deploy project, `/upload/[whatever]-config/resque-pool.yml`. heliotrope_testing already has this set to 5 (and is running hyrax2) and there haven't been any problems with importing or jobs running out of order or anything.

**Comment by sethaj** [comment]
This is done on staging/preview/testing. The change has been made for production, but it hasn't been deployed yet.
