### ISSUE TITLE
Deploy Minnesota to Production

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#513]
- [x] update seeds.db file with minnesota information n(including typekit id if needed)
- [x] tag release
- [x] deploy latest release tag branch to production
- [x] run seeds.db to create minnesota
- [x] contact A&E to setup redirects - all minnesota URLs redirect to fulcrum.org/minnesota
* minnesota.fulcrumscholar.org -> fulcrum.org/minnesota
* minnesota.fulcrumservices.org - > fulcrum.org/minnesota
* minnesota.fulcrum.org - > fulcrum.org/minnesota
* also ask A&E to do #554 (northwestern redirects)
- [x] Add minnesota google analytics id (UA-77847516-5) to press database table for minnesota
- [x] Generate handles for Minnesota.

**Comment by mbakeryo** [comment]
Planning to deploy 10/24 or the week of.
