### ISSUE TITLE
add typology of peer review

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#516]
When viewing a supplemental object or piece of full-text, we should indicate the level and type of review for the object. 
- [ ] create a list, or typology, of the kinds of peer review
- [ ] add this to the metadata template (template for work level)
- [ ] if peer review type is selected, it is displayed on the object's info page

**Comment by jmcglone** [comment]
An example of peer review typology icons from Mark Edington

![peerreviewiconography](https://cloud.githubusercontent.com/assets/1686111/19325908/45fb465a-9096-11e6-94af-3468dc72169a.jpg)

**Comment by jmcglone** [comment]
Lever Press is creating a controlled vocab/terminology/matrix for indicating level of peer review - based on the work of Jason Mittell.

**Comment by jmcglone** [comment]
Peer reviewed or not peer reviewed as an MVP for implementing this.

**Comment by jmcglone** [comment]
Labels and their definitions for peer-review, as documented at  https://www.leverpress.org/peerreview/:

Label: Single Blind
Definition: Reviewers may be informed of the author’s identity, but the author is not informed of the identity of the reviewers. Publication occurs after the author’s revisions in response to reviewers’ comments satisfy the editors and the Editorial Board.

Label: Double Blind
Definition: The identity of the author is not disclosed to the reviewers, and the identity of the reviewers is not disclosed to the author. Publication is contingent on the author responding to the critiques and commentary offered by reviewers to the satisfaction of the editors and the Editorial Board.

Label: Peer to Peer Review
Definition: The identities of both author and reviewers are disclosed each to the other. The process may result in more substantial exchanges and revisions to the work. Such a review process may eventuate from a process that began as Double- or Single-Blind; in other cases it may be employed for interdisciplinary work in which authors collaborate and review each other’s contributions. Choosing to employ such a review process is always done with the advance approval of the Editorial Board.

Label: Open Review
Definition: The work has been made publicly available through some accessible platform, and comment has been invited from a community of scholars. Various platforms (such as CommentPress or hypothes.is) may be utilized for organizing and curating the comment process; and each case may stipulate the terms by which reviewers may contribute to the work (e.g., anonymous, with names, with names and institutional affiliation). The selection of platforms and processes is undertaken on a case-by-case basis, and is shaped by those considerations that will best serve the work. When Lever Press works utilizing Open Review processes it will normally employ an additional form of peer review.

**Comment by mbakeryo** [comment]
We will need this, at the latest, for a launch in October 2018.
