### ISSUE TITLE
Story Points

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#545]
We have no choice but to use Fibonacci-like numbers to estimate card sizes using story points. 
  https://github.com/waffleio/waffle.io/wiki/FAQs#sizing-cards

I propose 20 points a week for a full-time resource, hence 40 points for a two week sprint.

A card given 100 points indicates it needs to be broken down into smaller pieces.

-Greg

**Comment by mbakeryo** [comment]
Place card in Wiki.

**Comment by gkostin1966** [comment]
https://github.com/mlibrary/heliotrope/wiki/The-Way
