### ISSUE TITLE
Test fedora import/export tool

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#556]
For the Michigan project, play around with the Fedora repository import/exporter and determine if the status and features of the codebase are viable for use with production deployments.

https://github.com/fcrepo4-labs/fcrepo-import-export

This should happen before #463.

**Comment by sethaj** [comment]
To start with, here's heliotrope with only northwestern imported. You can see the file_sets (and monograph too) appear in the UI with their full pairtree path as "flat" children of the rest/dev/ node. I guess this is the way AF expects things to be.

![fedora-importer](https://cloud.githubusercontent.com/assets/3924142/20942292/cc9ec01c-bbc8-11e6-8bab-894f12d5b467.png)

Exported that data with this command:

`java -jar target/fcrepo-import-export-0.0.1-SNAPSHOT.jar --mode export --resource http://127.0.0.1:8984/rest --descDir /home/seth/fcrepo_test_export/desc --binDir /home/seth/fcrepo_test_export/bin`

Shutdown fedora, removed all it's files, restarted it and the repo was empty.

Imported the exported data back in with this command:

`java -jar target/fcrepo-import-export-0.0.1-SNAPSHOT.jar --mode import --resource http://127.0.0.1:8984/rest --descDir /home/seth/fcrepo_test_export/desc --binDir /home/seth/fcrepo_test_export/bin`

While the import seems to have worked, there are now fewer children (271 vs. 324). The file_sets are no longer "flat", meaning their pairtree has been expanded and they're no longer "direct" children of /rest/dev.

![fedora-imported](https://cloud.githubusercontent.com/assets/3924142/20942469/792d3a7a-bbc9-11e6-875a-1924d66114e1.png)

During the import, there were a lot of these warnings which seemed to happen on the monograph or file_set ids:

`WARN 15:14:42.866 (Importer) Skipping Membership Resource: http://127.0.0.1:8984/rest/dev/3f/46/27/68/3f462768p`

Now it seems that AF can't find anything:

```ruby
[1] pry(main)> FileSet.first
ActiveFedora: loading fedora config from /home/seth/apps/heliotrope/config/fedora.yml
ActiveFedora: loading solr config from /home/seth/apps/heliotrope/config/solr.yml
Attempted to init base path `dev`, but it already exists
ActiveFedora::ObjectNotFoundError: ActiveFedora::ObjectNotFoundError
from /home/seth/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.0.1/lib/active_fedora/relation/finder_methods.rb:194:in `load_from_fedora'
```

```ruby
[2] pry(main)> Monograph.first
ActiveFedora::ObjectNotFoundError: ActiveFedora::ObjectNotFoundError
from /home/seth/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.0.1/lib/active_fedora/relation/finder_methods.rb:194:in `load_from_fedora'
```

```ruby
[3] pry(main)> ActiveFedora::Base.reindex_everything
Re-index everything ... http://127.0.0.1:8984/rest/dev/qr
ActiveFedora::ObjectNotFoundError: ActiveFedora::ObjectNotFoundError
from /home/seth/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.0.1/lib/active_fedora/relation/finder_methods.rb:194:in `load_from_fedora'
[4] pry(main)>
```

There is of course **a whole lot** I don't know about fedora. The issues for the importer/exporter are in jira, https://jira.duraspace.org/browse/FCREPO-2330?jql=project%20%3D%20FCREPO%20AND%20component%20%3D%20f4-import-export and I've been looking through them.  I'm uncertain if anyone has used the importer/exporter in the way we're trying to yet.

There is an in progress ticket to test import/export on Penn State's Scholarsphere which sounds similar to what we want for now (although ultimately we'd want to export/import a single monograph/work, not the whole repo). Maybe the results of that ticket will help to inform what we should try next.

https://jira.duraspace.org/browse/FCREPO-2326

**Comment by jmcglone** [comment]
We may not need this anymore if we are creating content in a Prepper environment
