### ISSUE TITLE
Brand Indiana

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#587]
Add branding elements/customize for Indiana

Emailed Gary 11/1/16, 2/3/17

Outstanding:

- [ ] Indiana landing page copy
- [ ] Footer links
- [x] Colors to use for header, footer, links, etc.
- [x] Font to use for word logo in header/footer
- [x] Logo to use on landing page: Find the logo here: https://drive.google.com/drive/folders/0B-CNui8jTxj4aXIwUnluY3VEVzQ

**Comment by jmcglone** [comment]
style guide: https://styleguide.iu.edu/index.html

**Comment by jmcglone** [comment]
@mbakeryo ready for partner review. See attached screenshot for sharing with Gary.

![indiana-fulcrum](https://cloud.githubusercontent.com/assets/1686111/23173889/a8777b10-f828-11e6-9add-0ff52cead92b.png)

**Comment by mbakeryo** [comment]
@jmcglone Thanks, Jon. I'll send this over to Gary.
