### ISSUE TITLE
Add stats content block on monograph catalog page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#595]
Extend stats display on the monograph catalog page:

- [x] create a tab for "Stats"
- [x] display pageview stats over time using a line graph
- [ ] when/if enabled, display altmetric score

**Comment by jmcglone** [comment]
Address this in v2 (hyrax), roughly 6-months

**Comment by jmcglone** [comment]
@sethaj do you remember what this one is about? Is it extending the stats displayed on the monograph catalog page?

**Comment by jmcglone** [comment]
An example of graphical stats from the National Academies Press, where "Downloads over time" could be a model for "Pageviews over time":

![screen shot 2017-08-29 at 9 14 36 am](https://user-images.githubusercontent.com/1686111/29822776-ad944504-8c9a-11e7-9ade-437fdad6bc2a.png)

**Comment by conorom** [comment]
Monograph stats graph is done, the Altmetric stuff is covered by #257, so will close this.
