### ISSUE TITLE
Thumbnails Don't Change When Replacing a File

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#598]
Thumbnail URL's don't change when you replace a file. The FileSet ID stays the same etc etc.

Possibly add a cache-breaking parameter to these thumbnails (use FileSet mod time or similar on the download links downloads/dr26xx384?file=thumbnail).

- [ ] swapping out a FileSet's file results in an immediately-visible change to the thumbnail (once Resque is finished)

**Comment by sethaj** [comment]
I haven't been able to reproduce this problem in my dev environment yet.

**Comment by conorom** [comment]
It looks like the solution to this particular thumbnail mystery is that I was impatiently refreshing before the final Resque jobs were finished and then jumping to conclusions. Probably refreshing during the jobs and then resorting to hard refresh at the perfect time to think it did something extra. Thumbnail does change by itself. Do'h. May bad.
