### ISSUE TITLE
Deploy Chaudhuri/Michigan to Production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#601]
- [x] Update seeds.db file with Michigan information (including typekit, if needed)
- [x] Tag release
- [x] Deploy latest release tag branch to production
- [x] Run seeds.db to create Michigan
- [x] Contact A&E to setup redirects - all Michigan URLs
- michigan.fulcrumscholar.org -> fulcrum.org/michigan
- michigan.fulcrumservices.org -> fulcrum.org/michigan
- michigan.fulcrum.org -> fulcrum.org/michigan
- [x] Add Michigan GA ID (UA-77847516-8, view ID 132442623) to press db table for Michigan  
- [x] Generate handles for Michigan
- [x] Assign DOIs for Michigan
- [x] Register DOIs for Michigan

**Comment by sethaj** [comment]
DOIs are registered, they are:

```
https://doi.org/10.3998/fulcrum.4q77fr32b	concern/file_sets/4q77fr32b
https://doi.org/10.3998/fulcrum.jw827b69n	concern/file_sets/jw827b69n
https://doi.org/10.3998/fulcrum.jh343s28d	concern/file_sets/jh343s28d
https://doi.org/10.3998/fulcrum.q811kj674	concern/file_sets/q811kj674
https://doi.org/10.3998/fulcrum.1v53jw986	concern/file_sets/1v53jw986
https://doi.org/10.3998/fulcrum.0c483j399	concern/file_sets/0c483j399
https://doi.org/10.3998/fulcrum.4b29b598d	concern/file_sets/4b29b598d
```
We need to wait for #566 to be put into production. Then we can add the DOIs (manually through the form) and then we can close this ticket.
