### ISSUE TITLE
Michigan Chadhuri M4V video

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#625]
One of the provided videos is in m4v format, which may have been an oversight as they all look to have been processed the same way apart from that.
Its mime type is set correctly (the app and data register is as a video) but no code exists to create a derivative of or actually play a m4v.

We should probably ask for a version in mp4 like the others or convert it ourselves.

Apparently they convert easily to mp4 as the format is very similar, e.g.:
https://www.ethanmick.com/ffmpeg/

note m4v isn't in our Hydra/Fedora File Formats Guide:
https://docs.google.com/document/d/191o0OvIPHVO4Tw0vybVvBK3kaFjIOE6dUutLND9uCO4/edit

**Comment by mbakeryo** [comment]
The m4v has been replaced with a mp4 in the folder. I am not closing this until it is determined that this file will work. I've also updated the template so it says mp4.

**Comment by mbakeryo** [comment]
I've converted all of the files to .mov at 1080p. This appears to have cut down the file sizes for all, but some are still >2G.
