### ISSUE TITLE
In sort change "Chapter" label to "Section"

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#648]
<img width="170" alt="change label" src="https://cloud.githubusercontent.com/assets/17436011/20965907/d65fb1a6-bc45-11e6-90bc-aaa41e584b59.png">

Since we use "Section" elsewhere, such as faceting, this label should be consistent.

**Comment by mbakeryo** [comment]
Question: Should "Related Chapter" on the asset page be changed to read "Related Section" - again, for consistency of language?
