### ISSUE TITLE
Test all FileSet metadata

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#654]
As tedious as it is, it's probably time to add a test (or tests) that cover every FileSet metadata field. The focus is to show everything is saved, editable and behaves according to its cardinality. Multi-valued fields should have the correct widget on the edit page.

It's possible that it might be enough to flesh out/refactor existing tests to add all the fields and then check the edit forms. One of the larger import tests, for example.

**Comment by sethaj** [comment]
Maybe we can do this in the file_set_spec.rb model test? Need to investigate...
