### ISSUE TITLE
Migration-proof and collision-proof IDs

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#657]
We need Object IDs that have the following properties:
- [ ] The ID will remain stable if we migrate the content from a dev/prep repo to the production repo.
- [ ] Objects created by different Hydra apps will never have colliding IDs.

These requirements would be addressed if UM Library did the following:
* All apps / repos use a common ID minter / statefile / microservice.
* Each app appends its own namespace to IDs it mints.

However, at present, we're doing neither of these; each Hydra app (actually, each instance of each app) has its own statefile; and no app is using a namespace for its IDs. As a consequence, we're currently at risk of ID collisions, especially if we attempt to import content into the production repo.

We need one solution across all UM Hydra instances for sane ID management.

**Comment by jgmorse** [comment]
At one point we (Sebastien, Aaron, John W., Roger, MBY and I) agreed in a meeting that IDs should be NOIDs minted from an independent service.  See:
https://docs.google.com/a/umich.edu/document/d/1r9ur5NAKzRTssLxF8Tq4Aq7Qf-xdq9EEjfymGbY1LAQ/edit?usp=sharing

**Comment by jgmorse** [comment]
@botimer Will test to see if app namespaces already take care of this problem.

(Possible Implication: if we need apps to see objects created by other apps, we might need to modify the ActiveFedora model to allow namespace-switching.)

**Comment by jgmorse** [comment]
@botimer Wondering if you've had a chance to look into this... I'm also wondering if the namespaces are also sufficient to prevent an admin of one app from deleting the content from another app, or what other measures we need in place to prevent that happening.

**Comment by botimer** [comment]
Sorry... I have not yet looked into this. It's on my to-do list. I'll update soon.

**Comment by mbakeryo** [comment]
@botimer I think we've determined that namespaces resolve this. Can you please confirm? Thanks.

**Comment by mbakeryo** [comment]
We're closing this as we believe that this is done.
