### ISSUE TITLE
Disable HTML5 Video Download Button

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#670]
It appears that in the latest release of Chrome a video download button was added to the default HTML 5 video player controls.

We need this disabled/removed. It looks like there's a CSS hack for this: http://stackoverflow.com/a/41136470

We should make sure to test how this looks in Safari as well as Chrome since they're both (?) webkit based.

**Comment by jmcglone** [comment]
maybe we can try using bowser.js to detect chrome 55 and if true, set a class on the video element that hides the download button.

https://github.com/ded/bowser

**Comment by gkostin1966** [comment]
Here is a nice short article to get you up to speed on Shadow DOM

https://css-tricks.com/custom-controls-in-html5-video-full-screen/

IMHO hiding the implementation just leads to more headaches.
