### ISSUE TITLE
Remove minter_state.rb

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#675]
We have a file app/models/minter_state.rb that existed because of a bug in the way CC included ActiveFedora::Noid. Looks like this was fixed (in October!) so we should be able to remove this file now provided we're using a new enough version of CC.

See https://github.com/mlibrary/heliotrope/issues/292
See https://github.com/projecthydra/curation_concerns/pull/1061

**Comment by sethaj** [comment]
Actually, it looks like the last time we updated CC was also in October. We'll need to do that again before we remove the minter_state.rb file.

**Comment by val99erie** [comment]
In the [release notes for CC 1.7.0](https://github.com/projecthydra/curation_concerns/releases/tag/v1.7.0), I see this entry:
`2016-10-18: Change when AF::Noid is required so it doesn't break in production
mode. [Michael J. Giarlo]`
