### ISSUE TITLE
Monograph subjects should be multi-valued

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#682]
It looks like Monograph.subject should be multi-valued, but it's not. I think this goes back to the metadata template, but maybe it's in the importer somewhere.

It looks like right now we've got them separated by commas in the monograph.

![subject-multi-line](https://cloud.githubusercontent.com/assets/3924142/21696917/11421bea-d35e-11e6-8bd9-021987757a92.png)

In the importer:
https://github.com/mlibrary/heliotrope/blob/master/lib/import.rb#L26

Monograph includes BasicMetadata:
https://github.com/mlibrary/heliotrope/blob/master/app/models/monograph.rb#L5

In CC:
https://github.com/projecthydra/curation_concerns/blob/master/app/models/concerns/curation_concerns/basic_metadata.rb#L49

- [ ] Make sure the importer is saving subject for monograph as multi-valued.
- [ ] Since FileSets also include BasicMetadata, we have this in file_sets too. But we're not using subject there, not in the importer or the form, so it's always empty. I guess double check that this is intended.
- [ ] Go back and fix subjects in production for each monograph.

**Comment by conorom** [comment]
Been meaning to comment on this one for a while.
Changing `:yes` to `:yes_split` where you've linked in `/lib/import.rb` should be all that is required for future imports to assign this as multivalued.
The UI corrections should be quick as it's only one thing ;)

I've never been super-comfortable with the single/multivalued stuff. I would love if we could somehow define it all in a config or yml file and have that set *everything* else, including form widgets and maybe even Solr docs.

The monograph edit form is a mess, it's never been fixed up. We have a ticket to sanitize/test fileset cardinality and edit form. Maybe we should have one for monograph too or else think about rolling this into an overarching config file somewhere, if that would be possible.
