### ISSUE TITLE
Test Hyrax with umrdr

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#703]
- [x] Define the purpose of the testing (meeting set for January 23): https://docs.google.com/document/d/12Kg_cAk00OsSTvUKj3ZopudXhaZse8kvIcEwoSL0Nt0/edit?ts=588652b7
- [x] Decide what features are to be tested
- [x] Test

**Comment by mbakeryo** [comment]
You can find Val's recommendation/advice regarding Hyrax here: https://docs.google.com/document/d/1VVPRG-5SxXsBRMAhFK5nH6xZTYcZ43PUs_pr6mgmLp8/edit

**Comment by mbakeryo** [comment]
1/23/17 per Nabeela: Jose has updated the Gemfile and there is a branch 'hyrax' on mlibrary/umrdr code to explore

**Comment by gkostin1966** [comment]
Did a mashup of UMRDR Sofia 7.2 with Hyrax App
https://github.com/gkostin1966/umrdr/tree/sufia_mashup
