### ISSUE TITLE
Work with Princeton on CC to Hyrax

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#716]
During Sprint 25, Feb. 6/13 we will collaborate with Princeton to update vanilla CC to a point where it can be replaced with a stable version of Hyrax. This involves creating documentation and working on tickets.

**Comment by jmcglone** [comment]
Currently blocked until we hear back from Princeton

**Comment by jmcglone** [comment]
Princeton will upgrade first, take notes, and chat with us on Friday Feb 10.

**Comment by mbakeryo** [comment]
We'll meet again with Princeton on Friday, Feb 24. Invitation forthcoming.

**Comment by mbakeryo** [comment]
We'll meet with Princeton again on Friday, Feb 24. Invitation forthcoming.
