### ISSUE TITLE
Develop user stories for full text search

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#725]
What are the search behaviors we need to support? What are the kind of searches that we currently see in DLXS? How much can be handled by Solr and how much do we need to be aware of the structure of the text?

Start by spelling out what should be covered by Solr and what should be covered by other things.

- [ ] determine if cozy-sun-bear will offer a search widget / [CSB#46](https://github.com/mlibrary/cozy-sun-bear/issues/46)
- [ ] user stories exist specific to heliotrope
- [ ] user stories exist specific to cozy-sun-bear

**Comment by jmcglone** [comment]
@sethaj @jgmorse we talked a little about search in our sprint planning meeting today. this might be a good ticket to braindump some of the ideas we've been kicking around.

**Comment by mbakeryo** [comment]
This seems like it's being handled in other tickets. Will create new, more specific, tickets as stories emerge.
