### ISSUE TITLE
Establish data model for FET

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#726]
- [x] Provide documentation of a data model that maps the relationship among a Book, an EPUB file, assets that are embedded in the EPUB, and assets that are supplemental to the EPUB.
- [ ] Review and confirm/correct the model that represents what's currently implemented
- [ ] Review the FET section for viability
- [ ] Create second part of document for metadata fields

**Comment by jgmorse** [comment]
Candidate diagram:
https://drive.google.com/open?id=0B-18ovAEQgwvMEJFWDg3aHo4cW8

**Comment by jgmorse** [comment]
Updated (v0.4):  https://drive.google.com/open?id=0B-18ovAEQgwvZkNkeXB0Mi0tNWs

**Comment by jgmorse** [comment]
Updated diagram (v0.4):
https://drive.google.com/open?id=0B-18ovAEQgwvZkNkeXB0Mi0tNWs

**Comment by gkostin1966** [comment]
??? (was Press) currently exist as a record in the sqlite3 database table "presses".  The press.subdomain value a.k.a. "michigan", "indiana", etc. is store as a metadata field in the Monograph.

**Comment by jgmorse** [comment]
@gkostin1966 Is that the only way the Press is represented?  So it's not a Hydra Work/Fedora Object?

**Comment by gkostin1966** [comment]
Correct, The Publisher (a.k.a. Press) is not a Hydra Work/Fedora Object.

**Comment by jgmorse** [comment]
Updated:
https://drive.google.com/open?id=0B-18ovAEQgwvU1NxczFoWWtERWM
