### ISSUE TITLE
Embed code for video

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#730]
As a user, I can grab embed code (ie, iframe) for a video hosted on Fulcrum and include it in an HTML or EPUB3. This feature is needed for the NYUP title.

- [ ] investigate other embed code video features (YouTube, Vimeo)
- [ ] the asset page displays embed code that copies to a system clipboard
- [ ] embed code works (displays video) and is valid inside an EPUB3
- [ ] test inside epub3 file, ensure it validates, look at it inside readium

**Comment by gkostin1966** [comment]
http://blog.heyo.com/wp-content/uploads/2013/02/Vimeo-HTML-embed.png
