### ISSUE TITLE
Dashboard Publishers Index Page

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#735]
STORY
As registered user with at least one admin role I should be able to list all presses I administer.

ACCEPTANCE
- [ ] There is a privileged presses page restricted to admins.
- [ ] The page lists all presses that can be administered by the registered user.
- [ ] The page lists all presses for a platform admin.

**Comment by jmcglone** [comment]
Like this page, only restricted to platform admins, right?

https://heliotrope-staging.hydra.lib.umich.edu/presses
