### ISSUE TITLE
Check mobile aspect of AblePlayer

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#746]
Check back in early April 2017 to see if there is a new version for mobile.

**Comment by sethaj** [comment]
It looks like the master branch (which we're using) hasn't need updated in quite awhile.

Let's check back on this in July.

**Comment by sethaj** [comment]
The current version latest/release (3.0) hasn't changed yet. WIll check back later.

**Comment by sethaj** [comment]
The latest release is still 3.0.
