### ISSUE TITLE
Discuss how to change BP/P to account for non-traditional formats

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#788]
As a client, the metadata template field "Book and Platform or Platform only" is confusing because these options don't apply to my project.

The materials will not exist in either the print edition of the book or the ebook. 

However, the materials will exist in the Readium edition of the book. 

- [ ] Should this field change to account for some other type of selection, such as N/A? 

- [ ] What implications does this change have - does it require a change to the Exclusivity Facet?

- [ ] Does this have to be a required field? What are the implications if it isn't?

- [ ] What label changes would have to happen depending on the changed behavior?

**Comment by jmcglone** [comment]
If this is exclusive to the platform, flag it, otherwise leave it . This would no longer be required.  The facet would be Exclusive to Fulcrum.
