### ISSUE TITLE
Deploy Indiana to Production

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#792]
- [x] update seeds.db file with Indiana information n(including typekit id if needed)
- [x] tag release
- [x] deploy latest release tag branch to production
- [x] run seeds.db to create Indiana
- [x] import indiana, overwrite derivatives (all videos, 1 thumbnail)
- [x] contact A&E to setup redirects - all Indiana URLs redirect to fulcrum.org/indiana
indiana.fulcrumscholar.org -> fulcrum.org/indiana
indiana.fulcrumservices.org - > fulcrum.org/indiana
indiana.fulcrum.org - > fulcrum.org/indiana
- [x] Add Indiana's google analytics id (UA-77847516-6) to press database table for Indiana
- [x] Generate handles for Indiana

**Comment by mbakeryo** [comment]
3/23/17: Let A&E/Aaron know about Indiana going to production on March 30th and we'll need redirect work (gave him the URLs). Aaron said ok. We'll let him know when we're ready for the redirects.

**Comment by sethaj** [comment]
Here are a few notes for specific things that might be useful.

Deploying a new press, adding the press to the db:
```
$ ssh bulleit-1
$ cd /hydra/heliotrope-production/current
$ sudo -u heliotrope-production RAILS_ENV=production bundle exec rake db:seed
```

__The GA ID for the press should already be in the seeds.db file, so there's nothing to do__

Generating a list of noids to send to Jeremy to create handles:
```
First get the new monograph's noid then:
$ sudo -u heliotrope-production RAILS_ENV=production bundle exec rake "heliotrope:file_set_urls[MONOGRAPH_NOID]"
```

Reindex only filesets (maybe instead of ActiveFedora::Base.reindex_everything):
```
Monograph.all.each {|m| m.ordered_members.to_a.each {|f| p f.id && f.update_index }}
```

**Comment by gkostin1966** [comment]
"/concern/file_sets/qb98mf474","9780253022684_lrg.jpg"
"/concern/file_sets/kk91fk54w","The_Great_Salish_Sea_FINAL_1080.mp4"
"/concern/file_sets/41687h45k","Salmon_Come_Home_Chuitna_River_Mine_version_5_coal_web.mp4"
"/concern/file_sets/8w32r563r","SomtimesFinal1080.mp4"
"/concern/file_sets/hd76s006h","Dana_Label_GMO_Disco_version_3_webshare.mp4"
"/concern/file_sets/p5547r40t","Dana_Lyons_Cows_With_Guns_Animation_720p.mp4"
"/concern/file_sets/jh343s29p","Cows_With_Guns_claymation_for_iTunes_old.mp4"
"/concern/file_sets/x633f1022","Dana_Lyons_2013_Cane_Toad_Muster_720p.mp4"
"/concern/file_sets/tq57nr024","Dana_Molokai_hi_res.mp4"
"/concern/file_sets/bc386j235","1_Trade_Winds.wav"
"/concern/file_sets/cf95jb46b","2_Salmon_Come_Home.wav"
"/concern/file_sets/ft848q651","3_Everybodys_Got_a_Shovel.wav"
"/concern/file_sets/sf268509m","4_I_Need_The_Water.wav"
"/concern/file_sets/9c67wm86f","5_The_Great_Salish_Sea.wav"
"/concern/file_sets/ft848q669","6_Sometimes.wav"
"/concern/file_sets/j6731380t","7_The_Fingers_of_Jesus.wav"
"/concern/file_sets/fj2362093","8_Its_a_Matter_of_Asking.wav"
"/concern/file_sets/1544bp120","9_Just_Want_to_Be_With_You.wav"
"/concern/file_sets/cf95jb47m","10_Singing_Home.wav"
"/concern/file_sets/1j92g745j","11_Good_Morning_Eliza.wav"
"/concern/file_sets/mg74qm09p","12_Cane_Toad_Muster.wav"
