### ISSUE TITLE
Northwestern asset is missing

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#796]
Costume design for the Kapellmeister/Pianist, Columbine's Veil

The asset is not showing up on the asset page: http://hdl.handle.net/2027/fulcrum.t722h880z

(The thumbnail image on the book page is fine.)

**Comment by sethaj** [comment]
I suspect IIIF is having problems because the height/width are wrong.

![wrong-height-width](https://cloud.githubusercontent.com/assets/3924142/23753528/cd2eaa1a-04a7-11e7-9926-72282163c6d5.png)

I'm not sure how this got this way or when, but it can probably be fixed with a reindex.

`FileSet.find('t722h880z').update_index`

**Comment by gkostin1966** [comment]
Some how the original file height and width in fedora had two values!
```
> f =  FileSet.find('t722h880z')
=>  #<FileSet id: "t722h880z", ...>
> f.original_file.height
=> ["128", "3689"]
> f.original_file.width
=> ["90", "2792"]
> f.original_file.height = ["3689"]
=> ["3689"]
> f.original_file.width = ["2792"]
=> ["2792"]
> f.original_file.save!
```
So Seth and I changed it on production and it displays correctly now.

**Comment by conorom** [comment]
Just saw this again. Same deal in than an unwanted "128" is added to the height and "96" added to the width. I'm pretty sure I had to finish up with an `f.save!` as well to get everything working.

It's funny cause a regular update_index on the file randomly pulls these numbers out (lack of ordering stuff I presume), so you end up with a narrow horizontal or vertical strip most of the time. I wonder would the correct values be indexed 1 in 4 times! Wish I'd kept trying it now :)
