### ISSUE TITLE
Northwestern content fixes

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#802]
- [x] remove extra space in front of keyword plural perspective on the record [Fracischina and Gian Farina, etching](http://hdl.handle.net/2027/fulcrum.mw22v5474)
- [ ] change content type for Film and Film Scenes to single attribute [AWAITING AUTHOR TO INDICATE WHAT THE ATTRIBUTE SHOULD BE]
- [ ] test content type change first on staging
- [x] remove the "duplicated" FileSets meant to represent the same FileSet being attached to multiple sections and add the additional `section_title` to the single remaining FileSet
- [x] Send to Emily (Dassia) for preview

**Comment by mbakeryo** [comment]
4/28/17: Emailed NU to see if the content type change is an actual request (and, if so, what the attribute should be).

**Comment by mbakeryo** [comment]
@conorom Fyi, I just wrote Emily to find out if she is using each handle associated with an asset (so, both the chapter 1 handle and the chapter 3 handle) in the ebook. If so, this might complicate removing the duplicated FileSet. I think...

**Comment by conorom** [comment]
@mbakeryo we (or rather @jgmorse) should be able to point the removed assets's handle to the still-existing one? Probably the best option.

**Comment by mbakeryo** [comment]
@conorom @jgmorse That's what I was hoping. I'm still going to call this blocked until I know for sure how the handles are being used in NU's ebook.

**Comment by jgmorse** [comment]
Let me know which handles to modify and which handle is remaining unchanged, and it will only take a minute to make the changes.

**Comment by mbakeryo** [comment]
5/24/17: emailed Emily to see if we can get the ebook to refer to when making those handle changes.

**Comment by mbakeryo** [comment]
6/13/17: emailed Emily with request for feedback (from her and Dassia) about the removal of the duplicate entries for assets in multiple sections.

**Comment by mbakeryo** [comment]
7/6/17: emailed Emily again asking for feedback.

**Comment by mbakeryo** [comment]
10/19/17: Closing this ticket because partner never responded. Will create new ticket if we get response.
