### ISSUE TITLE
Unwanted Markdown in WebVTT

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#814]
'Greater than' signs in the WEBVTT are triggering markdown 'blockquotes' formatting (looks like email reply text).
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

IIRC I rendered the transcript as markdown to allow newlines to persist, which is essential, obviously. I didn't notice any markdown issues at that time.

This is the first thing to try:
http://stackoverflow.com/questions/28397943/preserve-newline-in-text-area-with-ruby-on-rails

![screen shot 2017-03-20 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/9595080/24112678/bdacefa8-0d70-11e7-831d-c95f300af080.png)

**Comment by mbakeryo** [comment]
@conorom I think this is bad construction on my part. Other transcripts use the >> without throwing a block quote. On the No Bees video, the issue looks to be that the >> doesn't have a space between it and the text, e.g., >>Ballser: Blah, Blah should be >> Ballser: Blah, Blah.

**Comment by mbakeryo** [comment]
@conorom I'm wrong with thinking that the space was causing the issue. Weird though that the >> works on some of the other transcripts. See Everything I've Got.
