### ISSUE TITLE
Change Press to Publisher

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#818]
Throughout Heliotrope change "Press" to "Publisher."

- [x] Create a checklist of where this is listed.
- [x] Make sure to change role from Press Admin to Publisher Admin

**Comment by gkostin1966** [comment]
Hyrax::BasicMetadata defines a "publisher" property and it would be too much work to make changes in Hyrax so we could have our own "publisher" property.  Hence stay with press is best in the long run from the coding perspective.  All user facing labels will be "Publisher" for the press table.

**Comment by gkostin1966** [comment]
Blocked by #962 Hyrax 2.0.0 upgrade
