### ISSUE TITLE
Adding users/roles meeting

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#819]
Meet to discuss how to handle creating users and assigning roles at Publisher set-up.

Ideally, as a Platform Admin, as part of setting up the Publisher, the Platform Admin could set-up the Publisher Admin(s) (formerly Press Admin) for the new Publisher, without having to wait for Publisher Admins to accept an invitation to create an account on Fulcrum.

Could the Platform Admin create the account for the Publisher Admin and set the privileges for that user? The Platform Admin, upon creating the account, would send an invitation to the Publisher Admin to accept and set-up the account, e.g. set a password. 

What happens if the Publisher Admin wants to use an email address different from the one the Platform Admin created?

What are the implications regarding passwords/password generation?

Would the invitation time out at some point?

Or, is it necessary to have the user create their account before the Platform Admin can assign them privileges? If so, how would they do that? (As we don't currently allow anyone to create an account, we'd have to send an invitation of some kind?)

**Comment by mbakeryo** [comment]
4/27/17: Move to backlog until Jeremy has a chance to talk with Sebastien. Also in context of Object class, etc. JM will circle back once conversation has evolved, use cases determined.

**Comment by jgmorse** [comment]
We should bring up these use cases in the 12/1 [Implementing Authz in Samvera](https://calendar.google.com/calendar/b/1/render#eventpage_6%7Ceid-MzRzbTFjYWEwNzI4Z2s2MHFiZnRwYzM5ZGwgamdtb3JzZUB1bWljaC5lZHU-1-0-) meeting.
