### ISSUE TITLE
How should downloads work?

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#820]
In #810 downloads (for file_sets that allow full downloads) was fixed to allow the user's browser to decide how best to handle the download of each file type. So for instance a video would be downloaded as a file in chrome (not displayed in the browser) but in FF I believe that same video would be displayed in the browser. An image would be displayed in a new tab for both chrome and FF. This is an improvement on what was happening before, but is it the behavior we want?

- [x] Test how downloads work for different file types on different browsers and platforms and document this.

- [x] Decide if this default behavior is what we want. If it's not, we'll need decide what we want and make a new story about the desired behavior.

**Comment by jmcglone** [comment]
If we want to force download for these use a combination of:

1) specifying [content-disposition: attachment in the header](https://en.wikipedia.org/wiki/MIME#Content-Disposition) and 
2) take advantage of HTML5 friendly browsers and add a `download` attribute to the download button and give it a value of the file to be downloaded. This will not be a clean fix across all browsers ([IE11, Safari 10 and iOS still don't read the `download` attribute](http://caniuse.com/#search=download)).

**Comment by conorom** [comment]
The base behavior for Hydra downloads is [here](https://github.com/projecthydra/hydra-head/blob/master/hydra-core/app/controllers/concerns/hydra/controller/download_behavior.rb), [usage](https://github.com/projecthydra/hydra-head/wiki/File-downloads).

A lot of folks override this, either directly or indirectly (including [CC](https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/download_behavior.rb)) or copy parts of it out into their download controller:
https://github.com/aic-collections/aicdams-lakeshore/commit/12a3ca29086e73dab32fe0f46d62096ca913c1d8
https://github.com/ndlib/curate_nd/blob/master/app/controllers/downloads_controller.rb

**Comment by conorom** [comment]
In the end I pulled a few lines from `Hydra::Controller::DownloadBehavior`, adjusted and shoehorned them into our downloads controller when the file being downloaded is the repo file. Added `content-disposition='attachment'` so the HTML5 download (which only works half the time) seems unnecessary.

No doubt this will be revisited anon...
