### ISSUE TITLE
Fulcrum Hydra Community Update - April 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#831]
- [x] Write up April community update
- [x] Feedback/modifications from Jeremy
- [x] Feedback/modifications from dev team
- [x] Send to Nabeela

Due Friday, April 7th, 2017

March's update: 3/7/17:

The Fulcrum team continued its exploration into migrating from Curation Concerns to Hyrax. The Fulcrum and Princeton teams met twice to review and discuss Princeton's work. Much appreciation to Princeton for all of their work and willingness to discuss their findings with us and fielding our questions. Ultimately, the Michigan team has decided to turn our immediate attention to our need to accommodate fully encoded text, as this is a main requirement from our Andrew W. Mellon Foundation grant, for which we will soon be entering our final year. Once this functionality has been more fully fleshed out and a plan made, we will return to the work of implementing Hyrax.

Additional work has been underway, such as developing a way to embed Hydra-hosted video and images into EPUB files and third-party e-book readers, reworking our data model by excising sections, and moving forward with identifying user roles and permissions in conjunction with the planning of our client user dashboard.

**Comment by mbakeryo** [comment]
@jgmorse Here is my attempt at a Hydra Community update for April. Could you please modify as needed? (I'd like to get this to Nabeela by end of day Friday, if possible.)

The Fulcrum team, in collaboration with the HathiTrust development team, has been working on building an epub reader application. The codebase name for the reader is Cozy Sun Bear [link to Cozy Sun Bear repo]. The basic functionality of the reader is in place in our development environment and we are currently working on additional functionality, as well as styling.

We have also begun building a Platform Administrator dashboard. The dashboard will allow Platform Administrators an efficient way to see and edit all Publishers, Books, Assets, and Users on the platform. Over the coming month(s), the dashboard will expand to include other user roles, such as specific Publisher Administrators and Editors, as well as other enhancements, like reporting and customizing options.

Finally, we are very pleased to announce that another of our Andrew W. Mellon grant partners, Indiana University Press, has launched their title A Song to Save the Salish Sea: Musical Performance as Environmental Activism [link to the book catalog page on Fulcrum] by Mark Pedelty onto Fulcrum. The materials available on Fulcrum include eight music videos and twelve audio files, all by well-known musician and environmental activist, Dana Lyons.

**Comment by jgmorse** [comment]
Looks good to me!

**Comment by mbakeryo** [comment]
4/10/17: Sent to Nabeela.
