### ISSUE TITLE
Resize Leaflet for Embed Code

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#836]
For image assets, the embed code should use a resized Leaflet container so that a limited amount of the Leaflet container displays.

FYI, may need a specific stylesheet for embed pages to do that.

**Comment by sethaj** [comment]
We could try out Roger's leaflet-iiif-um.js too as a replacement for leaflet-iiif.js. It might "just work" which would be nice.... It's here now: https://quod.lib.umich.edu/e/epistles/vendor/leaflet/plugins/leaflet-iiif-um.js

but Roger said he's going to try to get it up on mlibrary github.

**Comment by respinos** [comment]
It's in the mlibrary checkout, in the `best-fit-initial-zoom` branch:

https://github.com/mlibrary/Leaflet-IIIF/tree/best-fit-initial-zoom

Best fit is triggered by passing the option to the Leaflet layer:

https://github.com/mlibrary/Leaflet-IIIF/blob/best-fit-initial-zoom/examples/bestfit.html

e.g. `L.tileLayer.iiif("http://quod.lib.umich.edu/cgi/i/image/api/image/apis:3556:6238_33/info.json", { bestFit: true } );`

**Comment by conorom** [comment]
Pulling the "best-fit" stuff out into its own ticket:
https://github.com/mlibrary/heliotrope/issues/884
