### ISSUE TITLE
Investigate phantom.js on set-up

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#846]
In order to increase our testing coverage and fully test the UI of Fulcrum (clicking links and buttons etc.), we want to run acceptance tests on using phantom.js. Whatever framework we use it should integrate nicely with our existing testing framework.

**Comment by sethaj** [comment]
Possibly related to #898

**Comment by sethaj** [comment]
We should also replace a bunch of tests that were wedged into `spec/features` that try to make sure certain css selectors exists that our GA event tracking relies on(`assets/js/ga_event_tracking.js`). PhantomJS would be way better than trying to use rspec for those.

**Comment by jmcglone** [comment]
We will be using chrome headless in Hyrax 2
