### ISSUE TITLE
Handle registration service

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#847]
When I ingest an item into the Library's Fedora repository, in addition to the creation of a NOID, a handle should be created and registered for the item using the NOID assigned by Fedora. The namespace of the application should be included in the handle. For example:

`http://hdl.handle.net/2027/fulcrum.2n49t1809`

Because this is at the repository level, we feel this should be a Library-wide project and service.

**Comment by jgmorse** [comment]
The timing of when handle registration can occur (pre- or post-ingest) depends on the completion of #944.

**Comment by jgmorse** [comment]
For the record, here's the manual process I've been using:


1. Conor creates a _file.csv_ with the following format:
"/concern/file_sets/${NOID}","${filename}"
(any additional fields will be ignored)

2. tang:/l1/bin/f/fulcrum/makeHandleBatchFile.pl -f _file.csv_

This will create an output file _batch.YYYY-MM-DD.hdl_

3. This is the step that actually creates the handles:

java -mx128m -cp /l/local/hcj/handle.jar net.handle.apps.batch.GenericBatch _batch.YYYY-MM-DD.hdl_ [_batch.YYYY-MM-DD.log_]

4. Inspect log file _batch.YYYY-MM-DD.log_ for any result not labeled SUCCESS.

I've been keeping the logfiles in tang:/quod-dev/prep/f/fulcrum/handles  out of convenience/laziness.
