### ISSUE TITLE
Review documentation and provide feedback

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#848]
- [ ] Readme 
- [ ] Wiki
- [x] Dev set-up
- [x] Confluence "in-house" stuff

**Comment by conorom** [comment]
As part of this ticket we should review what's missing from Confluence and start putting stuff up there. Stuff that includes in-house details of server names etc etc.

**Comment by moseshll** [comment]
I've added a bit to the in-house stuff on Confluence with instance locations on nectar, and URLs.
