### ISSUE TITLE
Add Indiana to Fulcrum home page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#850]
Add to the home page:

- [x] cover of Indiana's A Song for the Salish Sea
- [x] short description of the book/how Fulcrum is being used (or added to the experience of the book....)
- [x] link to the book on Fulcrum (links on the title, cover image and a View Project button)

**Comment by mbakeryo** [comment]
As for the short description for the book, I'll send this to Gary and see if he can provide something better. 

In this book, Mark Pedelty explores Cascadia's vibrant eco-musical community in order to understand how environmentalist music imagines, and perhaps even creates, a more sustainable conception of place. Fulcrum enabled Indiana University Press to make available several music videos and songs by well-known musician and environmental activist Dana Lyons.

**Comment by mbakeryo** [comment]
4/6/17: Sent the above copy to Charles/Jeremy/Jon for modifying/ok.

**Comment by mbakeryo** [comment]
@jmcglone Hi - noticed a couple of things: Sailish should be Salish and the subtitle should be included (to be consistent with the other entries).

**Comment by jmcglone** [comment]
@mbakeryo okay, I will fix
