### ISSUE TITLE
Test for libtiff upgrades

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#856]
As documented in #367 we had a libtiff bug in the stock version of debian's libtiff that caused problems with derivatives. It was fixed with a specially compiled version of libtiff. A&E would like to standardize on stock versions of libraries where possible. There's a new debian version of libtiff, but does it have the same bug?

- [ ] Find the command that Hydra::Derivatives uses to create thumbnails from tiffs. Maybe stick a log statement somewhere like https://github.com/projecthydra/hydra-derivatives/blob/8098a1b32144f692e47d99c36e48142c97254c3e/lib/hydra/derivatives/processors/shell_based_processor.rb#L45 maybe ?
- [ ] Find the smallest tiff that we saw problems with in #367 and run the command on it. Make sure everything is working.
- [ ] Send the command and tiff to @sulemandiwan (or put it into conflunce) so he can run it when updating libtiff.

**Comment by aelkiss** [comment]
It's outside A&E's scope to run this test for you when updating imagemagick -- you should have a test in your test suite that exercises this failure scenario and the ability to point to a specific imagemagick binary when running that test suite.

**Comment by sethaj** [comment]
It sounds like we're going a different direction for this. I don't think we need a test in heliotrope for a bug produced by libtiff right now. If there's ever a problem we'll notice fairly quickly if a thumbnail looks wrong, and it's not like it breaks the app or anything.  And A&E will not be using these tests either. If there's ever a desire to make this kind of test in the app, we can open another ticket. So we'll do it the way we usually do with everything else: update in a staging environment, if the app is ok, then update in prod. Seems to work just fine.

**Comment by sethaj** [comment]
Just adding a note: In order to get minimagik to log first

1. Create a config/initializers/mini_magick.rb file
2. Add: 
```
require 'mini_magick'
MiniMagick.logger.level = Logger::DEBUG
```
It will log to where ever resque does.

**Comment by aelkiss** [comment]
I understand the concern that testing libtiff is outside the scope of your application. So long as you have a documented way to quickly tell whether a given version of libtiff/imagemagick/netpbm is working with heliotrope, that's fine. It can't become A&E's responsibility to test dependencies with each application, though - that would very quickly become unmanageable.
