### ISSUE TITLE
Monograph draft or published status

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#858]
On the dashboard, display the status of the book (aka monograph). Start with draft or published status (we will more than likely need to change or extend these status as we develop the workflow).

**Comment by mbakeryo** [comment]
4/27/17: Decided to wait until after Hyrax to see what we have available to us. Also, start with Discoverable status (not draft/published).

**Comment by sethaj** [comment]
Related to #839 ?
