### ISSUE TITLE
Upload Penn State Vol 2 metadata/assets

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#866]
Upload Penn State's metadata template and assets into dev environment.

Materials live here: https://drive.google.com/drive/folders/0B-CNui8jTxj4Wmo0WDVja2F5RHc

Notes: 

BP/P column answers are now Yes/No, but left in the original column position (as required). 

Also, for externally hosted resources, added generic language for Alt Text, since it is a required field, but there isn't an actual asset for there to be alt text on.

**Comment by conorom** [comment]
Reingested these with the no-file-on-the-FileSet code.
