### ISSUE TITLE
Brainstorm dashboard workflow - identify tickets

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#874]
Create new tickets
diagram out how users will work through dashboard
consider 3 user types

**Comment by mbakeryo** [comment]
Meeting set for Wednesday, April 19, 2017.

**Comment by mbakeryo** [comment]
Ingest workflow meeting set for Monday, May 1, 2017.

**Comment by mbakeryo** [comment]
@jmcglone @jgmorse I know we have more work to do on this, but should I close this ticket and just set up some kind of regular meeting for us to work through - and establish due date? Or I should I leave this ticket?

**Comment by jmcglone** [comment]
@mbakeryo agree that a regular meeting might be helpful for moving this forward. there are a few moving parts and a regular check-in might help keep things in line.

**Comment by jgmorse** [comment]
@mbakeryo Yeah, I think schedule regular meetings, close this ticket, and we generate more granular tickets based on those meetings.

**Comment by mbakeryo** [comment]
We've decided to close this ticket and set-up regular meetings to push this forward; tickets that emerge from those discussions will be added.
