### ISSUE TITLE
Add Moses as admin

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#875]
run rake task on wiki

**Comment by jmcglone** [comment]
@moseshll hey! if this is done please feel free to close

**Comment by moseshll** [comment]
Didn't think of it until today, then didn't want to muddy the waters with
the demo. But yeah, I will do so when I get a break.

**Comment by moseshll** [comment]
Also set myself up on the preview instance and verified that I'm in the database. I got a non-fatal warning about not having write access to a log file, presumably because I'm not on the `heliotrope-staging` and `heliotrope-preview` groups. Will follow up with A&E.
