### ISSUE TITLE
Catalog page icons for external resources

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#876]
We need icons for the monograph catalog page which will indicate that the item is an externally-hosted resource of a given type. This will replace the beautiful "3D link" icon <sniff>

So this ticket is to choose glyphicons, say, which will represent:
- [x] external textual item (current use case)
- [x] external image
- [x] external video
- [x] external audio

**Comment by gkostin1966** [comment]
http://getbootstrap.com/components/#glyphicons

text: glyphicon glyphicon-file
image: glyphicon glyphicon-picture
video: glyphicon glyphicon-film
audio: glyphicon glyphicon-volume-up (glyphicon glyphicon-headphones, glyphicon glyphicon-music)
