### ISSUE TITLE
Button styling (share link, list view)

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#877]
note: I just noticed the wrapping button issue is a "logged in only" problem, so really not critical.

- [x] The share link button on the FileSet page wraps and, especially with Penn State's solid turquoise buttons ends up looking "fused" with the buttons above it.

- [ ] While I'm nit-picking, Should the list view button to be rounded on the left side for symmetry?

**Comment by moseshll** [comment]
The list view button border-radius is being overridden by some Curation Concerns CSS first-child/last-child logic that seems to be stymied by… something? The hidden "View results as:" screenreader node. I think this is a CC bug, and I think it may be beyond me right now.

**Comment by conorom** [comment]
I wouldn't get too worked up over a few squared-off pixels. Had I realized I was logged in, I wouldn't have created this ticket at all. Once I wrote it I thought a second checkbox would be nice :-)
