### ISSUE TITLE
Edit Animal Acts to say edited by

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#879]
Currently, the authors line makes it look like Chaudhuri and Hughes are the authors of this book.

They instead should be displayed as the editors.

Change to say "edited by Una Chaudhuri and Holly Hughes"

Can we do this easily? If so, how? Or is this more complicated?

**Comment by jmcglone** [comment]
We should be using the Editors field (make sure it is multi-valued) for this. The show pages should be changed to display either the creators if they exist, OR, the editors. If editors are there the display needs to be prefixed with "Edited by".

QUESTION: is creator a required field by fedora? Because what I'm proposing above would mean that the creator field is empty for volumes that are "edited" rather than "authored".

**Comment by sethaj** [comment]
Creator doesn't seem to be required (depositor is I think, but that's not really relevant here). And author isn't required either.

So we could put the authors into the editor field(s), and then have a bit of logic in the template to show editors (if any) or authors.

The big problem is that the editor field is multi-valued and as such order is not guarenteed. So if we put more than one editor in, we can't predict which editor will be first. Is that a deal-breaker?

If it is, we can either 1) stuff both editors into a single field or 2) as with author, create a seperate "primary editor" field.

**Comment by mbakeryo** [comment]
@sethaj My expectation is that yes - the order matters. I'll check with LeAnn, but I'd be very surprised if she said otherwise.

**Comment by jmcglone** [comment]
We would also want to make sure this editor field gets added as a `meta` tag. In looking how we do this with the press website, we just stuff "Edited by Name One and Name Two" into a `<meta name="authors" ... >` tag.

**Comment by mbakeryo** [comment]
May 1, there will be work on this with DLA, Fulcrum team to watch how this gets resolved. Seth will send out a meeting invite.

**Comment by sethaj** [comment]
We actually need two fields for this: editor_first_name, editor_last_name (or something) because Crossref requires this. This will be the same as how we handle author (store first and last name seperatly, index them as fullname).
