### ISSUE TITLE
Penn State review

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#880]
- [x] Upload Penn State to preview so Patrick A. can review
- [x]  Send to Patrick for review
- [x] Feedback from Patrick
- [x] Make fixes per Patrick
- [x] OK to publish

**Comment by mbakeryo** [comment]
4/17/17: Sent email to Patrick, Jon, and Jennifer asking them to review the entry on Preview.

**Comment by mbakeryo** [comment]
5/9/17: List of changes from  Patrick: 

Robert Darden, former gospel music editor for Billboard [make italic] magazine and the founder of the Black Gospel Music Restoration [this is a bad break] “…More"

Project at Baylor University, brings this vivid, ...

Also, I noted in the caption of the fourth photo that Martin Luther King Jr. is identified as “Rev.” That should either read “Dr.” or “Rev. Dr.”  or simply “Martin Luther King Jr." This infelicity may occur elsewhere. Sorry I did not catch it before.

Another minor error. A serial comma is missing after “Allen” in the photo of John Lewis and Others.

Design change: 
One other design issue that I’m sorry I didn’t write about sooner. I think the serif text face used is a little hard to read (the copy on the home page under the head “Robert Darden” and also used for the book entries. Would it be possible to use the same text font that is being used for Northwestern and Minnesota while keeping the sans serif just as is?

**Comment by mbakeryo** [comment]
5/15/17: I don't know why _Billboard_ isn't italicized or why there is a bad break between Restoration and Project. 

This is what it looks like (on Staging/Preview): 
<img width="279" alt="screen shot 2017-05-15 at 6 25 47 am" src="https://cloud.githubusercontent.com/assets/17436011/26053599/6a98d37a-3937-11e7-8158-3ce9e66db779.png">

This is what it looks like when I went to edit the copy:
<img width="440" alt="screen shot 2017-05-15 at 6 21 42 am" src="https://cloud.githubusercontent.com/assets/17436011/26053612/78202e1c-3937-11e7-9265-30dc4f7b8329.png">

Help? Thanks!

**Comment by conorom** [comment]
The italics and unwanted paragraph are artifacts from the way the hidden div is generated to allow the More/Less links to work. That stuff becomes awkward when you allow HTML tags as your truncation might leave tags open etc and you'll have to fix that. The code we have now discards tags in the truncation area, which solves some problems... but hence no italics. The spacing problem is, I'm almost certain, the browser correcting for the fact that there is an unmatched <p> tag caused by the truncation. 

We need to decide how to tackle this.

**Comment by mbakeryo** [comment]
The issue outlined above was fixed via ticket 954

Received ok from Patrick and Jennifer to release at end of sprint.
