### ISSUE TITLE
Has EPub Indication?

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#890]
When a Monograph has an EPub what should appear on the Monograph catalog page?

What (if anything) should appear on the Publisher catalog page?

**Comment by jmcglone** [comment]
@gkostin1966 We have new mockups for the publisher and monograph catalog pages for monographs that have EPUBs.

Publisher catalog page:

![publisher-catalog-page](https://cloud.githubusercontent.com/assets/1686111/25244223/d61560e6-25cd-11e7-8cde-49637f67e81c.png)

- [ ] The "Read" button should be large and its URL should point to the EPUB asset/EPUB reader.
- [ ] The "More info" button should be smaller than the Read button and its URL should point to the monograph catalog page.

Monograph catalog page:

![monograph-catalog-page](https://cloud.githubusercontent.com/assets/1686111/25244567/41b81d7e-25cf-11e7-9460-7693baac2417.png)

As a first step for revising the monograph catalog page, I would follow the above mockup ([HTML version here](http://mlibrary.github.io/elderberry/press/book/index.html)) and 

- [ ] add a "Read Book" button into a button group with the "Buy Book" button
- [ ] The "Read Book" button should have URL that points to the EPUB asset/EPUB reader

A more final version of the monograph catalog page with EPUBs is below, which, I think is a completely separate ticket we can tackle in the future:

![monograph-catalog-page-2](https://cloud.githubusercontent.com/assets/1686111/25244297/17f3aef0-25ce-11e7-87cb-c8f314dfeb56.png)
