### ISSUE TITLE
User login routing

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#894]
- [x] When I login to fulcrum on the fulcrum.org homepage, as a platform, publisher, or book admin, I am taken to the dashboard home.

- [x] When I login to fulcrum from a publisher, book, or asset page, I am logged in and returned to the page that I was previously on (publisher, book, or asset page). Whatever my role/credentials, I can see edit buttons on the publisher, book, or asset page I am routed to.

**Comment by jgmorse** [comment]
@jmcglone Should that last sentence begin "If I have the proper role/credentials..."?

**Comment by sethaj** [comment]
Look at what Hyrax does and then decide.

**Comment by mbakeryo** [comment]
4/27/17: Review Hyrax to see what they do before moving forward with this.
