### ISSUE TITLE
Create user activity log and display recent activities in dashboard home

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#897]
Things to track when a user performs an action in the dashboard:

Date/Time
Publisher Affiliation of the user or content
Book or Asset title/ID
Action (Modify, Add, Delete)
User

We need to come up with examples of how these fields are formed into some sort of message. For example: 

> jmcglone Added _Book Title_ to University Press

Display the most recent (10 ) activities on the dashboard homepage with a link to the full log.

**Comment by mbakeryo** [comment]
Review Hyrax first

**Comment by sethaj** [comment]
DBD has an issue similar to this, https://github.com/mlibrary/umrdr/issues/639. Depending on scheduling we should try to develop a solution with them.

**Comment by sethaj** [comment]
Looks like the update to Hyrax definitely includes at least part of what we want. This is from heliotrope with Hyrax 1.0.1.

![user-activity-fulcurm-hyrax](https://user-images.githubusercontent.com/3924142/27149882-1d1cc41e-5113-11e7-8fb3-2cc8e5f28066.png)

**Comment by sethaj** [comment]
In hyrax2 there's still have the Activity Log for *normal user* in their dashboard, but if you're an admin you won't see one.
