### ISSUE TITLE
QC Minnesota (2) metadata template/assets

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#900]
Minnesota delivered their second metadata template on 4/20/17. Materials are here: https://drive.google.com/drive/folders/0B-CNui8jTxj4bjFWQnl6bFhPSzA

Use this metadata template: https://docs.google.com/spreadsheets/d/1Nmw0yiwfWk0mSuRvK_6s4GOT8v8ZwmE9MLNCHOaNbsc/edit#gid=1726739743

- [x] Make sure it has been filled in correctly
- [x] Adjust template as needed
- [x] Obtain files
- [x] Download files
- [x] Move to shared place on Google Drive: https://drive.google.com/drive/folders/0B-CNui8jTxj4bjFWQnl6bFhPSzA
- [x] Write up summary of assets/share: https://docs.google.com/document/d/1iprQPeOAaZwq_sB4v02dAW-olwKhYHw0MR-hBGJz2Xs/edit
- [x] Ingest metadata/assets into dev (staging, preview)
- [x] Make adjustments per Minnesota's review (on metadata template and preview)
- [x] Resend to Minnesota for final feedback
- [x] Reorder assets from second batch (based on section, put at the end, in the order on the template)

**Comment by mbakeryo** [comment]
4/24/17: Sent template back to Terence to fill in Copyright Holder for E_1-E_26 and E_30-E_39.

**Comment by mbakeryo** [comment]
4/28/17: Meet with @conorom on May 1st to go over list of questions regarding batch 2.

**Comment by conorom** [comment]
The original E_33.jpg won't ingest. I think it's a JPEG 2000. Maybe the file is partially corrupt, has a bad header or isn't what it says it is (or something).
GIMP won't open it either, so I guess open source stuff sticks to the rules and bows out when those rules aren't followed.

It opens fine in macOS Preview, where I exported it to a jpeg at highest quality settings. This made it increase from 0.5MB to 5MB. The resulting file ingests fine. I archived the ole one in a subfolder of the Google Drive and put the new file in its place.

For the record here are the ingest errors 
dev:
`identify: no decode delegate for this image format JP2`

![screen shot 2017-05-03 at 4 34 00 pm](https://cloud.githubusercontent.com/assets/9595080/25680468/f4b4e822-301e-11e7-9093-618ec91ecf85.png)


staging:
`identify: not a JPEG file: starts with 0x00 0x00`)

![screen shot 2017-05-03 at 4 33 37 pm](https://cloud.githubusercontent.com/assets/9595080/25680494/02207d78-301f-11e7-8cb9-d31533ec90ac.png)

**Comment by mbakeryo** [comment]
@conorom After speaking with Terence yesterday, he's comfortable using the version that you created. If we don't want to allow that and need him to provide a new file, let me know. Also, I will document that we cannot accept JPEG 2000 files in our onboarding documentation for publishers.

**Comment by conorom** [comment]
I dunno, Hydra Derivatives has code that looks like it's supposed to work with JP2 (JPEG 2000):
https://github.com/projecthydra/hydra-derivatives/search?utf8=%E2%9C%93&q=jp2

I'm guessing this particular file was malformed in some way that caused nerdier unix-y image tools to baulk. The `00 00` start here is reminiscent of one of the errors above:
http://fileformats.archiveteam.org/wiki/JP2

I can't think of a really quick way to see other JP2 files we've ingested, but I don't think we should blacklist them.

**Comment by conorom** [comment]
You were right @mbakeryo. It looks like we can't support JPEG2000 without taking steps to enable ImageMagick to process them. I pulled a JPEG2000 sample from the web and ran a few experiments.
The `0x00 0x00` error comes from when a `.jp2` file has a `.jpg` extension. This makes the process break down on my dev machine, though weirdly in the case above staging progressed to the `no decode delegate` stage in spite of this. I can to that point on dev by correcting the file extension.

This is where JP2 stuff ends on this ticket, methinks. We've agreed a solution with Terence for this one file.

We'll need to decide if we want to enable support for these images (another ticket and working with A&E) and/or if you should blacklist them for the time being.

**Comment by mbakeryo** [comment]
5/8/17: Awaiting a list of edits from Terence.

**Comment by mbakeryo** [comment]
5/9/17: Here are the corrections from Terence: 

GLOBAL CHANGE: Spell out all instances of photo (or photo.): photograph.

E_1.tif: Add italics to title in caption: Arthur Fitzwilliam Tait, _A Good Chance_, ca. 1863, lithograph print. Published by Currier & Ives for the American Hunting Scenes print series.

E_1.tif: Remove quote marks from the title.

E_3.tif: Capitalize last word of title: bay to Bay.

E_3.tif: Capitalize "bay" in caption—"...into Hudson's Bay."

E_3.tif: In caption, change "3rd." to "Third"—"Third edition, colored..."

E_4.tif: Add italics to title in caption: Joseph John Kirkbride, _Picnic along Shore of Lake, near Mouth of Socateau_, ca. 1884, photograph.

E_5.tif: Add italics to title in caption: T. W. Ingersoll, _Views of Dalles of the St. Louis River_, ca 1890, photograph.

E_5.tif: Add space between creator's initials: T. W.

E_10.jpg: Spell out "J. R. O'Connell" and "photograph" in the caption so that it reads: Album page with one photograph, “O.C.C. War Canoe Crew, Champions of Canada 1904,” with John R. O’Connell at center. Photograph and hand-illustration by John R. O’Connell.

E_10.jpg: Spell out the name of the creator: John R. O'Connell.

E_11.jpg: The creator first name should be changed to "Hildegard G."

E_12.tif: Adjust caption to read as such: Arnold Sevaried and Walter Port, from an article in the _Minneapolis Star_ published October 11, 1930.

E_12.tif: Italicize "Minneapolis Star" in the first sentence of the description.

E_16.jpg: Adjust caption to read as such: Natives making canoe from tree trunk at Mission ca. 1900. Photograph by Alexander McLean.

E_19.jpg: Adjust title adding the word "advertisement" to the end as such: Kennebec Boat & Canoe Co. Advertisement.

E_20.tif: Let's adjust the first part of the description to the following, which reverses the italics and quotation treatment from what is presently shown: _Calling Moose with the “Moose Horn”_ by Tappan Adney appears in _St. Nicholas: An Illustrated Magazine for Young Folks_, Volume 23, Part 1, November 1895 to April, 1896, accompanying a story titled, “The First Moose Hunt.”

E_24.tif: Adjust the description so that what is now treated in quotes is italized: _Indians Making Birch Bark Canoes_ is a wood-cut engraving published in _Harper’s Weekly_ in 1871. The illustration depicts Native Americans constructing canoes with birch bark on the shore of a lake.

E_25.jpg: Italicize (and remove quotes from) "In the Canoe" in both the caption and description.

E_31.tif: Let's change the caption to read: Modifications of the beaver hat as illustrated by Horace T. Martin in _Castorologia, or The history and traditions of the Canadian Beaver_.

E_31.tif: Add middle initial to creator name: Horace T. Martin.

E_32.tif: Adjust the caption as follows: Denis Diderot's depiction of a Parisien furrier from his _L’Encyclopie_, 1751–1757.

E_32.tif: Add "Parisien" before "furrier" in the description.

E_34.jpg: Add italics to the caption as follows: Tappan Adney, _The Moose Call_, 1902.

E_34.jpg: Italicize "Outing Magazine" in the first line of the description.

E_35.tif: Adjust the fist line of the description to read as follows: _Taking the Moose Back to the Camp_ by Tappan Adney appears in _St. Nicholas: An Illustrated Magazine for Young Folks_, Volume 23, Part 1, November 1895 to April 1896, accompanying a story titled, “The First Moose Hunt.”

video2: Adjust the caption to read: Walter Walker building a 16-foot cedar strip canoe, 1980.

video3: Adjust the caption to read: _Canoeing by Reg Blomfield_, ca. 1934.

video3: Adjust the description to read: Reg Blomfield, holder of International, Canadian and American championships, demonstrates some of the things that can be done in a canoe. This classic black and white film shows Blomfield demonstrating some exceptional open canoe skills and is dated around 1934 or 1935.

**Comment by mbakeryo** [comment]
5/15/17: Resent to Terence for final review. Blocked until then.

**Comment by mbakeryo** [comment]
5/16/17: Additional changes per Terence

- [ ] video2: Lowercase "building" in the caption: Walter Walker building a 16-foot cedar strip canoe, 1980.

- [ ] video3: Adjust the description, adding a comma after "Canadian" and hyphens to "black-and-white": Reg Blomfield, holder of International, Canadian, and American championships, demonstrates some of the things that can be done in a canoe. This classic black-and-white film shows Blomfield demonstrating some exceptional open canoe skills and is dated around 1934 or 1935.
