### ISSUE TITLE
Fulcrum Hydra Community Update - May 2017

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#904]
- [x] Write up May community update
- [x] Feedback/modifications from Jeremy
- [ ] Feedback/modifications from dev team
- [ ] Send to Nabeela

Due Friday, May 5th, 2017

**Comment by mbakeryo** [comment]
@jgmorse This is what I have cobbled together. Ok to send off to Nabeela?

May's update: 

In addition to continuing to develop the epub reader application, Cozy Sun Bear, the Fulcrum team has started to investigate and prepare for the migration to Hyrax from Curation Concerns. As we have been ramping up our work on building a Platform Administrator dashboard, we're particularly interested in seeing how much of this development comes standard in Hyrax and what level of customization will be necessary to accommodate our publishing workflow.

We are also focused on preparing the remaining publishing projects from our Andrew W. Mellon Foundation-funded grant for release to Fulcrum, with the expectation that these will be live before the end of May.

**Comment by jgmorse** [comment]
Looks good to me.
