### ISSUE TITLE
Brand NYUPress

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#905]
- [x] NYUP landing page copy
- [x] Footer links
- [x] Colors to use for header, footer, links, etc.
- [x] Font to use for word logo in header/footer
- [x] Logo, cover and fonts to use are here: https://drive.google.com/drive/folders/0B-CNui8jTxj4cUFRdUw0d1h4a1U

1. Cover image file of the monograph ("Gray_Front.jpg") is here: https://drive.google.com/drive/folders/0B-CNui8jTxj4MXRPaTJvRU96Z28
2. The NYUP logo is here: https://drive.google.com/drive/folders/0B-CNui8jTxj4cUFRdUw0d1h4a1U
From Lisha: Our marketing associate who gave these to me says: "We use Gotham on our website but to make our logo, we use Scala Sans and NYU Press Regular (the "A" key to make the arch). Attached are all of these fonts, three logos (two without backgrounds which have been used for online platforms before), and a design file for the logo that should work once these fonts are installed." Let me know if you need the logo delivered in a different format than in the attached.
3. Fonts. We use Gotham on our website, so would prefer to use that if possible, included in this folder: https://drive.google.com/drive/folders/0B-CNui8jTxj4cUFRdUw0d1h4a1U 
4. Colors. The purple we use is NYU purple and its specifics are below. The black is standard black.
(PMS 2597 C85, M100, Y0, K0 R87, G6, B140 HEX 57068c)
5. Copy. The copy for the landing page resides in the branding folder here: https://drive.google.com/drive/folders/0B-CNui8jTxj4cUFRdUw0d1h4a1U (file is NYU Press Fulcrum Landing  Page Copy.docx)
6. URL should be nyupress.fulcrum.org.

**Comment by jmcglone** [comment]
@mbakeryo Ok, here's a screenshot of the NYU Press homepage on fulcrum. Please share this with them for feedback. Important note: I could not use the fonts they provided for the typography of the body text – we do not have licenses for them nor do we have access to them in Typekit. I used the closest thing I could find to the typography they currently use on their website (Whitney).

![nyupress-fulcrum](https://cloud.githubusercontent.com/assets/1686111/26693203/595bb5a8-46d1-11e7-9c0e-8c3739a995be.png)

**Comment by mbakeryo** [comment]
6/1/17: emailed Monica and Lisha for feedback.
