### ISSUE TITLE
Platform Admin Dashboard - Home page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#911]
On the Platform Admin dashboard, make the following changes:

- [x] Throughout dashboard, in the lefthand navigation, change "Items" to "Assets"
- [x] Throughout dashboard, in the lefthand navigation, change "Books" to "Monographs"
- [x] On Home page, change "Repository Summary" page title to "Home" to match where the users are (this is the default dashboard home page for the Platform Admin). 
- [x] On "Home" page, Include subtitle (under Home title) that says "Fulcrum Summary"
- [x] On "Home" page, change "Books" label in summary to "Monographs" - throughout dashboard

**Comment by moseshll** [comment]
Page titles still display with the previous names, fixing that will require a couple file renames because the title is based on the partial's name.
