### ISSUE TITLE
Platform Admin - Add a Publisher Form

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#913]
As a Platform Admin, I should be able to add a new publisher to Fulcrum using a form. 

When I select Add Publisher (from Publishers Summary page), I should be taken to a Publisher Setup page that includes the following fields:

- [ ] Publisher Name
- [ ]  Subdomain
- [ ]  Path to logo
- [ ]  Publisher description
- [ ]  Publisher's main URL (to their external website)
- [ ]  Google Analytics Fulcrum ID
- [ ] Typekit ID

- [ ] When I save the publisher, the publisher is created

**Comment by jmcglone** [comment]
I need to create a wireframe of this before it can be worked on.

**Comment by jmcglone** [comment]
@mbakeryo @conorom 

Mockup of Add New Publisher page. This mockup can also be used as a mockup for the editing an existing publisher form, where the "Add New Publisher" text is replaced with "Edit Publisher". Feel free to ask questions or make suggestions as needed.

![addpublisher](https://cloud.githubusercontent.com/assets/1686111/25536152/b1476b48-2c07-11e7-808a-1e6a30c3ccea.png)
