### ISSUE TITLE
Update FITS and ffmpeg

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#929]
Work with A&E to update FITS and ffmpeg to new verions. 1.0.7 for FITS and 3.3 for ffmpeg. A&E will update these in staging/preview, we'll test, then they'll update them on production.

**Comment by sethaj** [comment]
I've tested this with michigan and northwestern. Both FITS and ffmpeg seem ok on staging.

**Comment by sethaj** [comment]
A&E will coordinate with the team to update FITS and ffmpeg in production nect week.

**Comment by jmcglone** [comment]
@sethaj done, right?

**Comment by sethaj** [comment]
Yes, all done. We won't be able to *really* test this until we add a new monograph in production, but the configuration is (should be) identical to staging/preview, so we should be all set.
