### ISSUE TITLE
Replace Minnesota Assets (that had restrictions)

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#940]
- [x] Download replacement files from Minnesota, place in shared space: https://drive.google.com/drive/folders/0B-CNui8jTxj4UDNISFJrOFM2UzA
- [x] Replace files on staging/preview
- [x] Review files to ensure they display correctly; Minnesota QC
- [x] Replace files on production

**Comment by mbakeryo** [comment]
@conorom I've uploaded the adjusted Minnesota files (from the first batch) to here: https://drive.google.com/drive/folders/0B-CNui8jTxj4UDNISFJrOFM2UzA.

**Comment by mbakeryo** [comment]
@conorom I've reviewed the files you posted to Preview. Looks like the image was switched on the wrong Shooting the Rapids. 

Should be on the Winslow Homer - this one: https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/8c97kq45j. 

Not the Frances Anne Hopkins: https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/7m01bk74n

If you could please restore the Hopkins and fix the Homer, I'll ask Terence to review and give his ok to proceed. Thanks!!

**Comment by conorom** [comment]
I fixed that. Sorry that was sloppy. Shouldn't rely on the spreadsheet to find these but rather the `original_file.file_name` (which becomes `label`, too) in the repository. So something like this in the console (want to record it here as a reminder, maybe Confluence later):
```
irb(main):001:0> FileSet.find('7m01bk74n').label
=> "8_9.tif"

irb(main):002:0> FileSet.find('7m01bk74n').original_file.file_name
=> ["8_9.tif"]
```

On the bright side, I noticed that the Frances Anne Hopkins image's thumbnail stayed the same the whole time, so that's another ticket to spin out of this.

**Comment by conorom** [comment]
Note: this thumbnail-not-changing thing is almost certainly just browser caching. 
We've seen that before and can wait till later to fix it. This could be done using a cache-breaking URL parameter, e.g. a mod date or checksum, if we can find something suitable to use.

**Comment by mbakeryo** [comment]
@conorom How do we move forward getting the revised assets onto production? Is this through an ingest process or is it manually on production or some combination?

**Comment by conorom** [comment]
@mbakeryo simply adding /edit to each FileSet's URL and uploading the new file seems to work fine for what we need here.

aside: I wouldn't be surprised if some of the low-level file metadata don't get set, e.g. mod dates. I went looking for a date that would indicate the file had been reupped yesterday but didn't see anything obvious. It's not a major concern. I might have been misunderstanding what Curation Concerns is using these dates for.

**Comment by mbakeryo** [comment]
Here are the files that were adjusted:
Haida Dugout in Kasaan (1_20.jpg)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/f1881k95p
https://www.fulcrum.org/concern/file_sets/gx41mh92t

Range of the Paper Birch (2_10.jpg)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/v405s941w
https://www.fulcrum.org/concern/file_sets/pv63g0260

Pearl (4_31.tif)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/v405s940m
https://www.fulcrum.org/concern/file_sets/1c18df77c

Leroy Grumman (6_39.jpg)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/2n49t176q
https://www.fulcrum.org/concern/file_sets/w08929935

Shooting the Rapids (8_1.tif)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/7m01bk74n
https://www.fulcrum.org/concern/file_sets/nz805z70r

Joe Mell (8_5.jpg)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/jq085j99x
https://www.fulcrum.org/concern/file_sets/8623hx748

Penobscot Canoe (Enys_3.tif)
https://heliotrope-preview.hydra.lib.umich.edu/concern/file_sets/2227mp69j
https://www.fulcrum.org/concern/file_sets/2r36tx569
