### ISSUE TITLE
Monograph with EPub shouldn't need to be indexed twice.

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#941]
When adding an EPub to a Monograph the Monograph needs to be reindexed twice for the EPub to be recognized.  

monograph_indexer.rb
      solr_doc[Solrizer.solr_name('representative_epub_id', :symbol)] = existing_fileset_order.find { |id| ['application/epub+zip'].include? FileSet.find(id).mime_type }

Rework the monograph_indexer so it recognizes the EPub the first time.

**Comment by jmcglone** [comment]
@gkostin1966 Also noticed that some EPUBs tend not to be recognized even after the Monograph is reindexed. See https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/x633f129g or https://heliotrope-staging.hydra.lib.umich.edu/concern/monographs/s4655g72c
