### ISSUE TITLE
Reserve a NOID

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#944]
- [ ] A trusted app can request a NOID for any hydra object (asset, monograph)
- [ ] The returned NOID is not already used in the Hyrda repo and is reserved so that it won't be assigned to anything else
- [ ] At a later time, the same trusted app can submit/create a Hydra object and assign it that same NOID as its Hydra ID.

**Comment by jmcglone** [comment]
similar model is used in Sipity https://github.com/ndlib/sipity

**Comment by sethaj** [comment]
Likely upcoming changes with NOIDs and Hyrax, https://github.com/samvera-labs/hyrax/pull/1049 might change how we want to think about this issue.

**Comment by mjgiarlo** [comment]
Note that on last week's Samvera Tech call, we decided **not** to deprecate NOID usage in Hyrax.
