### ISSUE TITLE
Hyrax 2.0.0

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#962]
- [ ] Port to Hyrax 2.0.0
- [x] add heliotrope-testing to nectar

**Comment by gkostin1966** [comment]
TODO: Set up travis.ci to use Sauce Labs.
http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

**Comment by gkostin1966** [comment]
Blocked by #1105 Update to Rails 5.1

**Comment by mbakeryo** [comment]
Still no release date, but looks like maybe Fall 2017

**Comment by sethaj** [comment]
https://docs.google.com/document/d/1MxG-tbarLu2DSlSeNzRpgMxAsQILZOO5BylrT2CkEXE/edit

**Comment by sethaj** [comment]
Steps for developers to update their own dev spaces:

bundle install
bundle exec rails hyrax:install:migrations
bundle exec rails db:migrate

If that blows up you should try (in mysql):

alter table checksum_audit_logs change column checked_uri version varchar(255);
alter table checksum_audit_logs change column passed pass tinyint(1);
alter table checksum_audit_logs drop index index_checksum_audit_logs_on_checked_uri;
Then try the migrations again.

(I think this can happen if you've previously run an older version of hyrax2)

Then reindex (if you have things in fedora):

bundle exec rake solr:reindex (or ActiveFedora::Base.reindex_everything)
