### ISSUE TITLE
Change Hydra references to Samvera

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#974]
On the fulcrum static pages, we make reference to Hydra. Find those references and update them to Samvera.

- [x] `fulcrum/about.html`
- [x] `fulcrum/index.html`
- [x] https://publishing.umich.edu/projects/hydra (?)
-- the URL with "hydra" in it has been kept to avoid broken links, but the title of the page has changed.
- [x] https://publishing.umich.edu/projects
- [x] hydra tag on publishing and press (?) blogs
- [x] https://www.press.umich.edu/about
- [x] github `README` and repo description, tags
- [x] "Made possible by the Hydra project" footer
- [x] github wiki

**Comment by moseshll** [comment]
Is the Hydra Camp VM going to be renamed? I am assuming that paths & URLs -- like `hydra-dev/` on nectar -- are going to be left alone for the time being.

**Comment by conorom** [comment]
Probably we should stop using the Hydra Camp VM and start using this one:
https://github.com/samvera-labs/samvera-vagrant
which is referenced from the Hyrax README as of yesterday:
https://github.com/samvera/hyrax

Currently I think we reference a Hydra Camp "camper" box directly, this is the repo:
https://github.com/curationexperts/camper
This is the camper page, from where our current Vagrantfile is (mostly) stolen:
http://camp.curationexperts.com/

**Comment by conorom** [comment]
Regarding the paths on nectar, I guess we should bring that up in a meeting with the wider hydra-dev group. Doesn't seem like it's something to be rushed into.
