### ISSUE TITLE
The "Resource type" facet should have the label "Format"

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#975]
Pre-hyrax the "Resource Type" field had the label of "Format" in the facets of the monograph catalog page. Post-hyrax it's back to "Resource Type". Not sure why. Need to make sure the label: "Format"  in the monograph_catalog_controller.rb is working correctly.

**Comment by gkostin1966** [comment]
Hyrax uses locales and "Resource Type" is in ./config/locales/hyrax.en.yml.
Appending... 
  blacklight:
    search:
      fields:
        facet:
          resource_type_sim: Format
to ./config/locales/en.yml solves the issue.
