### ISSUE TITLE
Create an about page for a press

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#98]
**STORY**
As a press owner, I would like to be able to set up an about page for my press, so that customers can find out more about my press than I want to show on the main landing page.

**Comment by jmcglone** [comment]
Lever Press will probably want this

**Comment by jmcglone** [comment]
http://leverpress.org

**Comment by jmcglone** [comment]
This will also be needed to Gabii Project Reports Series (as a publisher) -- see ticket #1453
