### ISSUE TITLE
Move press branding logos out of assets

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#980]
We should move the different press branding logos out of `app/assets/images`. Now that they can be created/destroyed by users they should not be in the app (or git).

Change here: https://github.com/mlibrary/heliotrope/blob/master/config/initializers/carrierwave.rb#L12
but also remember to move the existing logos.

Maybe they should live somewhere like `~/tmp/images/logos`?  By default carrierwave wants to put them in in `~/tmp/uploads` (I think?) but we clean out `~/tmp/uploads` with a cron/rake task nightly, https://github.com/mlibrary/heliotrope/blob/master/lib/tasks/clean_cache.rake#L29

- [x] If we choose to add a new directory like `~/tmp/images/logos` then we need to make sure the deploy scripts know that that it is a shared directory (like `~/tmp/derivatives` is).

- [x] We also need to make sure the logos/images work in the templates. Right now they might be making use of the asset pipline in a way we won't be able to do if we move them to `~/tmp`

**Comment by conorom** [comment]
When you automatically generate an uploader with CarrierWave the default for `store_dir` is this:
```
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
```
... which means a press logo would end up somewhere like this:
`/uploads/press/logo_path/27/nyupress.png`

As we're already referencing logos in CSS I think it makes more sense to use the subdomain in the path, rather than the DB id. So this will work in the CSS:
`background-image: url("/uploads/press/logo_path/nyupress/nyupress.png");`

**Comment by conorom** [comment]
Also, as `/public` is already in our deploy scripts' shared folder, we shouldn't need to change anything there. I think.

**Comment by conorom** [comment]
Actually, after testing on staging I think we'll need a new link inside the `public` directory (I had assumed the entire public directory would be linked). Like this:
`uploads -> /hydra-dev/heliotrope-staging/shared/public/uploads/`

**Comment by gkostin1966** [comment]
FYI: I needed to set write permissions on the public folder in my development environment.
