### ISSUE TITLE
Tombstone an item 

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#994]
Collaboration opportunity with DBD. This is their ticket: https://github.com/mlibrary/umrdr/issues/19 

A view page for an item can be modified to become a tombstone such that it has the following properties:

- [ ] Display "reason message" on the page that gives more information about the current status of the item.  (At this stage, we can use default message like "This item is no longer available on Fulcrum"  (i.e. no reason given).)
- [ ] Remove the technical information tab from the asset page
- [ ] Put a generic icon (?) as the thumbnail on the catalog page to indicate a tombstoned asset (do we want to follow the external resources model - the type of file it is - audio, text, video, etc.?)
- [ ] Add an event to the object tracking history.

A tombstone should be triggered when any of the following conditions is met:
- [ ] It has been triggered manually by a user with the platform_admin role. (The means to manually trigger can be implemented in a separate ticket.)
- [ ] The access version of the bitstream has been removed from Fedora.
- [ ] The current date equals or exceeds the value in Permissions Expiration Date.

**Comment by mbakeryo** [comment]
Are we tombstone-ing the full work or the files attached to the work? (Fwiw, at least for this use case, we need to maintain the asset page as well as the listing of the asset on the catalog page. Only the asset itself will no longer be available - so it's very similar to how we handle external resources.)

**Comment by mbakeryo** [comment]
On Thu, Apr 28, 2016 at 8:42 PM, John Weise <jweise@umich.edu> wrote:
Here is a HathiTrust example of a tombstone for an item that had been accessible, but no longer is...

https://babel.hathitrust.org/cgi/pt?id=mdp.39015059379050;page=root;seq=1;view=image;size=100;orient=0

The full catalog record can be viewed, plus the following is displayed...

This item is no longer available in HathiTrust due to one of the following reasons:
It was deleted at the request of the rights holder or has been marked for deletion.
It was either wholly unusable or a superior copy is available.
Try a new search for your item to see if there are other copies or editions of this work available.

**Comment by jgmorse** [comment]
I think I'm restating Melissa's first comment: we'll need this for both FileSets and Works (since we'll have to tombstone books at some point).  Does that mean:
- [ ] We can reuse DBD's work for monographs?
- [ ] Can the trigger for tombstoning a book optionally cascade to all its children?

**Comment by jgmorse** [comment]
Do we want to automatically remove tombstoned items from search?  Is there a case for keeping them searchable?

**Comment by sethaj** [comment]
There's been some work on tombstones, https://github.com/mlibrary/heliotrope/issues/955 which consider something "tomestoned" if it was once in Fedora, but now is not (aka "Ldp::Gone").

But I think we should look at tomestoning the way DBD is doing it. Bascially adding a field "tombstone" and then changing display behaviour based on that:

https://github.com/mlibrary/umrdr/commit/8f2e90175532ae5c851727086ec246328902f7d7#diff-5e9283bc634ace7fd59ff3248ab54c7b
