### ISSUE TITLE
remove extra whitespace at top of page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#999]
in hyrax, on the top of the page, there is extra whitespace added to the page. remove this by adding an override to the `app/assets/css/heliotrope.scss` file

**Comment by sethaj** [comment]
Fulcrum w/ **Hyrax** has extra whitespace:

![hyrax-whitespace](https://user-images.githubusercontent.com/3924142/26943620-3b320d74-4c54-11e7-8dd9-c2223a219466.png)


That Fulcrum w/ **CurationConcerns** did not have:

![cc-no-whitespace](https://user-images.githubusercontent.com/3924142/26943632-4504580c-4c54-11e7-9a3f-95de8d43e386.png)

**Comment by moseshll** [comment]
`app/assets/css/heliotrope.scss` does try to override `margin-bottom` but it gets overridden by Hyrax styles. An `!important` looks like it will fix things.

**Comment by jmcglone** [comment]
This is okay for now but we should make another ticket to order heliotrope.scss to load after hyrax styles, so we won't need to use `!important` to override styles.

**Comment by moseshll** [comment]
Based on some of the linkage Conor sent me, and a little experimentation,
it looks like files listed earlier in application.css override those listed
further down. This seems counterintuitive, and I'd like to find a way to
verify it. But I agree that a cleaner solution is preferable.
